### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by prathibhacdac** [OpenSIPS/opensips#3160] opened 2023-08-21 08:40 UTC
**OpenSIPS version you are running**

```
version: opensips 3.5.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 9376d60c7
main.c compiled on 06:47:18 Aug 11 2023 with gcc 11
```

**Crash Core Dump**

```
Traceback (last included file at the bottom):
Aug 21 08:04:35 [210492] CRITICAL: 0. //etc/opensips/opensips.cfg
Aug 21 08:04:35 [210492] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:250:12-14: syntax error
Aug 21 08:04:35 [210492] CRITICAL:      if (is_method("REGISTER"))
Aug 21 08:04:35 [210492] CRITICAL:      {
Aug 21 08:04:35 [210492] CRITICAL:              if(proto == WSS) {
Aug 21 08:04:35 [210492] CRITICAL:              ^~~
Aug 21 08:04:35 [210492] CRITICAL:                      fix_nated_register();
Aug 21 08:04:35 [210492] CRITICAL:              }
Aug 21 08:04:35 [210492] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:250:12-14: bare word <proto> found, command calls need '()'
Aug 21 08:04:35 [210492] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:250:12-14: bad command!)
Aug 21 08:04:35 [210492] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:250:18-19: bare word <WSS> found, command calls need '()'
Aug 21 08:04:35 [210492] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:250:18-19: bad command: missing ';'?
Aug 21 08:04:35 [210492] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:250:20-21: bad command!)
Aug 21 08:04:35 [210492] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:256:3-5: syntax error
Aug 21 08:04:35 [210492] CRITICAL:core:yyerror: parse error in //etc/opensips/opensips.cfg:256:3-5:
Aug 21 08:04:35 [210492] ERROR:core:parse_opensips_cfg: bad config file (8 errors)
Aug 21 08:04:35 [210492] ERROR:core:main: failed to parse config file (null)
Aug 21 08:04:35 [210492] NOTICE:core:main: Exiting....

```

**Describe the traffic that generated the bug**

**To Reproduce**
**opensips.cfg**
```
####### Global Parameters #########

log_level=3
stderror_enabled=no
syslog_facility=LOG_LOCAL0

#children=4

/* uncomment the following line to enable debugging */
#debug_mode=yes

/* uncomment the next line to enable the auto temporary blacklisting of
   not available destinations (default disabled) */
#disable_dns_blacklist=no

/* uncomment the next line to enable IPv6 lookup after IPv4 dns
   lookup failures (default disabled) */
#dns_try_ipv6=yes

/* comment the next line to enable the auto discovery of local aliases
   based on revers DNS on IPs */
auto_aliases=no


socket=udp:172.31.34.24:5060   # CUSTOMIZE ME
socket=wss:172.31.34.24:443   # CUSTOMIZE ME



####### Modules Section ########

#set module path
mpath="/lib64/opensips/modules/"

#### SIGNALING module
#loadmodule "signaling.so"

#### StateLess module
loadmodule "sl.so"

#### Transaction Module
loadmodule "tm.so"
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 30)
modparam("tm", "restart_fr_on_each_reply", 0)
modparam("tm", "onreply_avp_mode", 1)

#### Record Route Module
loadmodule "rr.so"
/* do not append from tag to the RR (no need for this script) */
modparam("rr", "append_fromtag", 0)

#### MAX ForWarD module
loadmodule "maxfwd.so"

#### SIP MSG OPerationS module
loadmodule "sipmsgops.so"

#### FIFO Management Interface
loadmodule "mi_fifo.so"
modparam("mi_fifo", "fifo_name", "/tmp/opensips_fifo")
modparam("mi_fifo", "fifo_mode", 0666)


#### URI module
#loadmodule "uri.so"
#modparam("uri", "use_uri_table", 0)

#### USeR LOCation module
loadmodule "usrloc.so"
modparam("usrloc", "nat_bflag", "NAT")
modparam("usrloc", "db_mode",   0)

#### REGISTRAR module
loadmodule "registrar.so"
modparam("registrar", "received_avp", "$avp(received)")

/* uncomment the next line not to allow more than 10 contacts per AOR */
#modparam("registrar", "max_contacts", 10)


loadmodule "nathelper.so"
modparam("nathelper", "received_avp", "$avp(received)")

#### ACCounting module
loadmodule "acc.so"
/* what special events should be accounted ? */
modparam("acc", "early_media", 0)
modparam("acc", "report_cancels", 0)
/* by default we do not adjust the direct of the sequential requests.
   if you enable this parameter, be sure the enable "append_fromtag"
   in "rr" module */
modparam("acc", "detect_direction", 0)


#### UDP protocol
loadmodule "proto_udp.so"

loadmodule "proto_wss.so"
modparam("proto_wss", "wss_max_msg_chunks", 16)

loadmodule "tls_mgm.so"
modparam("tls_mgm", "domain_col", "erss.in")
modparam("tls_mgm", "match_ip_address_col", "172.31.34.24")
modparam("tls_mgm", "match_sip_domain_col", "bp3.erss.in")
modparam("tls_mgm","verify_cert_col", "1")
modparam("tls_mgm","require_cert_col", "0")
modparam("tls_mgm","tls_method_col", "TLSv1")

modparam("tls_mgm", "certificate_col", "/home/ubuntu/fullchain.pem")
modparam("tls_mgm", "private_key_col", "/home/ubuntu/privkey.pem")
modparam("tls_mgm", "verify_cert_col", "0")
modparam("tls_mgm", "require_cert_col", "0")

loadmodule "rtpengine.so"
modparam("rtpengine", "rtpengine_sock", "udp:localhost:12225")



####### Routing Logic ########

# main request routing logic

route{
        if (!mf_process_maxfwd_header("10")) {
                sl_send_reply("483","Too Many Hops");
                exit;
        }

        if (has_totag()) {
                # sequential requests within a dialog should
                # take the path determined by record-routing
                if (loose_route()) {

                        if (is_method("BYE")) {
                                # do accunting, even if the transaction fails
                                do_accounting("log","failed");
                        } else if (is_method("INVITE")) {
                                # even if in most of the cases is useless, do RR for
                                # re-INVITEs alos, as some buggy clients do change route set
                                # during the dialog.
                                record_route();
                        }

                        # route it out to whatever destination was set by loose_route()
                        # in $du (destination URI).
                        route(relay);
                } else {

                        if ( is_method("ACK") ) {
                                if ( t_check_trans() ) {
                                        # non loose-route, but stateful ACK; must be an ACK after
                                        # a 487 or e.g. 404 from upstream server
                                        t_relay();
                                        exit;
                                } else {
                                        # ACK without matching transaction ->
                                        # ignore and discard
                                        exit;
                                }
                        }
                        sl_send_reply("404","Not here");
                }
                exit;
        }

        # CANCEL processing
        if (is_method("CANCEL"))
        {
                if (t_check_trans())
                        t_relay();
                exit;
        }

        t_check_trans();

        #if ( !(is_method("REGISTER")  ) ) {
        #       if (from_uri==myself)
        #       {
        #       } else {
                        # if caller is not local, then called number must be local
        #               if (!uri==myself) {
        #                       send_reply("403","Rely forbidden");
        #                       exit;
        #               }
        #       }
        #}

        # preloaded route checking
        if (loose_route()) {
                xlog("L_ERR",
                "Attempt to route with preloaded Route's [$fu/$tu/$ru/$ci]");
                if (!is_method("ACK"))
                        sl_send_reply("403","Preload Route denied");
                exit;
        }

        # record routing
        if (!is_method("REGISTER|MESSAGE"))
                record_route();

        # account only INVITEs
        if (is_method("INVITE")) {

                fix_nated_contact();

                if($rU =~ "[0-9]{1,}") {

                        rtpengine_offer("replace-origin replace-session-connection ICE=remove RTP/AVP");
                        $ru ="sip:"+$rU+"@146.185.161.38:5070";
                        route(relay);

                }


                do_accounting("log");
        }

        #if (!uri==myself) {
        #       append_hf("P-hint: outbound\r\n");
        #       route(relay);
        #}

        # requests for my domain
        if (is_method("PUBLISH|SUBSCRIBE"))
        {
                sl_send_reply("503", "Service Unavailable");
                exit;
        }

        if (is_method("REGISTER"))
        {
                if(proto == WSS) {
                        fix_nated_register();
                }

                #www_

                if (!save("location"))
                        sl_reply_error();

                exit;
        }

        if ($rU==NULL) {
                # request with no Username in RURI
                sl_send_reply("484","Address Incomplete");
                exit;
        }

        # do lookup with method filtering
        if (!lookup("location","m")) {
                t_newtran();
                t_reply("404", "Not Found");
                exit;
        }

        # when routing via usrloc, log the missed calls also
        do_accounting("log","missed");
        route(relay);
}


route[relay] {
        # for INVITEs enable some additional helper routes
        if (is_method("INVITE")) {
                t_on_branch("per_branch_ops");
                t_on_reply("handle_nat");
                t_on_failure("missed_call");
        }

        if (!t_relay()) {
                send_reply("500","Internal Error");
        };
        exit;
}




branch_route[per_branch_ops] {
        xlog("new branch at $ru\n");
}


onreply_route[handle_nat] {

        fix_nated_contact();

        rtpengine_answer("UDP/TLS/RTP/SAVPF");

        xlog("incoming reply\n");
}


failure_route[missed_call] {
        if (t_was_cancelled()) {
                exit;
        }

        # uncomment the following lines if you want to block client
        # redirect based on 3xx replies.
        ##if (t_check_status("3[0-9][0-9]")) {
        ##t_reply("404","Not found");
        ##      exit;
        ##}

}


```

**Relevant System Logs**

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

**Additional context**

**Comment by razvancrainea** [comment] 2023-08-31 06:50
Duplicate of #3163

**Closed by razvancrainea** 2023-08-31 06:50 UTC
