### ISSUE TITLE
[BUG] add_body_part has unexpected behaviour. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [OpenSIPS/opensips#1943] opened 2020-01-21 12:08 UTC
**OpenSIPS version you are running**

```
version: opensips 3.0.1 (x86_64/linux)
flags: STATS: On, EXTRA_DEBUG, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a9d07b55f
main.c compiled on 08:07:34 Jan 10 2020 with gcc 6.3.0
```

**Describe the bug**

**To Reproduce**

We sent a sip message with one word Réunion. 
We change the encoding from utf8 to gsm7 using a lua function. 
[submmit_sm.zip](https://github.com/OpenSIPS/opensips/files/4090960/submmit_sm.zip)

Result is : 5205756e696f6e (correct). 
Next we attach the result to the body.   

We expect to see the result string send out, but instead we get : 52**a3c9**756e696f6e

**Expected behavior**

We expect the correct string to be send out. 

**Relevant System Logs**

'''see above'''

**OS/environment information**
 - Operating System: 
 - OpenSIPS installation: 
 - other relevant information:

    Operating System: Debian 9
    OpenSIPS installation: git clone https://github.com/OpenSIPS/opensips.git -b 3.0 opensips-3.0.1

**Additional context**

**Comment by razvancrainea** [comment] 2020-01-21 14:15
Oh, damn, I've just noticed - the problem is that the SMPP module does not look into the resulted "body", but rather in the initial body as well. That's why you get the same string as the one on the inbound.
To sort this out, you will have to loop the message back to OpenSIPS, and then call the `send_smpp_message()` function. I know this is not pleasant, but that's the only way it works right now.

**Comment by johandeclercqdemocon** [comment] 2020-01-21 14:25
Hello razvan, will it be corrected in the future?

**Comment by razvancrainea** [comment] 2020-01-21 14:33
Yes, we will work out an alternative.

**Comment by volga629-1** [comment] 2020-01-21 15:01
Yes, right now we use

```
                uac_replace_from("", "$avp(from_alias)");
                append_hf("X-Loop-Hdr: 1\r\n");
                t_relay( ,"tcp:my ip:my port");
```

**Comment by razvancrainea** [comment] 2020-01-21 15:07
Using the latest aa01dac commit, you can drop the `remove_body_part();` and `add_body_part();` from your script, and simply call `send_smpp_message("session", , , $avp(formatted-msg))`.

**Comment by volga629-1** [comment] 2020-01-21 15:13
@razvancrainea  Thank you for prompt help.

Is source and destination numbers can be  vars ?

**Comment by razvancrainea** [comment] 2020-01-21 15:18
Yes, they can be vars too.

**Comment by razvancrainea** [comment] 2020-01-22 09:55
Now that there's an alternative for this fix, I am going to close this ticket. Thanks for your report!

**Closed by razvancrainea** 2020-01-22 09:55 UTC
Labels: improvement, script bug, wontfix

**Comment by johandeclercqdemocon** [comment] 2020-01-22 10:02
Thank you for the help :-)
I agree with closure.   If I encounter other issues on smpp, then I will
comment on the original ticket.


Op wo 22 jan. 2020 om 10:55 schreef Răzvan Crainea <notifications@github.com

**Comment by johandeclercqdemocon** [comment] 2020-01-24 08:34
Message sent in : Réunion

DBG:proto_smpp:send_submit_or_deliver_request: MESSAGE: 5205756e696f6e type = 0

resulting pcap is attached : every digit is prefixed with 3. 

Is there somehting that I am overlooking ? 
[message_put_on_wire.zip](https://github.com/OpenSIPS/opensips/files/4107404/message_put_on_wire.zip)
