### ISSUE TITLE
RTP after 100 Trying is relayed at Private IP

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#704] opened 2015-11-25 00:30 UTC
Hello

I have a strange situation were a carrier which I am interconnected with is sending RTP after 100 Trying and before 180 Ringing with SDP. 

First of all I am not sure if the Carrier should send the RTP

Second, RTP stream is forwarded to the calling party which probably shouldn't and more strange is forwarded at the private IP of the calling party even if the fix sdp was called during call setup from the calling party.

After 180 with SDP received everithing is normalized.

OpenSIPs 2.1.1 (latest from git)
RTPEngine 4.2

The flow.

OpenSIPs to Customer Trace

91.217xxx is the OpenSIPs
94.70xxx is the Customer
192.168xxx is the local IP of the customer

![image](https://cloud.githubusercontent.com/assets/7074737/11384796/a3161000-931b-11e5-9f9f-14fa37175c6e.png)

OpenSIPs to Carrier Trace

91.217xxx is the OpenSIPs
62.xxx is the Carrier's Signaling
62.16xxx is the carrier's Media

![image](https://cloud.githubusercontent.com/assets/7074737/11384838/0df8e4ce-931c-11e5-8995-25d5017c3a43.png)

**Comment by razvancrainea** [comment] 2016-05-26 14:40
Hi, Anthony!

Apologies for answering so late, probably the problem is already solved. But I will give you my feedback anyway.
First, there's nothing wrong if the carrier sends RTP when it receives the INVITE.
Regarding the destination, it looks like rtpengine only knows the private IP of the caller, because that's all it can "learn" from the SDP. Unfortunately I am not so familiar with rtpengine's internals, so I am not sure if this can be tuned. However, to me it appears as a legit call flow.

As this does not look like a programming bug, I will close this issue. If you have any further questions, I think discussing on the mailing list would be more suitable, probably over there we will find more people familiar with the internals of rtpengine.

Best regards,
Răzvan

**Closed by razvancrainea** 2016-05-26 14:40 UTC
