### ISSUE TITLE
[SSL] opensips segfault last git

### ISSUE THREAD

**Issue by volga629** [OpenSIPS/opensips#1304] opened 2018-03-10 19:06 UTC
Hello Everyone,
Opensips last  git 79418dce9 is segfaulting.

````
Mar 10 13:53:27 canldev01-fedora27 kernel: opensips[20957]: segfault at 7f0d5e8d12c0 ip 00007f0d5c5edca6 sp 00007fffa9fc62f0 error 4 in libcrypto.so.1.1.0f[7f0d5c491000+25b000]

Mar 10 13:53:27 canldev01-fedora27 systemd-coredump[20967]: Process 20957 (opensips) of user 973 dumped core.#012#012Stack trace of thread 20957:#012#0  0x00007f0d5c5edca6 ossl_init_thread_stop (libcrypto.so.1.1)#012#1  0x00007f0d5c5edf5d OPENSSL_cleanup (libcrypto.so.1.1)#012#2  0x00007f0d6295eb58 __run_exit_handlers (libc.so.6)#012#3  0x00007f0d6295ebaa __GI_exit (libc.so.6)#012#4  0x00007f0d62944011 __libc_start_main (libc.so.6)#012#5  0x000056384bee6bba _start (opensips)

````

````
[root@canldev01-fedora27 ccpp-2018-03-10-14:04:22.967345-21688]# gdb coredump
GNU gdb (GDB) Fedora 8.0.1-36.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
[New LWP 21688]
Reading symbols from /usr/sbin/opensips...Reading symbols from /usr/lib/debug/usr/sbin/opensips-2.4.2.79418dce9-11.fc27.x86_64.debug...done.
done.

warning: Ignoring non-absolute filename: <linux-vdso.so.1>
Missing separate debuginfo for linux-vdso.so.1
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/39/0ac8cf94ebb7b5e423d7d902785b4334407a08
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ossl_init_thread_stop (locals=0x7f95107362c0) at crypto/init.c:332
332	crypto/init.c: No such file or directory.
(gdb) bt
#0  ossl_init_thread_stop (locals=0x7f95107362c0) at crypto/init.c:332
#1  0x00007f950e452f5d in OPENSSL_cleanup () at crypto/init.c:400
#2  0x00007f95125c3b58 in __run_exit_handlers (status=-1, listp=0x7f95129656f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at exit.c:83
#3  0x00007f95125c3baa in __GI_exit (status=<optimized out>) at exit.c:105
#4  0x00007f95125a9011 in __libc_start_main (main=0x560a2207b5e0 <main>, argc=5, argv=0x7fffecc26938, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffecc26928) at ../csu/libc-start.c:342
#5  0x0000560a2207fbba in _start ()
(gdb) bt full
#0  ossl_init_thread_stop (locals=0x7f95107362c0) at crypto/init.c:332
No locals.
#1  0x00007f950e452f5d in OPENSSL_cleanup () at crypto/init.c:400
        currhandler = <optimized out>
        lasthandler = <optimized out>
#2  0x00007f95125c3b58 in __run_exit_handlers (status=-1, listp=0x7f95129656f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at exit.c:83
        atfct = <optimized out>
        onfct = <optimized out>
        cxafct = <optimized out>
        f = <optimized out>
#3  0x00007f95125c3baa in __GI_exit (status=<optimized out>) at exit.c:105
No locals.
#4  0x00007f95125a9011 in __libc_start_main (main=0x560a2207b5e0 <main>, argc=5, argv=0x7fffecc26938, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffecc26928) at ../csu/libc-start.c:342
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 3856016081354425424, 94601520610192, 140737165551920, 0, 0, 7379376172713575504, 7403129135869396048}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7f9512d99c13 <_dl_init+259>, 0x7f9512d87d58}, data = {prev = 0x0, cleanup = 0x0, canceltype = 316251155}}}
        not_first_call = <optimized out>
#5  0x0000560a2207fbba in _start ()
No symbol table info available.
(gdb) 
````

**Comment by volga629** [comment] 2018-03-12 14:19
We use latest available version


````
[volga629@canldev01-fedora27 ~]$ rpm -qa | grep openssl
openssl-libs-debuginfo-1.1.0f-9.fc27.x86_64
openssl-libs-1.1.0g-1.fc27.x86_64
openssl-debugsource-1.1.0g-1.fc27.x86_64
openssl-devel-1.1.0g-1.fc27.x86_64
rubygem-openssl-2.0.5-87.fc27.x86_64
openssl-1.1.0g-1.fc27.x86_64
openssl-debuginfo-1.1.0f-9.fc27.x86_64
compat-openssl10-1.0.2m-1.fc27.x86_64
[volga629@canldev01-fedora27 ~]$ 

````

**Comment by razvancrainea** [comment] 2018-04-24 12:29
This is also a duplicate of #1121. Closing now and following there.

**Closed by razvancrainea** 2018-04-24 12:29 UTC
Labels: bug, duplicate
