### ISSUE TITLE
db_http crashes OpenSIPs

### ISSUE THREAD

**Issue by apsaras** [OpenSIPS/opensips#523] opened 2015-05-26 20:56 UTC
We found out that if cap_raw_query is not set to 1 when needed, and the http db url is called from avp_db_query, opensips is crashing.

May 26 20:52:25 sip-proxy01 /sbin/opensips[13126]: DBG:avpops:ops_dbquery_avps: query [123321123]
May 26 20:52:25 sip-proxy01 /sbin/opensips[13080]: DBG:core:handle_sigs: status = 11
May 26 20:52:25 sip-proxy01 /sbin/opensips[13080]: INFO:core:handle_sigs: child process 13126 exited by a signal 11
May 26 20:52:25 sip-proxy01 /sbin/opensips[13080]: INFO:core:handle_sigs: core was not generated
May 26 20:52:25 sip-proxy01 /sbin/opensips[13080]: INFO:core:handle_sigs: terminating due to SIGCHLD
May 26 20:52:25 sip-proxy01 /sbin/opensips[13120]: INFO:core:sig_usr: signal 15 received
May 26 20:52:25 sip-proxy01 /sbin/opensips[13122]: INFO:core:sig_usr: signal 15 received
May 26 20:52:25 sip-proxy01 /sbin/opensips[13103]: INFO:core:sig_usr: signal 15 received
May 26 20:52:25 sip-proxy01 /sbin/opensips[13097]: INFO:core:sig_usr: signal 15 received
May 26 20:52:25 sip-proxy01 /sbin/opensips[13082]: INFO:core:sig_usr: signal 15 received
May 26 20:52:25 sip-proxy01 /sbin/opensips[13092]: INFO:core:sig_usr: signal 15 received

OpenSIPs 2.1.0

**Comment by liviuchircu** [comment] 2015-05-27 08:12
This should have been fixed by commit 8d978ac4 - which addressed the real issue behind (lack of DB capabilities - and OpenSIPS shouldn't start). Marking this as a duplicate of issue #405.

I will try to see why the fix is incomplete.

**Comment by apsaras** [comment] 2015-05-27 08:50
If I not wrong I have a newer version installed and the problem is there. So please check that once more.

git rev-parse HEAD 
9cd6e6f8e238f15d2f0686a433fb2074b79cb48b

git describe --tags
2.1.0-24-g9cd6e6f

Thank you Liviu

**Comment by liviuchircu** [comment] 2015-05-27 09:20
You are correct, Antonis. I can confirm the problem is still there when using an extra avpops DB url. (non-default)

This is due to the fact that mod_init is run before module function fixups. Patch need a bit of rework.

**Closed** 2015-05-27 10:12 UTC
Labels: bug, duplicate
