### ISSUE TITLE
[BUG] F_MALLOC memory leak

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#2476] opened 2021-04-19 21:28 UTC
**OpenSIPS version you are running**
```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 19:20:36 Apr 19 2021 with gcc 8
```

**Describe the bug**
When using `F_MALLOC` in OpenSIPS 3.1 there is a memory leak. The leak is not present when using `Q_MALLOC`. It seems to have started early on in the 3.x version, but it has been quite difficult to track down to a specific commit due to instability of that early release (ie segfaults, CPU hangs, etc). The leak does not appear to be present on the 2.4 branch, as all of our production/dev 2.4 services reach steady-state as expected.

One observation is that `free -m` reports the memory use as `buff/cache` instead of `used` like I have seen in previous application memory leaks.  That alone isn't necessarily indicative of a memory leak as OS could have some influence here, however, the reported `available` memory has inverse trend of `buff/cache` and eventually drops to 0 and OS resorts to SWAP.

Here are some [minimal scripts](https://github.com/OpenSIPS/opensips/files/6338599/opensips_memory_leak.zip) that I have been using to test 2.4, 3.0, and 3.1.

The following graphs were constructed via `google/cadvisor` container running on same host as OpenSIPS. I did not provide them, but internal OpenSIPS memory stats look normal.

![F_MALLOC_leak](https://user-images.githubusercontent.com/36895232/115303877-d4272b80-a129-11eb-9b8f-347f04279d0f.png)

I confirmed the issue exists all the way back to version 3.0.0, at which point tests start to break from other issues. Any recommendations or pointers to suspect commits to test would be greatly appreciated!

**To Reproduce**
1. Start OpenSIPS w/ provided minimal scripts using F_MALLOC.
2. Start traffic at around 200CPS.
3. Monitor host memory for memory leak.

**OS/environment information**
 - Operating System: `Debian 10`
 - OpenSIPS installation: `git`

**Comment by john08burke** [comment] 2021-04-20 02:38
I was able to tighten the possible commit window down to 7b48e4e (good) and d1fbd99 (bad) before I started running into segfaults.  Doing an inspect on that commit window via `git log 7b48e4e..d1fbd99 --oneline` yields 68 possible commits:

Unfortunately, this looks to be the timeframe where allocators underwent significant rework.

```
27d355f57 mem: fix pkg_malloc_func
abb33165b mem: fix gen_rpm_* signatures
7f84a9be3 mem: make functions signatures consistent
6e05a4d3a mem: provide functions for alloc "macros"
c2a2033d6 mem: fix hp_block warning
b6a8ec322 drouting: remove useless free_rt_data() all param
8792c5b83 drouting: cleanup module
c6eb2335b mem: fix magic warning
a5393b6b2 mem: add rpm statistics
2ed7d0c06 mem: add flexible key-value restart persistent storage
c7cca6be8 mem: add support for HP malloc for restart persistency
a426d7dfd mem: add support for persistent memory storage
0846b2bd8 fix harmless compile warnings
a1c1172ad shmem: make shm_getmem() receive fixed address
3c4918887 Merge pull request #1645 from goharahmed/master
b8cf9336d Fixed bug where any addr get positive match in config if cluster_id is invalid or Invalid IP addr is given to cluster_check_addr()
b931ffe57 Merge pull request #1643 from rrb3942/postgresql_bulk_fix
44394e322 Fix AVP context over sending requests via local route.
c0e12b420 Merge pull request #1644 from SB-JohnK/patch-1
f99eeee21 Correct spelling of 'typically' from 'tipically'
d1ef89600 Fix errors on bulk insert after delete/update
c6ee8265b Rebuild documentation
be8d3a8f0 deb packaging: add mi_html module
e5fd28efa mid_registrar: Fix poorly handled lifetime reductions
f575d1fe1 uac_registrant: when transitioning a shtag to backup state, move shtag-ed records to NOT_REGISTERED_STATE state
2af3aa1c4 F_MALLOC: Remove unused "sanity checking" logic
0fd7b9ff9 mem/common.h: Relocate inline allocator detection code
d4f023e8d mid_registrar: Fix possible crash in mode == 2
da20233c6 mem debugging: Use the proper "status" functions
158f98e93 Red Hat init.d: Adjust stop command to 2.4 shutdown behavior
a2a305fc2 clusterer: Fix missing lock_release() calls
5b0beac7c Create issue templates
59669b27d uac_registrant: doc: fix escaping
b46346f12 uac_registrant: fix copy/paste error
c41c690a5 uac_registrant: doc updates
f95014d07 uac_registrant: force single registration for records with reg-id and +sip.instance params
4a22a7ba9 shared memory: Drop shm_resize()
bc74237c1 Fix compile warning
67026770d HP_MALLOC: Update copyrights
8a668851e PKG mem: Clean up header file
e7a283993 Rebuild documentation
fbecd4397 Add new compile flag: CC_O0 (zero compiler optimizations)
1f821b1ac Merge branch 'feature/selectable-allocator'
d2f780cb8 OPS-6: Allocator codebase - fix coding style
9349a061a OPS-6: Add new "allocator" cmdline options (-a, -k, -s)
8b054a173 OPS-6: Refactor QM_MALLOC into Q_MALLOC
243fcee7a OPS-6: HP_MALLOC - don't always allocate the stats lock
572f0df73 OPS-6: HP_MALLOC / F_MALLOC - remove redundant logic
4adb1bb50 OPS-6: Better organize some SHM_EXTRA_STATS code
c7d02c0a7 OPS-6: Add a memory manager printing function
41ad6727f OPS-6: Fix shutdown issues with multi-allocators
a6a0d812f OPS-6: Fix additional incompatibilities
6d7b8ec71 OPS-6: Fix some subtle bugs
23fea2f8c OPS-6: Update Makefile.conf.template comments
c202cfc2a OPS-6: SHM_EXTRA_STATS is once again functional
7a1cf1d92 OPS-6: Drop USE_SHM_MEM support
a58f76c0d OPS-6:  All 3 allocators may now compile together
ad60d1f7c Fix pres/subs listing via new MI
9e842178d rest_client: Explicitly set retcode_pv to 0 on error
9002881a6 OPS-6: F_MALLOC and HP_MALLOC may now compile together
e4e9e6941 OPS-6: F_MALLOC and QM_MALLOC may now compile together
320e4126b Add transformation {ip.matches,ip/masklen}
5e6cf56ff OPS-6: HP_MALLOC is once again functional
67ed0ccba OPS-6: Fix some F_MALLOC issues
af1f01342 OPS-6:  QM_MALLOC is once again functional
c8804d280 OPS-6: Major allocator rework - F_MALLOC is functional
78afd259e Rebuild documentation
ea959e19a OPS-6 (Selectable Allocator): Clean up VQ_MALLOC
```

**Comment by liviuchircu** [comment] 2021-04-20 07:49
Excellent work, @john08burke!  Looking your graphs and git bisect results, it's pretty clear that something went wrong during the allocator rework.  Let me see if I can reproduce this, so we can have it fixed ASAP.

**Comment by liviuchircu** [comment] 2021-04-20 16:18
@john08burke using your `3.1` config file and `F_MALLOC`, I performed the following:

* stress test that showed no memory leak.  Note that due to [demand paging](https://en.wikipedia.org/wiki/Demand_paging#:~:text=operating%20system%20trap.-,Advantages,utilizes%20large%20amounts%20of%20resources.), during the first ~30 seconds of the stress test, OpenSIPS will gradually request more and more lazily loaded pages from the Operating System, thus creating the "illusion" of a memory leak.  See this short video for a demo:

![no-leak-demo](https://user-images.githubusercontent.com/4446084/115429706-5720b280-a20c-11eb-9223-31013b0fd428.gif)

* manually added a memory leaking `malloc(8192)` call in `t_relay()`, then did the same stress test.  Here is how the leak should really manifest:

![leak-demo](https://user-images.githubusercontent.com/4446084/115429809-6f90cd00-a20c-11eb-87a5-f669a6f2fe9d.gif)

Same conclusions for `Q_MALLOC`.  OpenSIPS memory management can be confusing at times (because it "fake allocates" all of its shared memory pool in one go).  And, to prove the lazy page loading behavior from the Operating System side, here is proof that my OpenSIPS successfully boots with `70 GB` of memory, even though my PC does NOT have that much RAM!

```
liviu     254049  0.0  0.0 71722280 6816 ?       S    19:16   0:00 ./opensips -dd -a F_MALLOC -m70000 -M32 -f /var/tmp/memleak-test.cfg -w .
liviu     254050  0.0  0.0 71722280 436 ?        S    19:16   0:00 ./opensips -dd -a F_MALLOC -m70000 -M32 -f /var/tmp/memleak-test.cfg -w .
liviu     254051  0.0  0.0 71722280 436 ?        S    19:16   0:00 ./opensips -dd -a F_MALLOC -m70000 -M32 -f /var/tmp/memleak-test.cfg -w .
liviu     254052  0.0  0.0 71722280 2004 ?       S    19:16   0:00 ./opensips -dd -a F_MALLOC -m70000 -M32 -f /var/tmp/memleak-test.cfg -w .
liviu     254053  0.0  0.0 71722280 2004 ?       S    19:16   0:00 ./opensips -dd -a F_MALLOC -m70000 -M32 -f /var/tmp/memleak-test.cfg -w .
liviu     254054  0.0  0.0 71722280 2004 ?       S    19:16   0:00 ./opensips -dd -a F_MALLOC -m70000 -M32 -f /var/tmp/memleak-test.cfg -w .
liviu     254055  0.0  0.0 71722280 2004 ?       S    19:16   0:00 ./opensips -dd -a F_MALLOC -m70000 -M32 -f /var/tmp/memleak-test.cfg -w .
liviu     254056  0.0  0.0 71722280 1924 ?       S    19:16   0:00 ./opensips -dd -a F_MALLOC -m70000 -M32 -f /var/tmp/memleak-test.cfg -w .
```

So I will close this ticket until further notice.  Cheers!

**Closed by liviuchircu** 2021-04-20 16:18 UTC
Labels: invalid

**Comment by john08burke** [comment] 2021-04-20 17:07
Hey @liviuchircu! Looks like you are right... I was too impatient in my tests, I retried and memory reaches steady-state at the SHM setting.  This behavior must have been a part of the allocator refactor? As in 2.4 and earlier memory steady-state wasn't really tied to the SHM `-m` argument and (at least in our ENVs) was rarely fully used.  This is good info to know!  It might be worth documenting that it should be expected that OpenSIPS will consume full SHM with F_MALLOC.

Anyways, thanks for verifying and apologies for the invalid issue!

**Comment by liviuchircu** [comment] 2021-04-20 17:17
The pre-allocation behavior of the SHM pool has been the same since the very beginning, with all allocators.  It would be interesting to understand the why `2.4` and `3.0` behaved differently in your tests, as the allocator rework just made a bunch of code compile together, rather than separately.  There were no major logical reworks on any of the allocators in the process, except for the usual micro-fixes and micro-improvements :)

But, anyway, I wouldn't dwell on it too much for now.  As `3.1` and `3.2` get more and more usage, we will understand more about this area of the code naturally.

**Comment by john08burke** [comment] 2021-04-20 17:24
Hmm, interesting. Well, I won't worry about it then. Thanks again for your efforts, we will be pushing things to `3.1` very soon!
