### ISSUE TITLE
[replication] Opensips 2.2 Crash

### ISSUE THREAD

**Issue by goup2010** [OpenSIPS/opensips#761] opened 2016-01-17 19:09 UTC
Opensips 2.2 crashed when make a call.
OS: CentOS release 5.11
Opensips ver: 2.2 (17.01.2016)

[gdb_log.txt](https://github.com/OpenSIPS/opensips/files/93564/gdb_log.txt)

**Comment by goup2010** [comment] 2016-01-19 21:32
After commit 8d23d9b (19.01.2015) Opensips 2.2 continue crashed.

**Comment by bogdan-iancu** [comment] 2016-01-20 12:15
@liviuchircu is already investigating this problem (reported via mailing list)

**Comment by goup2010** [comment] 2016-01-20 21:32
I try latest commit 02b4c25 (20.1.2016). Continue crashed.

**Comment by goup2010** [comment] 2016-01-22 08:54
I compile Opensips 2.2 with latest commit 9f68260 (21.1.2016). Crash again.

**Comment by goup2010** [comment] 2016-01-25 18:51
After latest commit eaef57e (25.1.2016) Opensips 2.2 continue crashed.

**Comment by bogdan-iancu** [comment] 2016-01-26 10:09
@goup2010 , as said, @liviuchircu  is working in fixing the issue you reported (according to the provided back trace).
It is completely useless to keep trying each revision if the log does not mention as being a fix for this ticket. 
Please be patient  and we will notify here when the fix will be available on GIT repo.
Thanks for understanding !!

**Comment by liviuchircu** [comment] 2016-01-26 17:12
I tried to reproduce the crash by setting `$DLG_timeout` on an initial INVITE, in a 2-node cluster, with dialog replication enabled. Seemed to work well, and I couldn't get it to crash, regardless of traffic volume.

Two questions:
* could you please provide a sample script, which causes the crash? If privacy is a concern, you may email it to liviu@opensips.org
* in `gdb`, could you provide the output of the following:
  * `frame 1` (the one under `replicate_dialog_updated`)
  * `print *dlg`

Many thanks!

**Comment by goup2010** [comment] 2016-01-27 20:05
I send bt full and frame logs to liviuchircu.

**Comment by liviuchircu** [comment] 2016-01-28 12:52
I thought it would crash in `replicate_dialog_updated()` since you seemed to be using dialog replication, right? That's exactly why I couldn't replicate it at all!

It turns out that the involved script wasn't making use of either `bin` listeners or the `clusterer` module at all, yet some dialog codepaths are still proceeding with some replication logic! Once I understood the usage case, I managed to have my local setup crash as well.

Thank you for all the help! Hope to close this asap now!

**Comment by liviuchircu** [comment] 2016-01-28 16:23
[A fix for this](4c60af868970) was pushed to `master` branch.

**Comment by liviuchircu** [comment] 2016-02-12 10:14
Closing. Please re-open if anything else related to this issue pops up.

**Closed by liviuchircu** 2016-02-12 10:14 UTC
Labels: bug, fixed
