### ISSUE TITLE
[BUG] Sql cacher module problem with reloads

### ISSUE THREAD

**Issue by baevga** [OpenSIPS/opensips#2832] opened 2022-05-12 19:26 UTC
Hello Opensips team,

We are expiricing some problems with sql_cacher module in both on demand and full caching.

When on demand mode selected and opensips pass traffic if sql_cached_value got null it will be cached for all period due to expires param.
So, if it didn't set in modparam then it store this value(NULL for example) for hour even if reload was sented to opensips throuth MI (sql_cacher_reload).
After exprires value  has been overcomed then reloads start to work.
When on demand mode selected and opensips pass traffic if sql_cached_value got null it will be cached for all period due to expires param.
So, if it didn't set in modparam then it store this value(NULL for example) for hour even if reload was sented to opensips throuth MI (sql_cacher_reload).
After exprire value  has been overcomed then reloads start to work.

When we use full caching mode(on_demand=0) opensips on start doesn't load any data in chache. It happens only if we send reload to opensips manually throuth MI (sql_cacher_reload) after load.

Thank you!

version: opensips 3.1.9 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT, ENCRYPT-CFG
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 64bed6332
main.c compiled on  with gcc 9

Ubuntu 20.04.4 LTS

**Comment by rvlad-patrascu** [comment] 2022-06-09 16:45
Hi @baevga,
 
I am not able to reproduce the issues you've described here.

In the on_demand case, how do you issue the MI reload command? Are you by any chance not providing as parameter the key that you want to reload? Because that would explain why you still get NULL even if the key now exists in SQL. The behavior in this case is to invalidate all keys in cache.

In the full caching case, I'm not sure I understand the behavior. Is there any data in the cache up to the point you trigger the reload? Do you mean that after triggering the reload you then get only NULL?

**Comment by baevga** [comment] 2022-06-09 22:42
Hello @rvlad-patrascu 

Thank you for reply!

"In the full caching case, I'm not sure I understand the behavior. Is there any data in the cache up to the point you trigger the reload? Do you mean that after triggering the reload you then get only NULL?"

No, I meant that we have declared modparam "sql_cacher", "cache_table"... to cachedb_local  in config in full cache mode and  we start opensips it doesn't load cache properly. We have to make request to MI with sql_cacher_reload <partition> for cache load. Only after this it getting full data set and start working

**Comment by rvlad-patrascu** [comment] 2022-06-10 20:31
Hi @baevga ,

So you are saying that in full caching mode, without doing a reload, opensips does not load any key from SQL into the cache? This should be straight forward to reproduce but I do not see such behavior in my tests so I'll need more information here. Can you post some debug logs from opensips startup?

And what about the on demand mode? Was it the way you were running the MI command or is it still an issue?

**Comment by rvlad-patrascu** [comment] 2022-07-21 18:09
@baevga, @nikbyte 

Can we close this issue? As discussed separately with @nikbyte this is not a bug but rather misusing the cachedb_local module with sql_cacher (by enabling replication and causing inconsistencies with the reload version integer in the cache).

To prevent this issue in the future I have added a check in sql_cacher that throws an error if a collection from the local cache is replicated (https://github.com/OpenSIPS/opensips/commit/1b9662649d2e0606225b5e198a083619d0ca97e1).

**Comment by nikbyte** [comment] 2022-07-22 08:54
Yes. I close. Thank  you.

**Closed by nikbyte** 2022-07-22 08:54 UTC
Labels: investigating
