### ISSUE TITLE
[BUG] FEATURE? cache_raw_query required 3 parameters

### ISSUE THREAD

**Issue by nick-brig** [OpenSIPS/opensips#2313] opened 2020-11-18 10:58 UTC
**OpenSIPS version you are running**
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8

**Describe the bug**
I use this or a some call
```
event_route[E_UL_CONTACT_UPDATE] {                                                                                                                                           
    cache_raw_query("redis:local", "publish sip_notification E_UL_CONTACT_UPDATE");
}                                                                                                                                                                            
```
But got this error:
```
Nov 18 12:55:30 [38994] Traceback (last included file at the bottom):
Nov 18 12:55:30 [38994]  0. /etc/opensips/opensips.cfg
Nov 18 12:55:30 [38994] CRITICAL:core:yyerror: parse error in /etc/opensips/opensips.cfg:956:24-25: too few parameters for command <cache_raw_query>

Nov 18 12:55:30 [38994] event_route[E_UL_CONTACT_UPDATE] {
Nov 18 12:55:30 [38994]         cache_raw_query("redis:local", "publish sip_notification E_UL_CONTACT_UPDATE");
Nov 18 12:55:30 [38994]         ^~
Nov 18 12:55:30 [38994] }
Nov 18 12:55:30 [38994] 
Nov 18 12:55:30 [38994] ERROR:core:parse_opensips_cfg: bad config file (1 errors)
Nov 18 12:55:30 [38994] ERROR:core:main: failed to parse config file (null)
```

**Comment by liviuchircu** [comment] 2020-11-18 11:08
Duplicate of #2198.  Please grab the latest `3.1.1` packages, released just yesterday -- the issue is solved there.

**Closed by liviuchircu** 2020-11-18 11:08 UTC
Labels: duplicate
