### ISSUE TITLE
opensips-2.2-beta: module rest_client fails after first function call

### ISSUE THREAD

**Issue by krys1976** [OpenSIPS/opensips#846] opened 2016-04-01 13:53 UTC
Second execution of rest_post fails with 

kernel: traps: opensips[12008] general protection ip:4aeffb sp:7fffa8722a60 error:0 in opensips[400000+17e000]

**Comment by bogdan-iancu** [comment] 2016-04-01 15:01
Hi @krys1976 , try to get a backtrace . To get the core file, see:
     http://www.opensips.org/Documentation/TroubleShooting-Crash

**Comment by krys1976** [comment] 2016-04-01 15:38
[root@sip01-dev-vsc /]# gdb opensips core.16607
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/opensips...Reading symbols from /usr/lib/debug/usr/sbin/opensips.debug...done.
done.
[New LWP 16607]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libmysqlclient.so.18
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/df/ef2833c397fd7ebea0ba670b3d5b07776a26e7.debug
Core was generated by `opensips -P /var/run/opensips.pid -f /etc/opensips/opensips.cfg -m 32 -M 2048'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004aeffb in fm_remove_free (n=0x7fd704f3b390, qm=0x7fd70447f010) at mem/f_malloc.c:187
187		*pf=n->u.nxt_free;
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 cyrus-sasl-lib-2.1.26-20.el7_2.x86_64 elfutils-libelf-0.163-3.el7.x86_64 elfutils-libs-0.163-3.el7.x86_64 glibc-2.17-106.el7_2.4.x86_64 json-c-0.11-4.el7_0.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.13.2-12.el7_2.x86_64 libacl-2.2.51-12.el7.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-8.el7.x86_64 libcom_err-1.42.9-7.el7.x86_64 libdb-5.3.21-19.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libidn-1.28-4.el7.x86_64 libselinux-2.2.2-6.el7.x86_64 libssh2-1.4.3-10.el7_2.1.x86_64 libstdc++-4.8.5-4.el7.x86_64 libxml2-2.9.1-6.el7_2.2.x86_64 lm_sensors-libs-3.3.4-11.el7.x86_64 lua-5.1.4-14.el7.x86_64 net-snmp-agent-libs-5.7.2-24.el7.x86_64 net-snmp-libs-5.7.2-24.el7.x86_64 nspr-4.10.8-2.el7_1.x86_64 nss-3.19.1-19.el7_2.x86_64 nss-softokn-3.16.2.3-13.el7_1.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 nss-sysinit-3.19.1-19.el7_2.x86_64 nss-util-3.19.1-9.el7_2.x86_64 openldap-2.4.40-9.el7_2.x86_64 pcre-8.32-15.el7.x86_64 perl-5.16.3-286.el7.x86_64 perl-Class-Load-XS-0.06-3.el7.x86_64 perl-Compress-Raw-Zlib-2.061-4.el7.x86_64 perl-DBI-1.627-4.el7.x86_64 perl-DateTime-1.04-5.el7.x86_64 perl-List-MoreUtils-0.33-9.el7.x86_64 perl-Params-Util-1.07-6.el7.x86_64 perl-Params-Validate-1.08-4.el7.x86_64 perl-PathTools-3.40-5.el7.x86_64 perl-Scalar-List-Utils-1.27-248.el7.x86_64 perl-Socket-2.010-3.el7.x86_64 perl-Storable-2.45-3.el7.x86_64 perl-libs-5.16.3-286.el7.x86_64 popt-1.13-16.el7.x86_64 rpm-libs-4.11.3-17.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 systemd-libs-219-19.el7_2.7.x86_64 tcp_wrappers-libs-7.6-77.el7.x86_64 xz-libs-5.1.2-12alpha.el7.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb)

**Comment by krys1976** [comment] 2016-04-01 16:05
[bt_16346.txt](https://github.com/OpenSIPS/opensips/files/199933/bt_16346.txt)

**Comment by bogdan-iancu** [comment] 2016-04-04 15:44
@krys1976, you say the first curl query is ok, while the second one is the one crashing all the time, right ?

Also, are you sure the information you posted here about the crash is consistent?  your second post shows in the GDB listing a crash is fm_remove_free(), while in the attached backtrace the crash is somewhere deep in the curl library.

**Comment by krys1976** [comment] 2016-04-04 16:48
@bogdan-iancu ... under more investigation we found out, that it crashes only when the second function call is simultaenously to the first, in meaning of the first isn't fulfilled completly, but the second is already started.

**Comment by bogdan-iancu** [comment] 2016-04-04 16:53
OK, there is an overlapping between the first and the second query - can you tell if both are handled by the same process or are they in different opensips processes ?

**Comment by krys1976** [comment] 2016-04-05 09:58
When it's executed on same PID the behavior of 2.1.2 is it does, when different PIDs it crashes. On 2.2.0-beta I wasn't able to get the command running at same PID.

**Comment by bogdan-iancu** [comment] 2016-05-23 10:41
Hi @krys1976, @liviuchircu run several tests with rest_client and async support (including memory debugging support) and everything seems to be working fine.
I would say the problems are strongly depending of your particular setup - what OS and version are you using ? what;s the rest query you are running ? I'm looking to any information that might help us in reproducing your setup.

**Comment by liviuchircu** [comment] 2017-04-26 08:07
Fixed by ed8984c.

**Closed by liviuchircu** 2017-04-26 08:07 UTC
Labels: bug, low-priority, works for me
