### ISSUE TITLE
[BUG] Error when setting a non-existing "next index" for an AVP

### ISSUE THREAD

**Issue by wenyuanZZ** [OpenSIPS/opensips#2585] opened 2021-07-27 02:30 UTC
https://www.opensips.org/Documentation/Script-CoreVar-3-1

**Comment by wenyuanZZ** [comment] 2021-07-27 02:33
> https://www.opensips.org/Documentation/Script-CoreVar-3-1

In this url,it says:
...
#overwrite the value at a certain index
$(avp(17)[0]) = "zero";
...
Then I use it likely in opensips.cfg:
.....
$(avp(271)[0]) = $avp(55);
.....
But,it get an error in opensips 3.1.3,the log says:
Jul 27 10:32:26 vmeet-flexisip-dev-10-101-29-1 opensips[4812]: ERROR:core:pv_set_avp: Failed to replace avp
Jul 27 10:32:26 vmeet-flexisip-dev-10-101-29-1 opensips[4812]: ERROR:core:do_assign: setting PV failed
Jul 27 10:32:26 vmeet-flexisip-dev-10-101-29-1 opensips[4812]: ERROR:core:do_assign: error at /opt/opensips-3.1.3/etc/opensips/opensips.cfg:748
How to solve it,ths.

**Comment by liviuchircu** [comment] 2021-07-27 09:22
Hi, is this a syntax error or runtime error?  Your opensips starts, yes?

**Comment by wenyuanZZ** [comment] 2021-07-27 09:45
> Hi, is this a syntax error or runtime error? Your opensips starts, yes?

when sip message come in, it will say this error.My opensips is running.

**Comment by liviuchircu** [comment] 2021-07-27 13:11
Are there any other errors above the ERRORS you posted?  For example, maybe you are running out of shared memory during some `sipp` stress test, so the error is natural (since it has no more memory to set the AVP).

Your AVP syntax looks OK and there should be no errors under normal operation.

**Comment by wenyuanZZ** [comment] 2021-07-28 02:27
> or example, maybe you are running out of shared memory during some

There is not any other error, the cps is very low.

**Comment by liviuchircu** [comment] 2021-07-28 05:48
@wenyuanZZ, I managed to reproduce this as well.  I agree the error is annoying, and the code should simply work, given that index "0" is the same as "no index".  Basically, the error should not be printed if the index is either 0 (for a non-existing AVP) or equal to the AVP size, in which case the value should be appended to the AVP.

Expect the fix to come pretty soon.  Will keep you posted.

**Comment by liviuchircu** [comment] 2021-07-28 05:54
Until the fix is ready, you can use the following technique (hopefully you don't need to rewrite a big part of your script):

```
    if ($avp(271) != NULL)
        $(avp(271)[0]) = $avp(55);
    else
        $avp(271) = $avp(55);
```

**Comment by wenyuanZZ** [comment] 2021-07-28 06:06
> Until the fix is ready, you can use the following technique (hopefully you don't need to rewrite a big part of your script):
> 
> ```
>     if ($avp(271) != NULL)
>         $(avp(271)[0]) = $avp(55);
>     else
>         $avp(271) = $avp(55);
> ```

ths,liv. you are great.

**Comment by liviuchircu** [comment] 2021-08-17 14:15
Hi, @wenyuanZZ!

I have reconsidered this bug report and I no longer consider there is anything to fix here.  Here are some explanations:

* AVPs behave as stacks (always append to index `0`), so your operation can be simply written as: `$avp(17) = "test";`!  It will always append to index 0 (_push one more value_; _push one more value_; etc.), and the array will keep growing every time you run this code.
* to append to **last index**, there is the `$(avp(17)[append]) = "test";` syntax
* to reset all values of an AVP, use: `$avp(17) := NULL;`
* to reset all values of an AVP and store 1 value, use: `$avp(17) := "test";`
* it is **normal** for OpenSIPS to print out an error if you incorrectly access a non-existing index, like `$(avp(17)[0])` for non-existing `$avp(17)`.  Making exceptions for index `0` and `last` would only complicate matters while adding zero value...

So you should have all resources you need in order to write your `opensips.cfg` logic (if not, just open up a feature request and I'll take a look!).  Closing here.

**Closed by liviuchircu** 2021-08-17 14:15 UTC
Labels: wontfix, script bug

**Comment by wenyuanZZ** [comment] 2021-09-26 09:57
In opensips 1.11.3, avp is used as arrays. In opensips 3.1.3 is used as a stack?

**Comment by wenyuanZZ** [comment] 2021-09-26 09:58
# if the dispatcher list (in 271) does not start with
# the request domain/port that we are sending this call
# to, re-order the list so that it does
if($avp(55) && $(avp(271)[0]) != $avp(55)) {
	# create a index var for our loop (arrays are start at 0 and this is a count)
	$var(i) = $avp(274) - 1;

	# loop over the dispatcher list
	while($var(i) > 0) {
		# if this element in the dispatch list is the same
		# as the call destination
		if($(avp(271)[$var(i)]) == $avp(55)) {
			# replace it with the first element of the list
			$(avp(271)[$(var(i))]) = $(avp(271)[0]);
			####3.1.3#if($avp(271) != NULL)
			####3.1.3#      $(avp(271)[$(var(i))]) = $(avp(271)[0]);

			# break out of the loop
			$var(i) = -1;
		}

		$var(i) = $var(i) - 1;
	}

	# handles the case were we only have two servers
	# and the one that we are locked to has failed
	if ($var(i) >= 0) {
		xlog("L_INFO", "$ci|log|associated media server is inactive, moving to $rd");

		if ($ct.fields(uri) && cache_fetch("local", "$ci", $avp(56))) {
			cache_store("local", "$(ct.fields(uri){uri.user})", "sip:$rd:$rp", 3600);

			xlog("L_INFO", "$ci|log|associated contact $(ct.fields(uri){uri.user}) with media server sip:$rd:$rp");
		}

		# update the callid cache
		cache_store("local", "$ci", "sip:$rd:$rp", 3600);
	}
	# the server we are locked to is in the active server list from then
	# dispatcher so re-arrange the list to try it first
	else
	{
		xlog("L_INFO", "$ci|log|re-ordering the dispatcher list to keep associated server first");

		# set the first element of the list to the destination
		$(avp(271)[0]) = $avp(55);
		####3.1.3#if($avp(271) != NULL)
		####3.1.3#      $(avp(271)[0]) = $avp(55);
		####3.1.3#else
		####3.1.3#      $avp(271) = $avp(55);

		# set the domain for this request (server IP to route to)
		$rd = $(avp(55){uri.host});

		# set the port for this request (server IP to route to)
		$rp = $(avp(55){uri.port});
	}
}

**Comment by wenyuanZZ** [comment] 2021-09-26 09:59
######################################################################
## Dispatcher Module Parameters
######################################################################
#modparam("dispatcher", "list_file", "/etc/opensips/dispatcher.list")
modparam("dispatcher", "db_url", "mysql://")
#modparam("dispatcher", "flags", 2)
#modparam("dispatcher", "use_default", 0)
#modparam("dispatcher", "force_dst", 1)
modparam("dispatcher", "dst_avp", "$avp(271)")
modparam("dispatcher", "attrs_avp", "$avp(272)")
modparam("dispatcher", "grp_avp", "$avp(273)")
modparam("dispatcher", "cnt_avp", "$avp(274)")
modparam("dispatcher", "hash_pvar", "$avp(273)")
modparam("dispatcher", "ds_ping_method", "OPTIONS")
modparam("dispatcher", "ds_ping_from", "sip:sipcheck@10.101.29.1:5049")
modparam("dispatcher", "ds_ping_interval", 10)
modparam("dispatcher", "ds_probing_threshhold", 3)
modparam("dispatcher", "ds_probing_mode", 1)
modparam("dispatcher", "options_reply_codes", "501,403,404,400,200")

**Comment by wenyuanZZ** [comment] 2021-09-26 10:00
If I used ####3.1.3# part,it is no error in cfg,but, the loadbalance will fail,. I have 5 freeswitchs, it is allways run to a freeswitch.

**Comment by wenyuanZZ** [comment] 2021-09-26 10:02
If I dont use part of ####3.1.3#,it will say error in opensips 3.1.3,the log says:
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:pv_set_avp: Failed to replace avp, 18, 4, (null), -1937799632, 24, 0
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:do_assign: setting PV failed
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:do_assign: error at /opt/opensips-3.1.3/etc/opensips/opensips.cfg:805
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:parse_uri: bad port in uri (error at char
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:tr_eval_uri: invalid uri [sip:10.107.21.102:<null>]
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:pv_set_ruri_host: bad parameters
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:do_assign: setting PV failed
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:do_assign: error at /opt/opensips-3.1.3/etc/opensips/opensips.cfg:812
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:parse_uri: bad port in uri (error at char
Sep 26 16:39:55 ms-cooperation-prd-10-107-21-48 opensips[14774]: ERROR:core:tr_eval_uri: invalid uri [sip:10.107.21.102:<null>]

it is run ok in opensips 1.11.3

**Comment by wenyuanZZ** [comment] 2021-09-26 10:03
How should I fix my route?liv

**Comment by wenyuanZZ** [comment] 2021-09-26 10:03
@liviuchircu

**Comment by volga629-1** [comment] 2024-01-18 17:07
That issue still happing in 3.4 

Code example 


```
		if(ds_count($(avp(dsp_group){s.int}), "a", $avp(result))) {
		xlog("[DISPATCH_ALGO] [$rm] [$cfg_line]  $ci dst dispatcher count $avp(result) \n");
			$var(idx) = 0;
			while($var(idx) < $avp(result)) {
				if ($avp(dst)!=null) {
					$(avp(dst)[$var(idx)]) = $var(dst);
				} else {
					$avp(dst) = $var(dst);
				}
				xlog("[DISPATCH_ALGO] [$rm] [$cfg_line] $ci index $$var(idx) | $var(idx) param $param(dst_uri)  destination avp $$(avp(dst)[$var(idx)]) |  $(avp(dst)[$var(idx)])\n");
			$var(idx) = $var(idx) + 1;
			}
}
```

Log 


```

8 10:45:05 sbc01 /usr/sbin/opensips[1029203]: ERROR:core:pv_set_avp: Failed to replace avp
Jan 18 10:45:05 /usr/sbin/opensips[1029203]: ERROR:core:do_assign: setting PV failed
Jan 18 10:45:05 /usr/sbin/opensips[1029203]: ERROR:core:do_assign: error at /etc/opensips/opensips.cfg:1568


```
