### ISSUE TITLE
memory leak in HEP processing

### ISSUE THREAD

**Issue by rrevels** [OpenSIPS/opensips#1085] opened 2017-03-28 14:43 UTC
I am using the precompiled rpm for this task so have limited debug info available at the moment but will work on getting more if it turns out this is not easily found or already resolved in source.

Here is the rpm info and the log output from the memory dump on a single HEP thread.  The only traffic on this proxy is HEP packets from a remote captagent that I am using to import pcaps into a database.  Package memory runs out pretty quick.

I found a commit from september of last year that seems to describe a fix for something like I am seeing but it seems like that should have made it to this package by now.  Here is the link to that commit https://github.com/OpenSIPS/opensips/commit/63b2a52c2c2d453ccf889cc5e74991a2c81aaccd

And here is the memory stats I have collected so far:

* Wed Jan 20 2016 Nick Altmann <nick.altmann@gmail.com> - 2.2.0-1
- Specification updated for opensips 2.2
- New packages: db_sqlite, clusterer, event_flatstore,
  event_virtual, proto_bin, proto_hep, proto_wss, sql_cacher
- Renamed packages: mysql -> db_mysql, postgres -> db_postgres,
  cpl-c -> cpl_c

2017-03-28T13:37:29.640986+00:00 proxy-test-1 /sbin/opensips[13398]: Memory status (pkg):
2017-03-28T13:37:29.641058+00:00 proxy-test-1 /sbin/opensips[13398]: fm_status (0x7f51ebedb010):
2017-03-28T13:37:29.641071+00:00 proxy-test-1 /sbin/opensips[13398]:  heap size= 67108864
2017-03-28T13:37:29.641078+00:00 proxy-test-1 /sbin/opensips[13398]:  used= 4980072, used+overhead=5850736, free=62128792
2017-03-28T13:37:29.641089+00:00 proxy-test-1 /sbin/opensips[13398]:  max used (+overhead)= 5850736
2017-03-28T13:37:29.641094+00:00 proxy-test-1 /sbin/opensips[13398]: dumping free list:
2017-03-28T13:37:29.641117+00:00 proxy-test-1 /sbin/opensips[13398]: hash = 2060 fragments no.:     1, unused:     0#012#011#011 bucket size:  33554432 -  67108864 (first  61258128)
2017-03-28T13:37:29.641127+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL:      1 free fragments = 61258128 free bytes
2017-03-28T13:37:29.641145+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 61258128 large bytes
2017-03-28T13:37:29.641156+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 24 overhead
2017-03-28T13:37:29.641161+00:00 proxy-test-1 /sbin/opensips[13398]: -----------------------------

2017-03-28T13:47:56.371280+00:00 proxy-test-1 /sbin/opensips[13398]: Memory status (pkg):
2017-03-28T13:47:56.371306+00:00 proxy-test-1 /sbin/opensips[13398]: fm_status (0x7f51ebedb010):
2017-03-28T13:47:56.371323+00:00 proxy-test-1 /sbin/opensips[13398]:  heap size= 67108864
2017-03-28T13:47:56.371330+00:00 proxy-test-1 /sbin/opensips[13398]:  used= 28112568, used+overhead=32744080, free=38996296
2017-03-28T13:47:56.371336+00:00 proxy-test-1 /sbin/opensips[13398]:  max used (+overhead)= 32745976
2017-03-28T13:47:56.371341+00:00 proxy-test-1 /sbin/opensips[13398]: dumping free list:
2017-03-28T13:47:56.371356+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   1 fragments no.:     2, unused:     0#012#011#011 bucket size:         8 -         8 (first         8)
2017-03-28T13:47:56.371363+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   2 fragments no.:     2, unused:     0#012#011#011 bucket size:        16 -        16 (first        16)
2017-03-28T13:47:56.371369+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   3 fragments no.:     2, unused:     0#012#011#011 bucket size:        24 -        24 (first        24)
2017-03-28T13:47:56.371376+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   6 fragments no.:     1, unused:     0#012#011#011 bucket size:        48 -        48 (first        48)
2017-03-28T13:47:56.371382+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   7 fragments no.:     1, unused:     0#012#011#011 bucket size:        56 -        56 (first        56)
2017-03-28T13:47:56.371389+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   8 fragments no.:     2, unused:     0#012#011#011 bucket size:        64 -        64 (first        64)
2017-03-28T13:47:56.371396+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   9 fragments no.:     8, unused:     0#012#011#011 bucket size:        72 -        72 (first        72)
2017-03-28T13:47:56.371408+00:00 proxy-test-1 /sbin/opensips[13398]: hash =  30 fragments no.:     1, unused:     0#012#011#011 bucket size:       240 -       240 (first       240)
2017-03-28T13:47:56.371416+00:00 proxy-test-1 /sbin/opensips[13398]: hash =  97 fragments no.:     1, unused:     0#012#011#011 bucket size:       776 -       776 (first       776)
2017-03-28T13:47:56.371446+00:00 proxy-test-1 /sbin/opensips[13398]: hash = 2060 fragments no.:     1, unused:     0#012#011#011 bucket size:  33554432 -  67108864 (first  34362864)
2017-03-28T13:47:56.371458+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL:     21 free fragments = 34364784 free bytes
2017-03-28T13:47:56.371466+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 34362864 large bytes
2017-03-28T13:47:56.371472+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 24 overhead
2017-03-28T13:47:56.371482+00:00 proxy-test-1 /sbin/opensips[13398]: -----------------------------

2017-03-28T13:59:41.303640+00:00 proxy-test-1 /sbin/opensips[13398]: Memory status (pkg):
2017-03-28T13:59:41.303689+00:00 proxy-test-1 /sbin/opensips[13398]: fm_status (0x7f51ebedb010):
2017-03-28T13:59:41.303708+00:00 proxy-test-1 /sbin/opensips[13398]:  heap size= 67108864
2017-03-28T13:59:41.303716+00:00 proxy-test-1 /sbin/opensips[13398]:  used= 28112568, used+overhead=32744080, free=38996296
2017-03-28T13:59:41.303721+00:00 proxy-test-1 /sbin/opensips[13398]:  max used (+overhead)= 32745976
2017-03-28T13:59:41.303734+00:00 proxy-test-1 /sbin/opensips[13398]: dumping free list:
2017-03-28T13:59:41.303748+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   1 fragments no.:     2, unused:     0#012#011#011 bucket size:         8 -         8 (first         8)
2017-03-28T13:59:41.303761+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   2 fragments no.:     2, unused:     0#012#011#011 bucket size:        16 -        16 (first        16)
2017-03-28T13:59:41.303768+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   3 fragments no.:     2, unused:     0#012#011#011 bucket size:        24 -        24 (first        24)
2017-03-28T13:59:41.303774+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   6 fragments no.:     1, unused:     0#012#011#011 bucket size:        48 -        48 (first        48)
2017-03-28T13:59:41.303779+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   7 fragments no.:     1, unused:     0#012#011#011 bucket size:        56 -        56 (first        56)
2017-03-28T13:59:41.303785+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   8 fragments no.:     2, unused:     0#012#011#011 bucket size:        64 -        64 (first        64)
2017-03-28T13:59:41.303796+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   9 fragments no.:     8, unused:     0#012#011#011 bucket size:        72 -        72 (first        72)
2017-03-28T13:59:41.303812+00:00 proxy-test-1 /sbin/opensips[13398]: hash =  30 fragments no.:     1, unused:     0#012#011#011 bucket size:       240 -       240 (first       240)
2017-03-28T13:59:41.303837+00:00 proxy-test-1 /sbin/opensips[13398]: hash =  97 fragments no.:     1, unused:     0#012#011#011 bucket size:       776 -       776 (first       776)
2017-03-28T13:59:41.303877+00:00 proxy-test-1 /sbin/opensips[13398]: hash = 2060 fragments no.:     1, unused:     0#012#011#011 bucket size:  33554432 -  67108864 (first  34362864)
2017-03-28T13:59:41.303882+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL:     21 free fragments = 34364784 free bytes
2017-03-28T13:59:41.303888+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 34362864 large bytes
2017-03-28T13:59:41.303901+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 24 overhead

2017-03-28T14:09:10.618472+00:00 proxy-test-1 /sbin/opensips[13398]: Memory status (pkg):
2017-03-28T14:09:10.618519+00:00 proxy-test-1 /sbin/opensips[13398]: fm_status (0x7f51ebedb010):
2017-03-28T14:09:10.618536+00:00 proxy-test-1 /sbin/opensips[13398]:  heap size= 67108864
2017-03-28T14:09:10.618542+00:00 proxy-test-1 /sbin/opensips[13398]:  used= 43182664, used+overhead=50272400, free=23926200
2017-03-28T14:09:10.618547+00:00 proxy-test-1 /sbin/opensips[13398]:  max used (+overhead)= 50272400
2017-03-28T14:09:10.618552+00:00 proxy-test-1 /sbin/opensips[13398]: dumping free list:
2017-03-28T14:09:10.618572+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   1 fragments no.:     2, unused:     0#012#011#011 bucket size:         8 -         8 (first         8)
2017-03-28T14:09:10.618668+00:00 proxy-test-1 /sbin/opensips[13398]: hash = 2059 fragments no.:     1, unused:     0#012#011#011 bucket size:  16777216 -  33554432 (first  16836448)
2017-03-28T14:09:10.618684+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL:      3 free fragments = 16836464 free bytes
2017-03-28T14:09:10.618696+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 16836448 large bytes
2017-03-28T14:09:10.618708+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 24 overhead

2017-03-28T14:14:58.132285+00:00 proxy-test-1 /sbin/opensips[13398]: Memory status (pkg):
2017-03-28T14:14:58.132331+00:00 proxy-test-1 /sbin/opensips[13398]: fm_status (0x7f51ebedb010):
2017-03-28T14:14:58.132346+00:00 proxy-test-1 /sbin/opensips[13398]:  heap size= 67108864
2017-03-28T14:14:58.132352+00:00 proxy-test-1 /sbin/opensips[13398]:  used= 43182664, used+overhead=50272424, free=23926200
2017-03-28T14:14:58.132358+00:00 proxy-test-1 /sbin/opensips[13398]:  max used (+overhead)= 50272440
2017-03-28T14:14:58.132368+00:00 proxy-test-1 /sbin/opensips[13398]: dumping free list:
2017-03-28T14:14:58.132382+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   1 fragments no.:     2, unused:     0#012#011#011 bucket size:         8 -         8 (first         8)
2017-03-28T14:14:58.132402+00:00 proxy-test-1 /sbin/opensips[13398]: hash =   2 fragments no.:     1, unused:     0#012#011#011 bucket size:        16 -        16 (first        16)
2017-03-28T14:14:58.132449+00:00 proxy-test-1 /sbin/opensips[13398]: hash = 2059 fragments no.:     1, unused:     0#012#011#011 bucket size:  16777216 -  33554432 (first  16836408)
2017-03-28T14:14:58.132456+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL:      4 free fragments = 16836440 free bytes
2017-03-28T14:14:58.132461+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 16836408 large bytes
2017-03-28T14:14:58.132472+00:00 proxy-test-1 /sbin/opensips[13398]: TOTAL: 24 overhead

**Comment by ionutrazvanionita** [comment] 2017-03-28 15:37
If I understood correctly you're using siptrace? What exactly are you tracing? Dialogs, transactions?

**Comment by rrevels** [comment] 2017-03-28 15:54
No, its's sipcapture.  I have hep configured to skip the config file routes
and go right to db store.  The only network traffic hitting the server is
hep packets from another server running captagent.

**Comment by ionutrazvanionita** [comment] 2017-03-29 14:46
Based on what you're saying which seems to be totally true I made a very small patch which should fix your problem. Can you test it and report if the problem is solved?
[sipcapture_leak.fix.patch.txt](https://github.com/OpenSIPS/opensips/files/879432/sipcapture_leak.fix.patch.txt)

**Comment by rrevels** [comment] 2017-03-29 20:59
That does indeed seem to have taken care of that one.  It appears there is still an issue and this time it's being somewhat more elusive.  I have run out of time to work with it today but will take it up again in the morning.  On my last run it does look like the issue could be in calls to context_alloc not being freed.  Here is the output from the filter I do on my memory logs:

cat /var/log/opensips.msg | grep "pkg_malloc.*called from\|shm_malloc.*called from\|freeing frag.*alloc'ed from" | sed "s/^.* \(.* from\)\(.*\)/\1\2/g" | sort -k3 | uniq -c 
     41 alloc'ed from cachedb/cachedb_pool.c: filter_pool_by_scheme(58)
     41 called from cachedb/cachedb_pool.c: filter_pool_by_scheme(58)
  40134 called from context.c: context_alloc(127)
     41 alloc'ed from data_lump.c: del_lump(352)
     41 called from data_lump.c: del_lump(352)
     41 alloc'ed from dispatch.c: ds_check_timer(2297)
     41 called from dispatch.c: ds_check_timer(2297)
     41 alloc'ed from dlg.c: _internal_new_dlg_uac(150)
     41 called from dlg.c: _internal_new_dlg_uac(150)
  40116 alloc'ed from hep.c: unpack_hepv3(741)
  40134 called from hep.c: unpack_hepv3(741)
  40116 alloc'ed from hep.c: unpack_hepv3(752)
  40134 called from hep.c: unpack_hepv3(752)
     41 alloc'ed from h_table.c: build_cell(268)
     41 called from h_table.c: build_cell(268)
     81 alloc'ed from mi/attr.c: add_mi_attr(76)
     81 called from mi/attr.c: add_mi_attr(76)
     27 alloc'ed from mi/tree.c: create_mi_node(137)
     27 called from mi/tree.c: create_mi_node(137)
      1 alloc'ed from mi/tree.c: init_mi_tree(51)
      1 called from mi/tree.c: init_mi_tree(51)
     41 alloc'ed from msg_translator.c: via_builder(2073)
     41 called from msg_translator.c: via_builder(2073)
  19739 alloc'ed from parser/contact/contact.c: parse_contacts(190)
  19739 called from parser/contact/contact.c: parse_contacts(190)
  18663 alloc'ed from parser/contact/parse_contact.c: parse_contact(79)
  18663 called from parser/contact/parse_contact.c: parse_contact(79)
      4 alloc'ed from parser/digest/digest.c: new_credentials(38)
      4 called from parser/digest/digest.c: new_credentials(38)
  74652 alloc'ed from parser/msg_parser.c: get_hdr_field(110)
  74775 called from parser/msg_parser.c: get_hdr_field(110)
  40157 alloc'ed from parser/msg_parser.c: get_hdr_field(132)
  40175 called from parser/msg_parser.c: get_hdr_field(132)
  40157 alloc'ed from parser/msg_parser.c: get_hdr_field(156)
  40175 called from parser/msg_parser.c: get_hdr_field(156)
 527885 alloc'ed from parser/msg_parser.c: parse_headers(313)
 528389 called from parser/msg_parser.c: parse_headers(313)
     41 alloc'ed from parser/msg_parser.c: set_dst_uri(772)
     41 called from parser/msg_parser.c: set_dst_uri(772)
  40116 alloc'ed from parser/parse_from.c: parse_from_header(61)
  40116 called from parser/parse_from.c: parse_from_header(61)
   3139 alloc'ed from parser/parse_pai.c: parse_pai_header(58)
   3139 called from parser/parse_pai.c: parse_pai_header(58)
   2522 alloc'ed from parser/parse_param.c: parse_params(370)
   2522 called from parser/parse_param.c: parse_params(370)
  69705 alloc'ed from parser/parse_to.c: parse_to_param(278)
  69723 called from parser/parse_to.c: parse_to_param(278)
  79388 alloc'ed from parser/parse_via.c: parse_via(2112)
  79529 called from parser/parse_via.c: parse_via(2112)
    188 alloc'ed from parser/parse_via.c: parse_via(2275)
    188 called from parser/parse_via.c: parse_via(2275)
  40116 alloc'ed from proto_hep.c: hep_udp_read_req(1221)
  40134 called from proto_hep.c: hep_udp_read_req(1221)
     41 alloc'ed from proxy.c: hostent_cpy(102)
     41 called from proxy.c: hostent_cpy(102)
     41 alloc'ed from proxy.c: hostent_cpy(113)
     41 called from proxy.c: hostent_cpy(113)
     41 alloc'ed from proxy.c: hostent_cpy(136)
     41 called from proxy.c: hostent_cpy(136)
     41 alloc'ed from proxy.c: hostent_cpy(146)
     41 called from proxy.c: hostent_cpy(146)
     41 alloc'ed from proxy.c: hostent_shm_cpy(66)
     41 called from proxy.c: hostent_shm_cpy(66)
     41 alloc'ed from proxy.c: mk_proxy(202)
     41 called from proxy.c: mk_proxy(202)
     41 alloc'ed from ../../resolve.h: shm_clone_proxy(373)
     41 called from ../../resolve.h: shm_clone_proxy(373)
     41 alloc'ed from sip_msg.c: sip_msg_cloner(1012)
     41 called from sip_msg.c: sip_msg_cloner(1012)
     41 alloc'ed from sip_msg.c: sip_msg_cloner(1020)
     41 called from sip_msg.c: sip_msg_cloner(1020)
     41 alloc'ed from sip_msg.c: sip_msg_cloner(534)
     41 called from sip_msg.c: sip_msg_cloner(534)
     41 alloc'ed from t_hooks.c: insert_tmcb(92)
     41 called from t_hooks.c: insert_tmcb(92)
     41 alloc'ed from t_msgbuilder.c: build_uac_req(841)
     41 called from t_msgbuilder.c: build_uac_req(841)
    164 alloc'ed from ../../ut.h: shm_str_dup(569)
    164 called from ../../ut.h: shm_str_dup(569)

**Comment by ionutrazvanionita** [comment] 2017-03-30 16:41
Here i s another patch which should help with debugging. This patch prints the file and function from where context_alloc is called, because I'm in doubt whether the function is called from receive.c or proto_hep. 
[context.patch.txt](https://github.com/OpenSIPS/opensips/files/883137/context.patch.txt)

**Comment by rrevels** [comment] 2017-03-30 17:13
Perfect timing.  I was just looking at hep_handle_req in proto_hep.c which
both allocates shared memory for hep_ctx and calls context_alloc to get
memory pointed to by ctx.  I see where hep_ctx is freed but haven't found
ctx free yet.  I'll put the patch in and report back.

Thank you!

**Comment by rrevels** [comment] 2017-03-30 18:58
Sorry for the delay.  Here is some output from from my first test.

2017-03-30T18:50:08.833666+00:00 proxy-internal-1 /sbin/opensips[28651]:
pkg_malloc (84), called from context.c: context_alloc_f(131)
2017-03-30T18:50:08.843827+00:00 proxy-internal-1 /sbin/opensips[28652]:
INFO:core:context_alloc_f: Context alloc called from file proto_hep.c and
func hep_udp_read_req
2017-03-30T18:50:08.843832+00:00 proxy-internal-1 /sbin/opensips[28652]:
pkg_malloc (84), called from context.c: context_alloc_f(131)
2017-03-30T18:50:08.854029+00:00 proxy-internal-1 /sbin/opensips[28654]:
INFO:core:context_alloc_f: Context alloc called from file proto_hep.c and
func hep_udp_read_req
2017-03-30T18:50:08.854034+00:00 proxy-internal-1 /sbin/opensips[28654]:
pkg_malloc (84), called from context.c: context_alloc_f(131)
2017-03-30T18:50:08.864284+00:00 proxy-internal-1 /sbin/opensips[28651]:
INFO:core:context_alloc_f: Context alloc called from file proto_hep.c and
func hep_udp_read_req
2017-03-30T18:50:08.864289+00:00 proxy-internal-1 /sbin/opensips[28651]:
pkg_malloc (84), called from context.c: context_alloc_f(131)
2017-03-30T18:50:08.874541+00:00 proxy-internal-1 /sbin/opensips[28652]:
INFO:core:context_alloc_f: Context alloc called from file proto_hep.c and
func hep_udp_read_req
2017-03-30T18:50:08.874546+00:00 proxy-internal-1 /sbin/opensips[28652]:
pkg_malloc (84), called from context.c: context_alloc_f(131)
2017-03-30T18:50:08.884666+00:00 proxy-internal-1 /sbin/opensips[28654]:
INFO:core:context_alloc_f: Context alloc called from file proto_hep.c and
func hep_udp_read_req
2017-03-30T18:50:08.884672+00:00 proxy-internal-1 /sbin/opensips[28654]:
pkg_malloc (84), called from context.c: context_alloc_f(131)

**Comment by ionutrazvanionita** [comment] 2017-03-31 10:36
Thank you. This should fix the leak. Can you please test it?
[ctx_free_fix.patch.txt](https://github.com/OpenSIPS/opensips/files/885282/ctx_free_fix.patch.txt)

**Comment by rrevels** [comment] 2017-03-31 14:25
Oh yeah.  This is sooo much better.  It looks like there is still a small
leak hanging out somewhere so I'll leave memory debug on while I do a large
run of pcaps through this thing today and let you know if anything jumps
out at me but this is good enough to get through that large run.  Thank you!

2017-03-31T13:57:35.811253+00:00 proxy-internal-1 /sbin/opensips[16912]:
 used= 1009904, used+overhead=1987144, free=65121720
2017-03-31T13:58:53.783680+00:00 proxy-internal-1 /sbin/opensips[16912]:
 used= 1010352, used+overhead=1987976, free=65120888
2017-03-31T14:01:36.935331+00:00 proxy-internal-1 /sbin/opensips[16912]:
 used= 1021976, used+overhead=2010832, free=65098032

<==  Stopped sending new packets here.  Number of packets processed 39955.
 approx number of bytes left behind (didnt get first reading until after I
had started sending for some reason) is (1022064 - 1009904 = 12160) / 39955
packets = .3 bytes per packet.

2017-03-31T14:05:00.445835+00:00 proxy-internal-1 /sbin/opensips[16912]:
 used= 1022064, used+overhead=2011016, free=65097848
2017-03-31T14:10:52.229785+00:00 proxy-internal-1 /sbin/opensips[16912]:
 used= 1022064, used+overhead=2011016, free=65097848

Richard

**Comment by ionutrazvanionita** [comment] 2017-04-03 13:54
Pushed the two fixes in master, 2.3 and 2.2 . Do you have any clues regarding the last leak you've found?

**Comment by rrevels** [comment] 2017-04-03 14:15
Im wondering if it might not happen when a parsing error occurs during the
db insert section.   I haven't done enough work to determine one way or the
other yet though.

**Comment by bogdan-iancu** [comment] 2017-04-26 20:25
@rrevels , I assume there is no outstanding mem leak at the moment (based on your silence :) ).  So let's close this ticket and if you find something else, do not hesitate to open a new report.
Thanks for your report and assistance here !

**Closed by bogdan-iancu** 2017-04-26 20:25 UTC
Labels: bug
