### ISSUE TITLE
[CRASH]  _tcp_write_on_socket crashes when flushing async pending data

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#2258] opened 2020-09-21 21:22 UTC
**OpenSIPS version you are running**

```
version: opensips 2.4.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d17d0ed6c
main.c compiled on 16:31:57 Sep 14 2020 with gcc 7
```

**Crash Core Dump**

https://pastebin.com/v6bmkR7M

**Describe the traffic that generated the bug**

No specific pattern is known.

**To Reproduce**

Our server has been crashing every few hours all day, but we have not isolated any specific traffic as the cause.

**Relevant System Logs**

https://pastebin.com/5E87gLmq

**OS/environment information**
 - Operating System:  Amazon Linux 2
 - OpenSIPS installation:  git
 - other relevant information:

**Additional context**

**Comment by bcnewlin** [comment] 2020-09-28 20:13
We are still seeing these crashes multiple times per day.

```
version: opensips 2.4.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: a88a57479
main.c compiled on 21:12:05 Sep 25 2020 with gcc 7
```

Crash Backtrace: https://pastebin.com/svp06wk5

Crash Logs: https://pastebin.com/cLmpTsEg

**Comment by bcnewlin** [comment] 2020-09-28 20:14
These crashes may be the same as in #2216.

**Comment by bcnewlin** [comment] 2020-10-01 19:46
Some more crashes from today:

https://pastebin.com/3hHG6VqJ
https://pastebin.com/LEC3b8qQ
https://pastebin.com/Y2PsGMT4

**Comment by AnjanIpc** [comment] 2020-10-09 09:39
Is there any update on the issue pls ?
I had raised #2250 and it is closed by marked as Duplicate.

Thanks,

**Comment by AnjanIpc** [comment] 2020-10-14 07:25
Can someone update on this issue please ?
Thanks

**Comment by bogdan-iancu** [comment] 2020-10-15 14:58
The pattern of these crashes is shown here ->> https://pastebin.com/fRYDT0CF

**Comment by bcnewlin** [comment] 2020-10-15 15:00
```
(gdb) p *((struct tcp_data*)c->proto_data)
$1 = {async_chunks = 0x7f2491a4cf08, async_chunks_no = 0, oldest_chunk = 0}
```

**Comment by bogdan-iancu** [comment] 2020-10-15 15:11
and `p ((struct tcp_data*)c->proto_data)->async_chunks_no` ??

**Comment by bogdan-iancu** [comment] 2020-10-15 15:12
the backtrace shows a crash at that line, but according to GDB the memory seems to be valid

**Comment by bcnewlin** [comment] 2020-10-15 15:16
I don't entirely no what I'm doing here, so some of this may not be helpful. Just wanted to try to anticipate further requests. :)

```
(gdb) p ((struct tcp_data*)c->proto_data)->async_chunks_no
$1 = 0
(gdb) p ((struct tcp_data*)c->proto_data)->async_chunks
$2 = (struct tcp_send_chunk **) 0x7f2491a4cf08
(gdb) p *((struct tcp_data*)c->proto_data)->async_chunks
$3 = (struct tcp_send_chunk *) 0x7f2491a4cf18
(gdb) p **((struct tcp_data*)c->proto_data)->async_chunks
$4 = {buf = 0x3239613861333361 <error: Cannot access memory at address 0x3239613861333361>,
  pos = 0xc0c000313963352e <error: Cannot access memory at address 0xc0c000313963352e>, len = -1061109568, ticks = -1061109568}
```

**Comment by bogdan-iancu** [comment] 2020-10-15 15:27
Thank you @bcnewlin , this is weird. @AnjanIpc , do you still have your corefile for investigation ?

**Comment by AnjanIpc** [comment] 2020-10-15 15:50
@**bogdan-iancu** , yes i do have the core dump
DO you want to check anything ?

**Comment by bogdan-iancu** [comment] 2020-10-15 15:56
@AnjanIpc , the same, in frame 0, in gdb, do 
```
p (struct tcp_data*)c->proto_data
p *((struct tcp_data*)c->proto_data)
```

**Comment by AnjanIpc** [comment] 2020-10-15 16:02
(gdb) p (struct tcp_data*)c->proto_data
$1 = (struct tcp_data *) 0x0
(gdb) p *((struct tcp_data*)c->proto_data)
Cannot access memory at address 0x0

**Comment by bogdan-iancu** [comment] 2020-10-16 10:11
Thank you @AnjanIpc , so in your case, the `c->proto_data` is actually NULL (while in @bcnewlin 's backtrace it had a valid value).

Let me review a bit the code around setting the `c->proto_data` to be sure there are no races over there.

**Comment by bogdan-iancu** [comment] 2020-10-26 15:28
@AnjanIpc , any chance to output the "p *c" in frame 0 ?

**Comment by AnjanIpc** [comment] 2020-10-27 16:58
(gdb) p *c
$1 = {s = 50, fd = 5, proc_id = 8, write_lock = 1, id = 1949257128, cid = 11916216653931564456, rcv = {src_ip = {af = 2,
      len = 4, u = {addrl = {693619466, 0}, addr32 = {693619466, 0, 0, 0}, addr16 = {51978, 10583, 0, 0, 0, 0, 0, 0},
        addr = "\n\313W)", '\000' <repeats 11 times>}}, dst_ip = {af = 2, len = 4, u = {addrl = {49990410, 0}, addr32 = {
          49990410, 0, 0, 0}, addr16 = {51978, 762, 0, 0, 0, 0, 0, 0}, addr = "\n\313\372\002", '\000' <repeats 11 times>}},
    src_port = 33404, dst_port = 5061, proto = 3, proto_reserved1 = 1949257128, proto_reserved2 = 0, src_su = {s = {
        sa_family = 2, sa_data = "\202|\n\313W)\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 31874,
        sin_addr = {s_addr = 693619466}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2,
        sin6_port = 31874, sin6_flowinfo = 693619466, sin6_addr = {__in6_u = {
            __u6_addr8 = "\000\000\000\000\000\000\000\000\240S\032\030\376\177\000", __u6_addr16 = {0, 0, 0, 0, 21408,
              6170, 32766, 0}, __u6_addr32 = {0, 0, 404378528, 32766}}}, sin6_scope_id = 404646076}},
    bind_address = 0x7f0f898a99b8}, refcnt = 2, type = PROTO_TLS, state = S_CONN_OK, extra_data = 0x7f0f79bf7370,
  timeout = 189100, lifetime = 189100, id_hash = 424, id_next = 0x0, id_prev = 0x0, c_next = 0x0, c_prev = 0x0,
  con_aliases = {{parent = 0x7f0f79bf71e0, next = 0x0, prev = 0x0, port = 33404, hash = 374}, {parent = 0x0, next = 0x0,
      prev = 0x0, port = 0, hash = 0}, {parent = 0x0, next = 0x0, prev = 0x0, port = 0, hash = 0}, {parent = 0x0,
      next = 0x0, prev = 0x0, port = 0, hash = 0}}, aliases = 1, con_req = 0x0, msg_attempts = 0, flags = 28,
  proto_flags = 1, hist = 0x0, proto_data = 0x0}
(gdb)

**Comment by AnjanIpc** [comment] 2020-11-02 06:19
Any update on this please ?

**Comment by bogdan-iancu** [comment] 2020-11-04 08:47
@AnjanIpc, while trying to dig into this problem, I noticed some discrepancies in the data you provided. According to your [original report](https://github.com/OpenSIPS/opensips/issues/2250#issuecomment-701461693), the crash is in the `_tcp_write_on_socket` function, which is in the proto_tcp module. Still, in the report above, I see that the connection is PROTO_TLS.
So, what it is after all? a TCP or TLS connection ?

**Comment by AnjanIpc** [comment] 2020-11-04 08:55
OPTIONS sip:10.170.129.10:5059 SIP/2.0
                Max-Forwards: 10
                Record-Route: <sip:10.170.129.10:5066;r2=on;lr>
                Record-Route: <sip:10.170.129.10:5061;transport=tls;r2=on;lr>
                Via: SIP/2.0/UDP 10.170.129.10:5066;branch=z9hG4bK8211.d0c8ec670653c9643ca96622ef658bbb.0;i=c5106334
                Via: SIP/2.0/TCP 127.0.0.1:5061;received=10.67.17.2;rport=43438
                From: <sip:127.0.0.1:5061>
                To: <sip:10.170.129.10:5061>
                Contact: nexpose <sip:127.0.0.1:5061>
                Call-ID: 1234
                Cseq: 1 OPTIONS
                Content-Length: 0


This is the option message. while processing of 200 OK for this OPTIONS, opensips is crashing sometimes.

**Comment by AnjanIpc** [comment] 2020-11-11 09:12
Any update on this issue pls ?

**Comment by bogdan-iancu** [comment] 2020-11-12 16:49
sorry @AnjanIpc , I missed your reply here....nevertheless, you did not answer to my question - your [printing in gdb](https://github.com/OpenSIPS/opensips/issues/2258#issuecomment-717384248) is TLS and contradicts the TCP noticed in your [full backtrace](https://github.com/OpenSIPS/opensips/issues/2250#issuecomment-701461693).

So, from the same core file, please post the full bracktrace and also the `p *c` in frame 0 ? Again, from the same corefile, belonging to the same single crash

**Comment by AnjanIpc** [comment] 2020-11-20 07:12
(gdb) p *c
$1 = {s = 50, fd = 5, proc_id = 8, write_lock = 1, id = 1949257128, cid = 11916216653931564456, rcv = {src_ip = {af = 2,
len = 4, u = {addrl = {693619466, 0}, addr32 = {693619466, 0, 0, 0}, addr16 = {51978, 10583, 0, 0, 0, 0, 0, 0},
addr = "\n\313W)", '\000' <repeats 11 times>}}, dst_ip = {af = 2, len = 4, u = {addrl = {49990410, 0}, addr32 = {
49990410, 0, 0, 0}, addr16 = {51978, 762, 0, 0, 0, 0, 0, 0}, addr = "\n\313\372\002", '\000' <repeats 11 times>}},
src_port = 33404, dst_port = 5061, proto = 3, proto_reserved1 = 1949257128, proto_reserved2 = 0, src_su = {s = {
sa_family = 2, sa_data = "\202|\n\313W)\000\000\000\000\000\000\000"}, sin = {sin_family = 2, sin_port = 31874,
sin_addr = {s_addr = 693619466}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 2,
sin6_port = 31874, sin6_flowinfo = 693619466, sin6_addr = {__in6_u = {
__u6_addr8 = "\000\000\000\000\000\000\000\000\240S\032\030\376\177\000", __u6_addr16 = {0, 0, 0, 0, 21408,
6170, 32766, 0}, __u6_addr32 = {0, 0, 404378528, 32766}}}, sin6_scope_id = 404646076}},
bind_address = 0x7f0f898a99b8}, refcnt = 2, type = PROTO_TLS, state = S_CONN_OK, extra_data = 0x7f0f79bf7370,
timeout = 189100, lifetime = 189100, id_hash = 424, id_next = 0x0, id_prev = 0x0, c_next = 0x0, c_prev = 0x0,
con_aliases = {{parent = 0x7f0f79bf71e0, next = 0x0, prev = 0x0, port = 33404, hash = 374}, {parent = 0x0, next = 0x0,
prev = 0x0, port = 0, hash = 0}, {parent = 0x0, next = 0x0, prev = 0x0, port = 0, hash = 0}, {parent = 0x0,
next = 0x0, prev = 0x0, port = 0, hash = 0}}, aliases = 1, con_req = 0x0, msg_attempts = 0, flags = 28,
proto_flags = 1, hist = 0x0, proto_data = 0x0}
(gdb)

**Comment by AnjanIpc** [comment] 2020-12-29 13:46
Any update on this please ?

**Comment by AnjanIpc** [comment] 2021-02-17 10:11
Any update on this please ?

**Comment by leokoutikas** [comment] 2021-02-17 17:40
Hi @bogdan-iancu.  Would be great if you can share an update.  As you might guess, our customers don't like it when things crash while running a security scan.  Please let us know if you need anything else to drive towards root cause.  Thank you.

**Comment by bogdan-iancu** [comment] 2021-04-12 13:24
@bcnewlin , @AnjanIpc , I have here fix for this crash, if you could run some tests to validate it also on your side.
[tcp_proto_null_fix.patch.txt](https://github.com/OpenSIPS/opensips/files/6297001/tcp_proto_null_fix.patch.txt)
The patch is for 3.1, but it should apply fine against 2.4 also (if not, just let me know).

**Closed** 2021-04-20 15:26 UTC
Labels: bug, fixed, high-priority

**Comment by bcnewlin** [comment] 2021-04-20 19:29
@bogdan-iancu We ran with the patch for several days with no ill effects. Upgrading to the comitted version now. Thank you!
