### ISSUE TITLE
[CRASH] in fix_nated_sdp() in 3.4 and 3.5 version

### ISSUE THREAD

**Issue by cicahrad** [OpenSIPS/opensips#3225] opened 2023-10-11 10:39 UTC
Hi,

my openSIPs crash on this functuion: fix_nated_sdp("rewrite-media-ip");. I did try 3.4 and 3.5 versions whit same result. When I switch to 3.3 version all is working. In 3.3 version i call fix_nated_sdp(2);.

I did test on:
opensips 3.5.0-dev  git revision: 14df28478
opensips 3.4.1 git revision: 3a7a2bdfb

In log I have message:
Oct 11 11:49:49 ustredna opensips[2917133]: Oct 11 11:49:49 [2917133] CRITICAL:core:sig_usr: segfault in process pid: 2917133, id: 5

It happend on all inconimg INVITEs whit SDP contain private IP address. Here is example:
INVITE sip:60677@pbxm.ha-loo.cz SIP/2.0
Via: SIP/2.0/UDP 172.16.2.241:5062;rport;branch=z9hG4bKrskwyykh
Max-Forwards: 70
To: <sip:60677@pbxm.ha-loo.cz>
From: "77880" <sip:77880@pbxm.ha-loo.cz>;tag=hhwsl
Call-ID: tdwxrvffovcedlm@stepanX
CSeq: 570 INVITE
Contact: <sip:77880@172.16.2.241:5062>
Content-Type: application/sdp
Authorization: Digest xxxxxxxx
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,PRACK,REFER,NOTIFY,SUBSCRIBE,INFO,MESSAGE
Supported: replaces,norefersub,100rel
User-Agent: Twinkle/1.10.2
Content-Length: 307

v=0
o=twinkle 128826865 210941475 IN IP4 172.16.2.241
s=-
c=IN IP4 172.16.2.241
t=0 0
m=audio 8000 RTP/AVP 98 97 8 0 3 101
a=rtpmap:98 speex/16000
a=rtpmap:97 speex/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:3 GSM/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20

Here is link for bt full from core dump: https://pastebin.com/J9azPw4w

**OS/environment information**
 - Operating System: Debian 11
 - OpenSIPS installation: debs

I can reproduce problem any time.

Thank you
Stepan

**Comment by liviuchircu** [comment] 2023-10-11 18:23
Duplicate of #3226.  Or maybe the other way around... anyway, it's fixed now :-)

**Closed by liviuchircu** 2023-10-11 18:23 UTC
