### ISSUE TITLE
BUG in b2b_logic when add headers during REFER processing

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#2431] opened 2021-03-09 09:56 UTC
Hello team,

when I'm trying to add dynamic variables in b2b logic request route like this
```
$var(xxx) = $sql_cached_value(socket:id:$var(key));
$avp(hdrs) = "X-XXX-SockID";
$avp(hdrs_body) = $var(xxx);
```

and after that I call b2b_client_new() with $avp(hdrs) and $avp(hdrs_body).
after b2b_client_new() I call b2b_bridge() (processing REFER).

In this case I have crash because of instead of sql cached value there is freed memory pointer to it.

Addinig of static values works well.

**Comment by nikbyte** [comment] 2021-03-09 10:19
```
#3  b2b_scenario_hdrs (entity=0x7fbf349dfd20) at logic.c:3239
        b2b_hdrs_buf_len = 20
        b2b_hdrs_buf = {s = 0x7fbf349dfef8 "X-HCV-ZoneID: 1001\r\n\276\177", len = 20}
        len = <optimized out>
        tmp_buf = <optimized out>
        name_value = {n = 894631776, s = {s = 0x7fbe3552ff60 "X-XXX-SockID", len = 12}}
        body_value = {n = 3, s = {s = 0x7fbe00000003 <error: Cannot access memory at address 0x7fbe00000003>, len = 4}}
        avp_hdrs = 0x7fbe3552ff40
        avp_hdr_vals = 0x7fbe35303db8
        __FUNCTION__ = "b2b_scenario_hdrs"
```

line number may be wrong.

**Comment by nikbyte** [comment] 2021-03-09 10:20
```
(gdb) p name_value
$1 = {n = 894631776, s = {s = 0x7fbe3552ff60 "X-XXX-SockID", len = 12}}
(gdb) p body_value
$2 = {n = 3, s = {s = 0x7fbe00000003 <error: Cannot access memory at address 0x7fbe00000003>, len = 4}}
```

**Comment by nikbyte** [comment] 2021-03-09 11:58
Update. Figured it out. It's crashing when there is not string in avp.

**Comment by nikbyte** [comment] 2021-03-09 12:00
This is the reason of crash. We need to check better what returned from AVP. Because if there is null, header names and values are mixing. If there is an integer, opensips crashes.

**Comment by bogdan-iancu** [comment] 2021-03-30 15:11
@nikbyte , so the crash happens if one the hdr values is not a string, but int ?

**Comment by nikbyte** [comment] 2021-03-30 16:25
Yes, if value is integer, then we have a crash.

**Comment by bogdan-iancu** [comment] 2021-04-02 06:30
OK, I asked @rvlad-patrascu  to take a look here

**Comment by rvlad-patrascu** [comment] 2021-04-10 19:45
Hi @nikbyte

I've tried to reproduces the issue and what I found out is:
* opensips does not crash in my tests, when I use integer values, it just leaves the header name or value empty - I have pushed a fix for this
* As per normal OpenSIPS scripting, if you simply assign NULL to an AVP it will remove the last value of the AVP. This in turn will naturally lead to a mismatch between the intended header names and values. Also, the b2b_client_new() function will eventually notice there are too few header values corresponding to header names and throw an error. I would say that the b2b_client_new() function cannot automatically avoid this behavior and you should check for NULL values in the script before assigning them to the header AVPs.

**Comment by rvlad-patrascu** [comment] 2022-01-17 17:04
Hello @nikbyte 

Are you still having the issues described here?

**Comment by rvlad-patrascu** [comment] 2023-06-20 16:15
@nikbyte feel free to re-open this if there is still an issue here or you have anything to add to [my previous reply](https://github.com/OpenSIPS/opensips/issues/2431#issuecomment-817193167).

**Closed by rvlad-patrascu** 2023-06-20 16:15 UTC
Labels: bug, fixed
