### ISSUE TITLE
[BUG] t_on_reply doesn't work for CANCEL transaction

### ISSUE THREAD

**Issue by bcnewlin** [OpenSIPS/opensips#1648] opened 2019-03-27 14:18 UTC
**OpenSIPS version you are running**

```
version: opensips 2.4.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 52ff74af8
main.c compiled on 22:24:12 Mar 22 2019 with gcc 7
```

**Describe the bug**

 I have created routes to track transaction usage but I am running into an issue with the CANCEL transaction. It appears that replies to a CANCEL will only ever trigger the global onreply_route. When I arm a different transaction reply route using t_on_reply it is never called. Since the transaction is not available in the global reply route, I cannot use it for my purposes.

**To Reproduce**

1. Send a CANCEL message to OpenSIPS
2. Arm a reply route using t_on_reply
3. Receive 200 response to CANCEL
4. Verify expected reply route was not called

**Expected behavior**

The reply route armed with t_on_reply should be called when a reply to the CANCEL is received.

**Relevant System Logs**

**OS/environment information**
 - Operating System: Amazon Linux 2
 - OpenSIPS installation: git
 - other relevant information:

**Additional context**

**Comment by bogdan-iancu** [comment] 2019-05-22 17:32
@bcnewlin , after going down in the code's catacombs : 

- the global onreply is triggered by OpenSIPS code (not transaction/TM related) and it is called for any incoming reply.

- at TM level, the CANCEL propagates hop-by-hop - each party re-generates the CANCEL further and also locally consumes any incoming reply CANCEL. As being hop-by-hop (and not interesting), by design, TM does not trigger per-transaction onreply for CANCEL.

Definitely this is not a bug, in the worst case it is a limitation per design.

May I ask what you need to do with the CANCEL replies, in a transactional context ?

**Comment by bcnewlin** [comment] 2019-06-03 19:40
As I stated we are trying to create more detailed statistics around transaction usage against custom dimensions within our application, for example tracking transactions by customer, gateway, direction, etc. In order to successfully track transactions we must know when the start and when they end. As there is no callback for transaction states like with dialog (#1630) the only way to do this is via reply routes. However, this only works if every transaction will generate a reply. Because the statistics we are trying to track are specific to the transaction they are stored in AVPs, which cannot be accessed from the global reply route, only from the TM route.

**Comment by bogdan-iancu** [comment] 2019-06-06 08:10
I see. Still, I guess you want to trace the state of the INVITE transaction, not of the CANCEL transaction. And you mentioned that you want to cover the case when there is not incoming reply for the INVITE, so no onreply route for the INVITE - and if I understand it correctly, this is the gap you try to fill in.
If so, why not using the failure route to "trace" even the locally generated final replies (like 408). Otherwise I fail to see how the reply of the CANCEL will help you understanding what happened with your INVITE - what it is important is the outcome of the INVITE transaction.

Now, more on the handling of the CANCEL replies - as the CANCEL is a hop-by-hop request (each proxy consumes the incoming CANCEL and re-generates its own CANCEL for further sending), the reply is considered as a reply for a UAC-type transaction in OpenSIPS - a reply for a request generated by OpenSIPS. And such replies do not hit the onreply route - for example, if you do MI `t_uac_dlg` or script `t_new_request`, their replies will not hit the onreply route.

**Comment by bcnewlin** [comment] 2019-06-06 12:42
No, the desire was to track the state of ALL transactions, not just INVITE. That is why the inability to get a reply for CANCEL was an issue. There is no issue tracking INVITE transactions as they always trigger some sort of reply/failure route (if armed).

**Comment by bogdan-iancu** [comment] 2019-06-10 07:05
I understand this, but as mentioned, per design, the onreply route is not triggered for the replies to local requests (locally generated requests) - and the hopbyhop CANCEL is one of them.
In the best case, we can move this to a Feature Request, but definitely it is not a bug

**Comment by bcnewlin** [comment] 2019-06-10 14:46
Yes, I understand as well. :) If you say it is by design then I agree it is by definition not a bug. It could be considered a feature request, although for my purposes #1630 would be more helpful.

**Comment by bogdan-iancu** [comment] 2019-06-13 16:02
OK, I will close this one - if you are still interested in getting access to the CANCEL reply, please open a feature request.

**Closed by bogdan-iancu** 2019-06-13 16:02 UTC
