### ISSUE TITLE
[BUG] Presence module is failing to send NOTIFY when TCP transport in combination with Route is in use

### ISSUE THREAD

**Issue by vkuzmenok** [OpenSIPS/opensips#2280] opened 2020-10-09 23:37 UTC
**OpenSIPS version you are running**

```
version: opensips 2.4.5 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: d025b4f61
main.c compiled on 18:52:58 Oct  9 2020 with gcc 4.8.5
```
The issue is also reproducible with 2.4.8
**Describe the bug**
NOTIFY messages are not being sent for presence subscriptions when TCP transport is being used in Route header

**To Reproduce**
Generate the SIP SUBSCRIBE at UAC as below
SUBSCRIBE sip:2101-1@mydomain.com SIP/2.0
Record-Route: <sip:<UAC_IP>;transport=tcp;r2=on;lr>
Record-Route: <sip:<UAC_IP>;r2=on;lr>
Allow: INVITE, ACK, BYE, CANCEL, REGISTER, OPTIONS, INFO
Content-Length: 0
CSeq: 1 SUBSCRIBE
Expires: 300
Route: <sip:2101@<opensips_UAS_IP>:5060;transport=tcp;lr>
Contact: <sip:wlssuser@<UAC_IP>:5059;transport=udp;wlsscid=65243f65cf6;sipappsessionid=app-1xa4t9gcmi9nz;wlssfcid=sip-1exr0rfz68nx2>
Call-ID: wlss-1209cf48-7d4169761aa379fad401b7c59eafc65c@<UAC_IP>
Max-Forwards: 68
From: <sip:2101@<UAC_IP>>;tag=e29f4efc
To: sip:2101-1@mydomain.com
Event: presence
Via: SIP/2.0/TCP <UAC_IP>:5060;branch=z9hG4bKc841.8de3264b4653d8e4d9133eceeed0d1ca.0
Via: SIP/2.0/UDP <UAC_IP>:5059;wlsscid=65243f65cf6;branch=z9hG4bK8bb59946548a0ad6713ee9a86e5aa3ea

200 OK message is being sent without issues

NOTIFY is failing with the following in the logs

```
DBG:presence:build_dlg_t: CONTACT = sip:wlssuser@<UAC_IP>:5059;transport=udp;wlsscid=65243f65cf6;sipappsessionid=app-1xa4t9gcmi9nz;wlssfcid=sip-1exr0rfz68nx2
DBG:tm:t_uac: next_hop=<sip:<UAC_IP>;transport=tcp;r2=on;lr>
DBG:core:mk_proxy: doing DNS lookup...
DBG:tm:t_uac: sending socket is 172.29.107.196
DBG:tm:dlg2hash: 5260
DBG:tm:print_request_uri: sip:wlssuser@<UAC_IP>:5059;transport=udp;wlsscid=65243f65cf6;sipappsessionid=app-1xa4t9gcmi9nz;wlssfcid=sip-1exr0rfz68nx2
ERROR:tm:msg_send: send() to <UAC_IP>:5060 for proto tcp/2 failed
ERROR:tm:t_uac: attempt to send to 'sip:<UAC_IP>;transport=tcp;r2=on;lr' failed
DBG:tm:insert_timer_unsafe: [0]: 0x7ff5c7a680c8 (434)
INFO:presence:send_notify_request: NOTIFY sip:2101@<UAC_IP> via sip:<UAC_IP>;transport=tcp;r2=on;lr on behalf of sip:2101-1@ffd.ipc.com for event presence, to_tag=3844867f83aaa272f230f2cffce9b974.4448, cseq=1

```
With some code modification of proto_tcp.c I was able to see that code fails on this check

	/* was connection found ?? */
	if (c==0) {
		if (tcp_no_new_conn) {
			return -1;
		}

**Expected behavior**

The server should be able to send NOTIFY messages using TCP proto to the IP address and port in the Route header.

**OS/environment information**
 - Operating System: RHEL 7

**Comment by razvancrainea** [comment] 2020-10-13 14:40
You're probably setting the [tcp_no_new_conn_bflag](https://www.opensips.org/Documentation/Script-CoreParameters-3-1#toc74) flag before handling the `SUBSCRIBE`/`PUBLISH`, that's why OpenSIPS will not open a new connection for the generated `NOTIFY`. Can you confirm the flag is set in your script?

**Comment by vkuzmenok** [comment] 2020-10-13 15:11
@razvancrainea 
There is no explicit setting for the tcp_no_new_conn_bflag in the script. In the [modules/presence/notify.c](https://github.com/OpenSIPS/opensips/blob/master/modules/presence/notify.c)  in send_notify_request, on line 2135 tcp_no_new_conn is explicitly set to 1

If I remove that assignment, I do not see any more errors in the log, and I can see NOTIFY on the wire.

**Comment by razvancrainea** [comment] 2020-10-15 10:39
This is not a bug, it is exactly how it should work.
The idea is the following: OpenSIPS receives the SUBSCRIBE from sipp over TCP connection UAC_IP:SIPP_PORT. When the NOTIFY is generated, it should ideally go back through the same TCP connection; however, the Route says it should be sent to UAC_IP:5060 (and 5060 is probably != SIPP_PORT). That's why the connection cannot be found.

In order to fix this, you have 3 alternatives:
1. Fix the SIPP scenario - add the local port in the Request-Route header (this is the preferred method)
2. Add a TCP alias for SIPP_PORT -> 5060. This way when the NOTIFY is generated to port 5060, OpenSIPS will find this alias and send it over the same TCP connection
3. Catch the NOTIFY in `local_route` and reset the tcp_no_new_conn_bflag - this will create a new connection to the UAC_IP:5060 server (note that I haven't tested this, but it should work). Although this might work, in practice, if client is not reachable, the NOTIFY will be lost - it will not be sent over the same connection the SUBSCRIBE created.

Closing this ticket as it is not a bug, but rather just works differently. If you have further questions, please use our [mailing list](http://lists.opensips.org/cgi-bin/mailman/listinfo/users).

**Closed** 2020-10-15 10:39 UTC
