### ISSUE TITLE
t_inject_branches  do not work with path  extenstion

### ISSUE THREAD

**Issue by futsystems** [OpenSIPS/opensips#1235] opened 2017-12-16 04:44 UTC
OpenSIPS 2.3.2
UA1--[P1]--[REG]
UA1--[P2]--[REG]
UA1 use p1 as outbound sip proxy,UA2 use p2 as outbound sip proxy
proxy use path module,and add_path_received when UA send register request.

**_Problem 1_**:t_inject_branches branch Invite request do not send message to Route.
UA2 online:
UA1 make call to UA2, the sip message will send as UA1->P1->REG->P2->UA2 as designed.
REG send Invite request with Route:<P2;received>. P2 loos_route, will take received as desitnation and send message to UA2. all these works well.

UA2 offline:
REG server use event_routing module to subscribe event E_UL_CONTACT_INSERT to fork_call
when UA2 got notified and register to REG, then for_call route call t_inject_branches("event").
this time, the invite request fill the contact (also have route set as online ) but send to UA2's received address directly. then P2 is bypassed.
I think t_inject_branches should fire the inital Invite and send to Route: not to send UA2 directly.

maybe i miss use some module, and it is not a bug.
and i am trying find a way to bypass that, set $du in branch_route. but i can not get reg_attr properly.
xlog("Attributes for branch $T_branch_idx: $(avp(reg_attr)[$T_branch_idx])\n");
when i set the event_routing, and from t_inject_branches's branch, i get (avp(reg_attr) as Null. i have no idea how to get proxy ip from reg_attr.

**_Problem2_**: notify_on_event fire notify_route even when the transction is canceled
notify_on_event("E_UL_CONTACT_INSERT","$avp(filter)","fork_call", "20");
UA1 make a call to UA2 at Time1, UA2 will be notified and register to REG, and the subscription will be notified.
UA1 cancel the call at Time2.
UA1 make another call to UA2 immediately again at Time3 ,UA2 will be notified and register to REG again.
if Time3-Time1<20(the timeout of subscription ) the fork_call will be notified twice.one is the Call1 and another is Call2. i think.

so why UA1 cancel the call1, but the fork_call still be notified at Call2? i think if transaction is canceled,then the subscription will not be notified.

**_Problem3_**: t_wait_for_new_branches
t_wait_for_new_branches is enable in the invite route.
UA1 make a to UA2, UA2 is notifed and register to  REG, and  fork_call is notified.
but before UA2 answer the call, UA1 cancel the call. but the transaction can not be canceled.till fr_time_out.
so i think if Caller cancel the call, transaction need to be canceled other than fr_inv_timeout hit.

**Comment by futsystems** [comment] 2017-12-20 05:08
problem1: about reg_attr
when branch is generated by lookup ,then contact's  attr fileld is passed into branch_route. we can get the attr filed in branch_route.

if branch is generated by t_inject_branches,then event's args do not have attr field,so we can not get attr field in branch_route. 
maybe it is better for E_UL_CONTACT_INSERT event  to supply contact's attr field.

**Comment by bogdan-iancu** [comment] 2017-12-20 12:46
@futsystems , thanks for the reports - I already pushed a fix for problem 1 (with the path) - please give it a try and confirm the fix.
In the mean while I will check the other problems you reported.

**Comment by futsystems** [comment] 2017-12-20 14:16
@bogdan-iancu the problem1 is fixed, i have tested. now proxy1 proxy2 can make calls between them without problem. that is great.

**Comment by bogdan-iancu** [comment] 2017-12-20 14:31
Following with Problem2 (the canceled call) - The Event-based Routing mechanism is not necessarily bound to a transaction (it can work even outside the context of a transaction). Because of that, there is not such a tight relation between EBR and TM - the "relation" between the two is limited to storing the transaction ID into the EBR subscription. But the EBR is not aware of the transaction state or even if the transaction still exists or not - it has only its ID.
So, as time as the subscription is still valid at time, the route will be triggered. The only place where your processing becomes transaction aware is inside the t_inject_branches() - this will fetch the transaction ID from the event, it will search for the transaction and do the branching stuff.
There is no way for the RBR engine to know that the transaction was canceled or not - only the t_inject_branch() will find this out and fail to add the branch.
Let me know your thoughts based on my input here.

**Comment by bogdan-iancu** [comment] 2017-12-20 14:58
Now, on Problem3 (cancel while ringing) - if I understand correctly the scenario, the call got a new branch (via EBR) upon UA2 registration, so UA2 is ringing. And if UA1 sends a Cancel, according to my tests, the UA2 will receive the Cancel on spot. Am I doing something different than you  ?

**Comment by futsystems** [comment] 2017-12-20 15:03
thank you for explain the mechanism of EBR module.

i have collect logs for that situation.
-->REQUEST: [REGISTER] ru[sips:<PROXY1>:443;transport=tls] fu[62000001] tu[62000001]  CID[OPk90sHp7LpYq4sbHj7QGn3cDzGibQHQ]
user 62000001 registered the a new contact sips:62000001@10.38.245.254:65204;transport=TLS, injecting
[New Branch] Branch_ID:1 M=INVITE RURI=sips:62000001@10.38.245.254:65204;transport=TLS F=5280002 T=62000001
user 62000001 registered the a new contact sips:62000001@10.38.245.254:65204;transport=TLS, injecting
[New Branch] Branch_ID:2 M=INVITE RURI=sips:62000001@10.38.245.254:65204;transport=TLS F=5280002 T=62000001
REPLY INVITE: [100]->[INVITE]@CID[ace421e81fc141d39ec75c20ec83af76]
REPLY INVITE: [100]->[INVITE]@CID[ace421e81fc141d39ec75c20ec83af76]
REPLY INVITE: [180]->[INVITE]@CID[ace421e81fc141d39ec75c20ec83af76]
REPLY INVITE: [180]->[INVITE]@CID[ace421e81fc141d39ec75c20ec83af76]

then two branch's CID are same.
so i guess subscription got notified and trigger the fork_call route with the same transaction ID. then t_inject_branches inject twice.

but notify_on_event create subscription in different Invite's transaction, so i think they should have different transaction ID from subscriber content.
t_inject_branch will create branch in different transaction, but the log seems the branch created are only in the new transaction.

do i understand these staff right?

**Comment by bogdan-iancu** [comment] 2017-12-20 15:07
Is your previous comment related to Problem 2 (registering after the call was canceled) ?

**Comment by futsystems** [comment] 2017-12-20 15:08
yes it is.

**Comment by futsystems** [comment] 2017-12-20 15:21
Yes,your testing are same with me.**(Problem 3)**
UA1 call UA2 via(EBR) upon UA2 registration
UA2 ring,UA1 cancel the call,UA2 got cancel correctly. but UA1's call is still on, 487 is delayed.
please check the image from wireshark.
![problem-3-1](https://user-images.githubusercontent.com/5887620/34214112-72b3ac36-e5dc-11e7-92f0-0e036b98b6cb.png)

**Comment by bogdan-iancu** [comment] 2017-12-20 15:27
OK, I understood and was able to reproduce the Problem3 - please let's fork this out from this ticket and create a separate ticket for the Problem3 (as now it proved to be a stand-alone bug).

**Comment by futsystems** [comment] 2017-12-20 15:43
ok,thanks for your time.

**Comment by bogdan-iancu** [comment] 2017-12-20 15:46
The remaining issue here is Problem2 - in this case, EBR will trigger the fork_call route twice - one time for the call1 (which was canceled) and one time for the call2 (which is in ringing state).
In order to check it for sure, please provide (it may be off-forum - reach me via bogdan at opensips dot org) the opensips logs in level 4 (debug) and the ngrep capture of the SIP traffic (on opensips ip)

**Comment by futsystems** [comment] 2017-12-20 15:52
ok i will collect more detail  info about that,and send to you via email later.

**Comment by futsystems** [comment] 2017-12-22 01:22
i have collect the log and send email,please check for email arrival.

**Comment by bogdan-iancu** [comment] 2017-12-22 08:32
I got the email, thank you

**Comment by bogdan-iancu** [comment] 2017-12-22 12:34
Thank you @futsystems , this helped me to understand your actual scenario - the call is not actually canceled (meaning UA1 is sending a CANCEL to UA2), but it is declined (UA2 rejects with 603 reply).

The difference is major between the two cases - when subscribing and waiting for potential new registrations, the transaction is still kept as pending even if all the existing branches were rejected. This approach is needed for scenarios where you call to a number that is registered with a hardphone and a mobile app using Push Notification - even if the hard phone rejected the call (busy?), you still want to have to call delivered to the mobile app - that means to wait for the PN to take effect and have the app registered. So, while the transactions does not timeout (according to fr_inv_timeout), it will receive the notification and fork new branches even if all the current branches are terminated. Again, this is how PN should work.
So, the behavior is as expected.

**Comment by atrips** [comment] 2019-05-07 11:56
Hello,

@bogdan-iancu I understand that in current design if B party rejects call (486 Busy Here) you still need to wait fr_inv_timer to be reached. In our use case this causes a problem as we have no desk phone involved but only mobile one. Do you think that it will be possible to terminate transaction based on specific list with response codes ?

**Comment by bogdan-iancu** [comment] 2019-05-31 13:14
Re-opening for re-evaluation

**Comment by atrips** [comment] 2019-06-04 12:36
Little more info related to my comment above to explain our use case. The goal is OpenSIPS to be deployed as "generic" SIP push notification proxy in ANY SIP infrastructure.

Simplified architecture is pretty standard UA - (Push Proxy) - (PBX/SoftSwitch). In our case PBX/SS is 3rt party solution that we have no control over it. PBX is a place that call forking and all other telephony services are handled. Push Proxy should be transparent (as possible) to existing/deployed infrastructure. It should forwards registration request to the PBX, stores location on successful registration reply and sends push notification on mobile terminating calls/messages only for mobile application customers (like SBC with Push notification abilities). That is the reason I'm searching a way to terminate transaction based on specific error cause.

**Comment by bogdan-iancu** [comment] 2019-08-21 15:00
OK, I opened the #1811 feature request to address your need here (as it is not a bug)

**Closed by bogdan-iancu** 2019-08-21 15:00 UTC
Labels: bug, fixed
