### ISSUE TITLE
Re-invite pings are broken in 2.2

### ISSUE THREAD

**Issue by 46labs** [OpenSIPS/opensips#954] opened 2016-09-06 12:51 UTC
Behavior:

SIP Re-invite pings will be sent at random intervals between 1 second and the re-invite ping interval. A log message is thrown saying that the dialogs are going to be terminated. It does send the re-invites out, but when the dialog is scheduled for teardown and the re-invite interval elapses, the dialog is removed from opensips, but a Bye is never generated.

create dialog is called with "RrB" flags. 

version: opensips 2.2.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, HP_MALLOC, FAST_LOCK-FUTEX-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 7261cf0
main.c compiled on 00:54:40 Sep  5 2016 with gcc 5.4.0

Dialog List:

dialog::  hash=1141:1236350104
       	state:: 5
       	user_flags:: 0
       	timestart:: 1473165665
       	datestart:: 2016-09-06 12:41:05
       	timeout:: 0
       	callid:: 17-29858@10.0.2.225
       	from_uri:: sip:14054104980@10.0.2.225:5060
       	to_uri:: sip:service@209.105.251.200:5060
       	caller_tag:: 29858SIPpTag0017
       	caller_contact:: sip:209.105.251.200;did=574.50494f3
       	callee_cseq:: 0
       	caller_route_set::
       	caller_bind_addr:: udp:10.0.4.29:5060
       	caller_sdp:: v=0
o=user1 53655765 2353687637 IN IP4 10.0.2.225
s=-
c=IN IP4 10.0.2.225
t=0 0
m=audio 6000 RTP/AVP 0
a=rtpmap:0 PCMU/8000
       	CALLEES::
       		callee::
       			callee_tag:: 2030F6E3-57CEB9600007EFB1-5E9E9700
       			callee_contact:: sip:10.0.4.29:5062;transport=udp
       			caller_cseq:: 1
       			callee_route_set::
       			callee_bind_addr:: udp:10.0.4.29:5060
       			callee_sdp:: v=0
o=- 53655765 2353687637 IN IP4 10.0.4.29
s=-
c=IN IP4 10.0.4.29
t=0 0
m=audio 20042 RTP/AVP 0 18 8
a=rtpmap:0 PCMU/8000
a=rtpmap:18 g729/8000
a=rtpmap:8 pcma/8000
a=sendrecv
a=direction:both
dialog::  hash=1676:1091999188
       	state:: 5
       	user_flags:: 0
       	timestart:: 1473165666
       	datestart:: 2016-09-06 12:41:06
       	timeout:: 0
       	callid:: 18-29858@10.0.2.225
       	from_uri:: sip:14054104980@10.0.2.225:5060
       	to_uri:: sip:service@209.105.251.200:5060
       	caller_tag:: 29858SIPpTag0018
       	caller_contact:: sip:209.105.251.200;did=c86.8a4e59e
       	callee_cseq:: 0
       	caller_route_set::
       	caller_bind_addr:: udp:10.0.4.29:5060
       	caller_sdp:: v=0
o=user1 53655765 2353687637 IN IP4 10.0.2.225
s=-
c=IN IP4 10.0.2.225
t=0 0
m=audio 6000 RTP/AVP 0
a=rtpmap:0 PCMU/8000
       	CALLEES::
       		callee::
       			callee_tag:: 214380BA-57CEB9610007EDCD-5E4E4700
       			callee_contact:: sip:10.0.4.29:5062;transport=udp
       			caller_cseq:: 1
       			callee_route_set::
       			callee_bind_addr:: udp:10.0.4.29:5060
       			callee_sdp:: v=0
o=- 53655765 2353687637 IN IP4 10.0.4.29
s=-
c=IN IP4 10.0.4.29
t=0 0
m=audio 20046 RTP/AVP 0 18 8
a=rtpmap:0 PCMU/8000
a=rtpmap:18 g729/8000
a=rtpmap:8 pcma/8000
a=sendrecv
a=direction:both

Attaching syslog at log level 4.
[reinvite_issue.txt](https://github.com/OpenSIPS/opensips/files/456704/reinvite_issue.txt)

**Comment by razvancrainea** [comment] 2016-09-06 13:12
Hi, Trevor!

Can you also provide a sip trace for this call? It would be easier to follow and correlate to the syslog messages.

Thanks,
Răzvan

**Comment by 46labs** [comment] 2016-09-06 13:56
U 209.105.251.200:5060 -> 10.0.4.29:5060
INVITE sip:15122033884@209.105.251.200;user=phone SIP/2.0.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0018.
To: 1111#15122033884 <sip:service@209.105.251.200:5060>.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Contact: <sip:209.105.251.200;did=c86.8a4e59e>.
Max-Forwards: 68.
Subject: Performance Test.
Content-Type: application/sdp.
Content-Length:   131.
X-Session: W15CCwpJX14sWkNLWkhdX0VbUw==.
X-OrigData: 1,e66bea8d,3.
X-OrigIP: 10.0.2.225.
X-SwitchIP: 209.105.251.200.
X-OrigPrefix: 1111.
X-MaxMedia: 100.
X-Disable_ANI_Normalization: 0.
.
v=0.
o=user1 53655765 2353687637 IN IP4 10.0.2.225.
s=-.
c=IN IP4 10.0.2.225.
t=0 0.
m=audio 6000 RTP/AVP 0.
a=rtpmap:0 PCMU/8000.


U 10.0.4.29:5060 -> 209.105.251.200:5060
SIP/2.0 100 Trying.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0018.
To: 1111#15122033884 <sip:service@209.105.251.200:5060>.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Content-Length: 0.
.


U 10.0.4.29:5060 -> 209.105.251.200:5060
SIP/2.0 100 Giving a try.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0018.
To: 1111#15122033884 <sip:service@209.105.251.200:5060>.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Content-Length: 0.
.


U 10.0.4.29:5060 -> 10.0.4.29:5062
INVITE sip:1002#15122033884@10.0.4.176;user=phone SIP/2.0.
Record-Route: <sip:10.0.4.29;lr;ftag=29858SIPpTag0018;did=c86.4d596114>.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK3c6f.3b0fc555.0.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0018.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Contact: <sip:209.105.251.200;did=c86.8a4e59e>.
Max-Forwards: 67.
Subject: Performance Test.
Content-Type: application/sdp.
Content-Length:   131.
X-Session: W15CCwpJX14sWkNLWkhdX0VbUw==.
Remote-Party-ID: <sip:14054104980@209.105.251.200>;privacy=off;screen=yes.
P-Asserted-Identity: <sip:14054104980@209.105.251.200;user=phone>.
X-Direction: EGRESS.
X-EgressLB: 209.105.251.200:5060.
X-MediaAnchor: transcoding.
.
v=0.
o=user1 53655765 2353687637 IN IP4 10.0.2.225.
s=-.
c=IN IP4 10.0.2.225.
t=0 0.
m=audio 6000 RTP/AVP 0.
a=rtpmap:0 PCMU/8000.


U 10.0.4.29:5062 -> 10.0.4.29:5060
SIP/2.0 100 Connecting.
Record-Route: <sip:10.0.4.29;lr;ftag=29858SIPpTag0018;did=c86.4d596114>.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK3c6f.3b0fc555.0.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0018.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Content-Length: 0.
.


U 10.0.4.29:5062 -> 209.105.251.200:5060
INVITE sip:1002#15122033884@10.0.4.176;user=phone SIP/2.0.
Via: SIP/2.0/UDP 10.0.4.29:5062;branch=z9hG4bKQxqIGabk;rport.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=54C36D69-57CEB9610007EF08-670EA700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>.
CSeq: 10 INVITE.
Call-ID: 0367FB70-57CEB9610007EF0A-670EA700.
Max-Forwards: 70.
X-Session: W15CCwpJX14sWkNLWkhdX0VbUw==.
Remote-Party-ID: <sip:14054104980@209.105.251.200>;privacy=off;screen=yes.
P-Asserted-Identity: <sip:14054104980@209.105.251.200;user=phone>.
X-Direction: EGRESS.
Supported: timer.
Session-Expires: 1800.
Min-SE: 90.
Content-Type: application/sdp.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Length: 206.
.
v=0.
o=- 53655765 2353687637 IN IP4 10.0.4.29.
s=-.
c=IN IP4 10.0.4.29.
t=0 0.
m=audio 20044 RTP/AVP 0 18 8.
a=rtpmap:0 PCMU/8000.
a=rtpmap:18 g729/8000.
a=rtpmap:8 pcma/8000.
a=sendrecv.
a=direction:both.


U 209.105.251.200:5060 -> 10.0.4.29:5062
SIP/2.0 100 Giving a try.
Via: SIP/2.0/UDP 10.0.4.29:5062;received=10.0.4.29;branch=z9hG4bKQxqIGabk;rport=5062.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=54C36D69-57CEB9610007EF08-670EA700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>.
CSeq: 10 INVITE.
Call-ID: 0367FB70-57CEB9610007EF0A-670EA700.
Content-Length: 0.
.


U 209.105.251.200:5060 -> 10.0.4.29:5062
SIP/2.0 180 Ringing.
Via: SIP/2.0/UDP 10.0.4.29:5062;received=10.0.4.29;rport=5062;branch=z9hG4bKQxqIGabk.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=54C36D69-57CEB9610007EF08-670EA700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=32336SIPpTag0120.
Call-ID: 0367FB70-57CEB9610007EF0A-670EA700.
CSeq: 10 INVITE.
Contact: <sip:209.105.251.200;did=58f.abb9a515>.
X-Foo: Bar1.
Content-Length: 0.
.


U 10.0.4.29:5062 -> 10.0.4.29:5060
SIP/2.0 180 Ringing.
Record-Route: <sip:10.0.4.29;lr;ftag=29858SIPpTag0018;did=c86.4d596114>.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK3c6f.3b0fc555.0.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0018.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Length: 0.
.


U 10.0.4.29:5060 -> 209.105.251.200:5060
SIP/2.0 180 Ringing.
Record-Route: <sip:10.0.4.29;lr;ftag=29858SIPpTag0018;did=c86.4d596114>.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0018.
To: 1111#15122033884 <sip:service@209.105.251.200:5060>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Length: 0.
.


U 209.105.251.200:5060 -> 10.0.4.29:5062
SIP/2.0 200 OK.
Via: SIP/2.0/UDP 10.0.4.29:5062;received=10.0.4.29;rport=5062;branch=z9hG4bKQxqIGabk.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=54C36D69-57CEB9610007EF08-670EA700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=32336SIPpTag0120.
Call-ID: 0367FB70-57CEB9610007EF0A-670EA700.
CSeq: 10 INVITE.
Contact: <sip:209.105.251.200;did=58f.abb9a515>.
Content-Type: application/sdp.
Content-Length:   131.
.
v=0.
o=user1 53655765 2353687637 IN IP4 10.0.4.176.
s=-.
c=IN IP4 10.0.4.176.
t=0 0.
m=audio 6000 RTP/AVP 0.
a=rtpmap:0 PCMU/8000.


U 10.0.4.29:5062 -> 10.0.4.29:5060
SIP/2.0 200 OK.
Record-Route: <sip:10.0.4.29;lr;ftag=29858SIPpTag0018;did=c86.4d596114>.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK3c6f.3b0fc555.0.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0018.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Supported: timer.
Session-Expires: 1800;refresher=uas.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Type: application/sdp.
Content-Length: 206.
.
v=0.
o=- 53655765 2353687637 IN IP4 10.0.4.29.
s=-.
c=IN IP4 10.0.4.29.
t=0 0.
m=audio 20046 RTP/AVP 0 18 8.
a=rtpmap:0 PCMU/8000.
a=rtpmap:18 g729/8000.
a=rtpmap:8 pcma/8000.
a=sendrecv.
a=direction:both.


U 10.0.4.29:5060 -> 209.105.251.200:5060
SIP/2.0 200 OK.
Record-Route: <sip:10.0.4.29;lr;ftag=29858SIPpTag0018;did=c86.4d596114>.
Via: SIP/2.0/UDP 209.105.251.200:5060;branch=z9hG4bK3c6f.320e14d1.0.
From: 14054104980 <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0018.
To: 1111#15122033884 <sip:service@209.105.251.200:5060>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
Call-ID: 18-29858@10.0.2.225.
CSeq: 1 INVITE.
Supported: timer.
Session-Expires: 1800;refresher=uas.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Type: application/sdp.
Content-Length: 206.
.
v=0.
o=- 53655765 2353687637 IN IP4 10.0.4.29.
s=-.
c=IN IP4 10.0.4.29.
t=0 0.
m=audio 20046 RTP/AVP 0 18 8.
a=rtpmap:0 PCMU/8000.
a=rtpmap:18 g729/8000.
a=rtpmap:8 pcma/8000.
a=sendrecv.
a=direction:both.


U 10.0.4.29:5060 -> 209.105.251.200:5060
INVITE sip:209.105.251.200;did=c86.8a4e59e SIP/2.0.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK3c6f.4b0fc555.0.
To: <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0018.
From: <sip:service@209.105.251.200:5060>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
CSeq: 1 INVITE.
Call-ID: 18-29858@10.0.2.225.
Max-Forwards: 70.
Content-Length: 206.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Type: application/sdp.
.
v=0.
o=- 53655765 2353687637 IN IP4 10.0.4.29.
s=-.
c=IN IP4 10.0.4.29.
t=0 0.
m=audio 20046 RTP/AVP 0 18 8.
a=rtpmap:0 PCMU/8000.
a=rtpmap:18 g729/8000.
a=rtpmap:8 pcma/8000.
a=sendrecv.
a=direction:both.


U 10.0.4.29:5060 -> 10.0.4.29:5062
INVITE sip:10.0.4.29:5062;transport=udp SIP/2.0.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK0c6f.55012202.0.
To: <sip:1002#15122033884@10.0.4.176>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
From: <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0018.
CSeq: 2 INVITE.
Call-ID: 18-29858@10.0.2.225.
Max-Forwards: 70.
Content-Length: 131.
Contact: <sip:209.105.251.200;did=c86.8a4e59e>.
Content-Type: application/sdp.
.
v=0.
o=user1 53655765 2353687637 IN IP4 10.0.2.225.
s=-.
c=IN IP4 10.0.2.225.
t=0 0.
m=audio 6000 RTP/AVP 0.
a=rtpmap:0 PCMU/8000.


U 10.0.4.29:5062 -> 10.0.4.29:5060
SIP/2.0 100 Trying.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK0c6f.55012202.0.
To: <sip:1002#15122033884@10.0.4.176>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
From: <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0018.
CSeq: 2 INVITE.
Call-ID: 18-29858@10.0.2.225.
Content-Length: 0.
.


U 10.0.4.29:5062 -> 209.105.251.200:5060
INVITE sip:209.105.251.200;did=58f.abb9a515 SIP/2.0.
Via: SIP/2.0/UDP 10.0.4.29:5062;branch=z9hG4bKdBERjang;rport.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=54C36D69-57CEB9610007EF08-670EA700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=32336SIPpTag0120.
CSeq: 11 INVITE.
Call-ID: 0367FB70-57CEB9610007EF0A-670EA700.
Max-Forwards: 70.
Supported: timer.
Session-Expires: 1800.
Min-SE: 90.
Content-Type: application/sdp.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Length: 206.
.
v=0.
o=- 53655765 2353687637 IN IP4 10.0.4.29.
s=-.
c=IN IP4 10.0.4.29.
t=0 0.
m=audio 20044 RTP/AVP 0 18 8.
a=rtpmap:0 PCMU/8000.
a=rtpmap:18 g729/8000.
a=rtpmap:8 pcma/8000.
a=sendrecv.
a=direction:both.


U 209.105.251.200:5060 -> 10.0.4.29:5060
SIP/2.0 100 Giving a try.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK3c6f.4b0fc555.0.
To: <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0018.
From: <sip:service@209.105.251.200:5060>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
CSeq: 1 INVITE.
Call-ID: 18-29858@10.0.2.225.
Content-Length: 0.
.


U 10.0.4.29:5060 -> 209.105.251.200:5060
INVITE sip:209.105.251.200;did=574.50494f3 SIP/2.0.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bKca49.a01809.0.
To: <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0017.
From: <sip:service@209.105.251.200:5060>;tag=2030F6E3-57CEB9600007EFB1-5E9E9700.
CSeq: 1 INVITE.
Call-ID: 17-29858@10.0.2.225.
Max-Forwards: 70.
Content-Length: 206.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Type: application/sdp.
.
v=0.
o=- 53655765 2353687637 IN IP4 10.0.4.29.
s=-.
c=IN IP4 10.0.4.29.
t=0 0.
m=audio 20042 RTP/AVP 0 18 8.
a=rtpmap:0 PCMU/8000.
a=rtpmap:18 g729/8000.
a=rtpmap:8 pcma/8000.
a=sendrecv.
a=direction:both.


U 10.0.4.29:5060 -> 10.0.4.29:5062
INVITE sip:10.0.4.29:5062;transport=udp SIP/2.0.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK9a49.7398b582.0.
To: <sip:1002#15122033884@10.0.4.176>;tag=2030F6E3-57CEB9600007EFB1-5E9E9700.
From: <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0017.
CSeq: 2 INVITE.
Call-ID: 17-29858@10.0.2.225.
Max-Forwards: 70.
Content-Length: 131.
Contact: <sip:209.105.251.200;did=574.50494f3>.
Content-Type: application/sdp.
.
v=0.
o=user1 53655765 2353687637 IN IP4 10.0.2.225.
s=-.
c=IN IP4 10.0.2.225.
t=0 0.
m=audio 6000 RTP/AVP 0.
a=rtpmap:0 PCMU/8000.


U 209.105.251.200:5060 -> 10.0.4.29:5062
SIP/2.0 100 Giving a try.
Via: SIP/2.0/UDP 10.0.4.29:5062;received=10.0.4.29;branch=z9hG4bKdBERjang;rport=5062.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=54C36D69-57CEB9610007EF08-670EA700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=32336SIPpTag0120.
CSeq: 11 INVITE.
Call-ID: 0367FB70-57CEB9610007EF0A-670EA700.
Content-Length: 0.
.


U 209.105.251.200:5060 -> 10.0.4.29:5060
SIP/2.0 100 Giving a try.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bKca49.a01809.0.
To: <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0017.
From: <sip:service@209.105.251.200:5060>;tag=2030F6E3-57CEB9600007EFB1-5E9E9700.
CSeq: 1 INVITE.
Call-ID: 17-29858@10.0.2.225.
Content-Length: 0.
.


U 10.0.4.29:5062 -> 10.0.4.29:5060
SIP/2.0 100 Trying.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK9a49.7398b582.0.
To: <sip:1002#15122033884@10.0.4.176>;tag=2030F6E3-57CEB9600007EFB1-5E9E9700.
From: <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0017.
CSeq: 2 INVITE.
Call-ID: 17-29858@10.0.2.225.
Content-Length: 0.
.


U 10.0.4.29:5062 -> 209.105.251.200:5060
INVITE sip:209.105.251.200;did=2.4d58765 SIP/2.0.
Via: SIP/2.0/UDP 10.0.4.29:5062;branch=z9hG4bKX7l.MaKp;rport.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=173A383B-57CEB9600007F0FF-672EC700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=32336SIPpTag0119.
CSeq: 11 INVITE.
Call-ID: 1E41A8CA-57CEB9600007F101-672EC700.
Max-Forwards: 70.
Supported: timer.
Session-Expires: 1800.
Min-SE: 90.
Content-Type: application/sdp.
Contact: <sip:10.0.4.29:5062;transport=udp>.
Content-Length: 206.
.
v=0.
o=- 53655765 2353687637 IN IP4 10.0.4.29.
s=-.
c=IN IP4 10.0.4.29.
t=0 0.
m=audio 20040 RTP/AVP 0 18 8.
a=rtpmap:0 PCMU/8000.
a=rtpmap:18 g729/8000.
a=rtpmap:8 pcma/8000.
a=sendrecv.
a=direction:both.


U 209.105.251.200:5060 -> 10.0.4.29:5062
SIP/2.0 100 Giving a try.
Via: SIP/2.0/UDP 10.0.4.29:5062;received=10.0.4.29;branch=z9hG4bKX7l.MaKp;rport=5062.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=173A383B-57CEB9600007F0FF-672EC700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=32336SIPpTag0119.
CSeq: 11 INVITE.
Call-ID: 1E41A8CA-57CEB9600007F101-672EC700.
Content-Length: 0.
.


U 209.105.251.200:5060 -> 10.0.4.29:5060
SIP/2.0 408 Request Timeout.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK3c6f.4b0fc555.0.
To: <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0018.
From: <sip:service@209.105.251.200:5060>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
CSeq: 1 INVITE.
Call-ID: 18-29858@10.0.2.225.
Content-Length: 0.
.


U 209.105.251.200:5060 -> 10.0.4.29:5062
SIP/2.0 408 Request Timeout.
Via: SIP/2.0/UDP 10.0.4.29:5062;received=10.0.4.29;branch=z9hG4bKdBERjang;rport=5062.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=54C36D69-57CEB9610007EF08-670EA700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=32336SIPpTag0120.
CSeq: 11 INVITE.
Call-ID: 0367FB70-57CEB9610007EF0A-670EA700.
Content-Length: 0.
.


U 209.105.251.200:5060 -> 10.0.4.29:5060
SIP/2.0 408 Request Timeout.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bKca49.a01809.0.
To: <sip:14054104980@10.0.2.225:5060>;tag=29858SIPpTag0017.
From: <sip:service@209.105.251.200:5060>;tag=2030F6E3-57CEB9600007EFB1-5E9E9700.
CSeq: 1 INVITE.
Call-ID: 17-29858@10.0.2.225.
Content-Length: 0.
.


U 209.105.251.200:5060 -> 10.0.4.29:5062
SIP/2.0 408 Request Timeout.
Via: SIP/2.0/UDP 10.0.4.29:5062;received=10.0.4.29;branch=z9hG4bKX7l.MaKp;rport=5062.
From: 14054104980 <sip:14054104980@209.105.251.200>;tag=173A383B-57CEB9600007F0FF-672EC700.
To: "1002#15122033884" <sip:1002#15122033884@10.0.4.176>;tag=32336SIPpTag0119.
CSeq: 11 INVITE.
Call-ID: 1E41A8CA-57CEB9600007F101-672EC700.
Content-Length: 0.
.


U 10.0.4.29:5062 -> 10.0.4.29:5060
SIP/2.0 408 Request Timeout.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK9a49.7398b582.0.
To: <sip:1002#15122033884@10.0.4.176>;tag=2030F6E3-57CEB9600007EFB1-5E9E9700.
From: <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0017.
CSeq: 2 INVITE.
Call-ID: 17-29858@10.0.2.225.
Content-Length: 0.
.


U 10.0.4.29:5062 -> 10.0.4.29:5060
SIP/2.0 408 Request Timeout.
Via: SIP/2.0/UDP 10.0.4.29:5060;branch=z9hG4bK0c6f.55012202.0.
To: <sip:1002#15122033884@10.0.4.176>;tag=214380BA-57CEB9610007EDCD-5E4E4700.
From: <sip:14054104980@209.105.251.200>;tag=29858SIPpTag0018.
CSeq: 2 INVITE.
Call-ID: 18-29858@10.0.2.225.
Content-Length: 0.
.

**Comment by 46labs** [comment] 2016-09-06 13:59
FYI, the 408 RTO was the last message sent or received by this node.

**Comment by razvancrainea** [comment] 2016-09-06 14:41
Hi, Trevor!

Checking the logs and the trace, I noticed the following events:

12:41:06 - call was established
12:42:13 - re-invites are sent out and 100 Trying is received
12:42:43 - GW replies with 408 - Request Timeout - at this moment the dialog is dropped

I am not sure what is the expected behavior, but to me everything looks fine. You argued that OpenSIPS does not send a BYE at 12:42:43? If so, the reason is simple - since the endpoints timed out, this means that they are no longer accessible - therefore if they didn't receive the INVITE, they won't receive the BYE either.

Let me know if I am missing something here.

Best regards,
Răzvan

**Comment by bogdan-iancu** [comment] 2016-09-30 07:57
Hi @46labs , if you have any updates or feedback, please reopen this ticket. I will close it for the moment as the report (as it is now) is invalid.

**Closed by bogdan-iancu** 2016-09-30 07:57 UTC
Labels: bug, invalid
