### ISSUE TITLE
Variables overflow in 2.3

### ISSUE THREAD

**Issue by nikbyte** [OpenSIPS/opensips#1253] opened 2018-01-15 19:53 UTC
Integers more than 2147483648 overflows in JSON module.
For example
$json(test/int) = 5122031234 will result in
{"int":827063938}

or

$json(test/int) = 2147483649 will result in
{"int":-2147483647}

Addition:
it looks like the same behaviour for all variables in opensips. :(

**Comment by bogdan-iancu** [comment] 2018-01-31 17:32
Hi @nikbyte , by design, all variables in OpenSIPS can hold strings or integers (32 bits). Nothing more.
So, it is not a bug, but a design limitation.

**Comment by nikbyte** [comment] 2018-02-01 04:11
Thank you for the explanation. Let's keep this as feature request?

**Comment by bogdan-iancu** [comment] 2018-02-01 09:07
I will close this one. In the mean while, take a look at the math module - http://www.opensips.org/html/docs/modules/2.3.x/mathops.html - this may allow you to operate with large numbers (as strings).
If you still consider, open a feature request.

**Closed by bogdan-iancu** 2018-02-01 09:07 UTC
