### ISSUE TITLE
opensips openssl 

### ISSUE THREAD

**Issue by volga629** [OpenSIPS/opensips#1324] opened 2018-03-29 14:48 UTC
Opensips last git  2.4 is crashing 

````
Mar 29 10:24:27 canldev01-fedora27 kernel: opensips[7208]: segfault at 7f1d7441e720 ip 00007f1d71eebe46 sp 00007fffd7377310 error 4 in libcrypto.so.1.1.0g[7f1d71d8f000+25c000]


Mar 29 10:24:27 canldev01-fedora27 systemd-coredump[7211]: Process 7208 (opensips) of user 973 dumped core.#012#012Stack trace of thread 7208:#012#0  0x00007f1d71eebe46 ossl_init_thread_stop (libcrypto.so.1.1)#012#1  0x00007f1d71eec07d OPENSSL_cleanup (libcrypto.so.1.1)#012#2  0x00007f1d784a71d8 __run_exit_handlers (libc.so.6)#012#3  0x00007f1d784a722a exit (libc.so.6)#012#4  0x00007f1d78490f31 __libc_start_main (libc.so.6)#012#5  0x000055ac2487cd4a _start (opensips)

````

````
[root@canldev01-fedora27 ~]# rpm -qa | grep opensips
opensips-tls_mgm-2.4.3.0d494e5e6-11.fc27.x86_64
opensips-proto_tls-2.4.3.0d494e5e6-11.fc27.x86_64
opensips-debuginfo-2.4.3.0d494e5e6-11.fc27.x86_64
opensips-debugsource-2.4.2.79418dce9-11.fc27.x86_64
opensips-2.4.3.0d494e5e6-11.fc27.x86_64
opensips-tls_mgm-debuginfo-2.4.3.0d494e5e6-11.fc27.x86_64
opensips-proto_tls-debuginfo-2.4.3.0d494e5e6-11.fc27.x86_64

````

````
[root@canldev01-fedora27 ccpp-2018-03-10-13:13:06.967780-1295]# gdb coredump
GNU gdb (GDB) Fedora 8.0.1-36.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
[New LWP 1295]
Missing separate debuginfo for the main executable file
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/1b/5993c2153e6935dc911e12680da501ed58f1fe
Core was generated by `/usr/sbin/opensips -P /run/opensips/opensips.pid -f /etc/opensips/opensips.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0094245e46 in ?? ()
"/var/spool/abrt/ccpp-2018-03-10-13:13:06.967780-1295/coredump" is a core file.
Please specify an executable to debug.
(gdb) bt
#0  0x00007f0094245e46 in ?? ()
#1  0x00000000ffffffff in ?? ()
#2  0x00007f009424607d in ?? ()
#3  0x00000000ffffffff in ?? ()
#4  0x00007f009a9596f8 in ?? ()
#5  0x0000000000000001 in ?? ()
#6  0x00007f009a5b7b58 in ?? ()
#7  0x0000000000000001 in ?? ()
#8  0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x00007f0094245e46 in ?? ()
No symbol table info available.
#1  0x00000000ffffffff in ?? ()
No symbol table info available.
#2  0x00007f009424607d in ?? ()
No symbol table info available.
#3  0x00000000ffffffff in ?? ()
No symbol table info available.
#4  0x00007f009a9596f8 in ?? ()
No symbol table info available.
#5  0x0000000000000001 in ?? ()
No symbol table info available.
#6  0x00007f009a5b7b58 in ?? ()
No symbol table info available.
#7  0x0000000000000001 in ?? ()
No symbol table info available.
#8  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) 

````

**Comment by bogdan-iancu** [comment] 2018-03-29 16:59
@volga629 , if you have OpenSIPS installed from packages, be sure you install also the package with the debug symbols, so you can get a more meaningful backtrace

**Comment by razvancrainea** [comment] 2018-04-23 08:15
This is actually a duplicate of #1304. Closing it now, will send further information on that ticket.

**Closed by razvancrainea** 2018-04-23 08:15 UTC
