### ISSUE TITLE
debug_mode and log_level=4 are not working in centos 7.2 

### ISSUE THREAD

**Issue by mvenkatesh431** [OpenSIPS/opensips#1003] opened 2016-12-15 15:38 UTC
Hi all,

  I am using OpenSIPS on centos 7.2. When I try to enable the debug mode it is not working.
I tried with following options
**log_level=4
debug_mode=1**

Both are not working. When I enable debug using debug_mode=1 OpenSIPS is not starting.

OpenSIPS version : 
version: opensips 2.3.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, QM_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
git revision: 3187c51
main.c compiled on 10:27:48 Dec 15 2016 with gcc 4.8.5

**Comment by razvancrainea** [comment] 2016-12-15 16:36
Did you check your system logs? Are there any errors related to opensips?

**Comment by mvenkatesh431** [comment] 2016-12-15 16:49
OpenSIPS is not starting if i set debug_mode=1

Here is the log  : 

Dec 15 11:45:36 webrtcdemo systemd: Starting SYSV: OpenSIPS is a fast SIP Server....
Dec 15 11:45:36 webrtcdemo opensips: Starting opensips:
Dec 15 11:45:36 webrtcdemo systemd: opensips.service: control process exited, code=exited status=1
Dec 15 11:45:36 webrtcdemo systemd: Failed to start SYSV: OpenSIPS is a fast SIP Server..
Dec 15 11:45:36 webrtcdemo systemd: Unit opensips.service entered failed state.
Dec 15 11:45:36 webrtcdemo systemd: opensips.service failed.

and If i use log_level=4 it is not giving all debug messages.

**Comment by razvancrainea** [comment] 2016-12-16 08:12
Can you set in your configuration file `log_stderror=yes` and start it from cli, like `opensips -f opensips.cfg`?

**Comment by mvenkatesh431** [comment] 2016-12-19 09:38
It is working if I start from the CLI. Debug_mode=1 also working.

**Comment by razvancrainea** [comment] 2016-12-19 10:08
Did you check if OpenSIPS is running after you get that message? Also, what `opensips.service` file are you using?

**Comment by mvenkatesh431** [comment] 2016-12-20 12:28
OpenSIPS is working as excepted if I start from the CLI, But if I enable debug_mode=1 and start the server using /etc/init.d/opensips start it is not starting.

Also log_leve=4 is also not working if i start the opensips from the init script.

Here is the init.d script i am using 
[opensips_init file.txt](https://github.com/OpenSIPS/opensips/files/663664/opensips_init.file.txt)

**Comment by razvancrainea** [comment] 2016-12-20 12:38
I am not sure I understand your report: how does `debug_mode` or `log_level` influence OpenSIPS start? can you detail a bit? For example, if you don't set `debug_mode=1`, and start OpenSIPS using `/etc/init.d/opensips start`, is it working? Or it is not working from `/etc/init.d/opensips` no matter what value you set for those parameters.

When it is not working, do you see anything in the system log? Also, can you run `/usr/sbin/opensips -V` and `opensips -V`?

**Comment by mvenkatesh431** [comment] 2016-12-20 13:33
If i don't set the `debug_mode=1` then OpenSIPS is starting fine with the `/etc/init.d/opensips start`.
It is not working if i set the debug_mode=1 in opensips.cfg and start it from the init.d script.

Also` log_level=4 `also not giving any Debug messages if I start from the init.d script.

The only case opensips is not starting is if I enable the` debug_mode=1 `and start the opensips using init.d script. remaining cases it is working fine. 

```
opensips -V
version: opensips 2.2.2 (x86_64/linux)
```

I also tried it with git master branch, Same thing happened there also. 
It is only happening in CentOS 7, I tried it in Ubuntu it is working fine.

I can't see any errors in syslog file, Here is the log of OpenSIPS if I set the debug_mode=1 and start the server

```
Dec 20 07:24:16 test systemd: Starting SYSV: OpenSIPS is a fast SIP Server....
Dec 20 07:24:16 test opensips: Starting opensips:
Dec 20 07:24:16 test systemd: opensips.service: control process exited, code=exited status=1
Dec 20 07:24:16 test systemd: Failed to start SYSV: OpenSIPS is a fast SIP Server..
Dec 20 07:24:16 test systemd: Unit opensips.service entered failed state.
Dec 20 08:01:01 test systemd: Starting Session 118 of user root.
Dec 20 08:01:01 test systemd: Started Session 118 of user root.
Dec 20 08:29:58 test systemd: Starting SYSV: OpenSIPS is a fast SIP Server....
Dec 20 08:29:58 test opensips: Starting opensips:
Dec 20 08:29:58 test systemd: opensips.service: control process exited, code=exited status=1
Dec 20 08:29:58 test systemd: Failed to start SYSV: OpenSIPS is a fast SIP Server..
Dec 20 08:29:58 test systemd: Unit opensips.service entered failed state.

```

**Comment by razvancrainea** [comment] 2016-12-20 14:02
I tried to run this on CentOS 7.2 and indeed, if I set the `debug_mode` to `yes`, OpenSIPS does not start.
However, if you take a look at the logs (`journalctl -xe`), you'll noticed the problem:
```
ERROR:core:do_suid: failed to change owner of pid file /var/run/opensips/opensips.pid: No such file
```
So basically the problem is that CentOS looks for a pidfile. However, in `debug_mode`, OpenSIPS does not generate this file, because there is only a single process running, and it is attached to the console.

After thinking about it, `debug_mode` doesn't really make sense when starting OpenSIPS through `/etc/init.d/opensips` because of several reasons:
* the process remains attached to the console, so you can simply close it by `CTRL ^C`.
* the standard error is not printed, so you won't get any logs.

Therefore, `debug_mode` only makes sense when starting OpenSIPS directly, run some tests to debug a problem, then close it and start it properly as a daemon.

Regarding setting `log_level=4`, are you sure you are looking at logs properly? Did you try checking the logs using journalctl?

**Comment by mvenkatesh431** [comment] 2016-12-20 14:51
Thanks, Răzvan, I will use `debug_mode=1 ` on the console.

Regarding `log_level=4 `, It's is not giving all debug messages, I checked in journalctl also.

**Comment by bogdan-iancu** [comment] 2017-01-25 15:34
@mvenkatesh431 , everything is clear here, or there are things to be clarified ?

**Closed** 2017-01-30 22:57 UTC
Labels: invalid
