### ISSUE TITLE
[BUG] Possibility of duplicate key error in activewatcher table

### ISSUE THREAD

**Issue by wdoekes** [OpenSIPS/opensips#1722] opened 2019-06-04 09:43 UTC
*Forked from ticket #1662, which explains the problem and listed three fixes:*

* [x] To-tag collisions
* [x] The constraint
* [x] Don't stop processing on single row failure

Two of those were fixed. This ticket concerns the discepancy between _in-memory handling_ of duplicate activewatcher (silently adding more) records and the _DB handling_ (rejecting with duplicate key error).

According to the ticket, we should fix that the in-memory representation of a subscription should never create duplicates:

> The second is about the constraint - which I think it is good to have, at DB and code level. You cannot have 2 different subscription within the same SIP dialog (to_tag, from_tag, callid). So, if another SUBSCRIBE is received with the same dialog ID, it should overwrite the existing one.

**Solution**

- Overwrite in-memory representation of duplicate activewatchers (same to_tag, from_tag, callid).
- Take care so the DB version is overwritten too.

**Comment by bogdan-iancu** [comment] 2019-06-14 10:51
@wdoekes , take a look at the above commit - it should address the pending issue. If you can double check / run some testing, it will be great !

**Comment by bogdan-iancu** [comment] 2019-06-21 16:15
Ok, the ec1889638a9d43280ba1362f6108a175efd4a854 patch introduced a problem (reported by @danpascu), so I reverted for the moment - I will take the time to come up with a better solution.

**Comment by bogdan-iancu** [comment] 2019-07-08 12:22
yeah, still on my todo list, to find a solution to the hen-and-egg problem that was present into the previous fix :P

**Comment by wdoekes** [comment] 2019-07-08 12:56
Yea. I haven't gotten around to taking a proper look either. Thanks for keeping it alive :)

**Comment by bogdan-iancu** [comment] 2019-08-01 16:00
@wdoekes, the problem with the reverted commit is how the To-tag is generated. 
My "fix" was to move the insertion (of the subscription) into the hash **before** sending back any reply - by doing this, I can test the collision and return a proper reply.
But the problem is that the To-tag (needed for checking the hash) is generated by the function sending the reply, which (with my commit) is triggered **after** the hash check :( .

So the dilemma is : how to build the To-tag (needed for hash check) without sending the SIP reply ? Doing the hash check after sending the reply doesn't help too much :P

**Comment by bogdan-iancu** [comment] 2019-11-08 16:32
A possible fix (which I favor) is to split the `to-tag` generation and reply sending from the same function. The presence module will do:
* generate a new UAS side tag (the `to-tag`)
* check the subscription hash table for collisions and add into the hash (if collision, send a negative reply)
* send the 200 OK reply for the subscription by using the already generated `to-tag`

**Comment by wdoekes** [comment] 2019-11-11 13:39
Sounds good.

Something like this, as addition to your original ec188963 then?
```
        else
        {
-               if(msg && send_2XX_reply(msg, reply_code, subs->expires, &subs->to_tag,
-                       &subs->local_contact)<0)
-               {
-                       LM_ERR("sending 2XX reply\n");
-                       goto error;
-               }
+               // - calc_tag_suffix
+               // - append to totag_prefix (module-specific?)
+               // - put result in &subs->to_tag
+               // - put result in msg and re-parse msg->to (so 
 
                if(subs->expires!= 0)
...
+               if(msg && send_2XX_reply(msg, reply_code, subs->expires, 0,
+                       &subs->local_contact)<0)
```

**Comment by bogdan-iancu** [comment] 2019-11-19 16:26
Yup, something like that. I hope to get some time in the next days to rework the "signaling" API to expose a `generate_totag()` function.

**Comment by bogdan-iancu** [comment] 2019-11-23 20:31
Hi @wdoekes , could you do some testing (on head) with my latest changes? this should fully solve the problem ;)

**Comment by wdoekes** [comment] 2019-11-25 08:17
Awesome. We're on it.

**Comment by bogdan-iancu** [comment] 2020-01-08 15:42
Thanks @wdoekes , just let me know the result, so I can do the backport and close here.

**Comment by wdoekes** [comment] 2020-01-09 15:43
Hi! Sorry about the delay. I finally got around updating my test setup and fixing it up to handle opensips 3.1.

I hacked tags.h to trigger the dupes:
```
--- a/tags.h
+++ b/tags.h
@@ -66,6 +66,8 @@ static inline void calc_tag_suffix( struct sip_msg *msg, char *tag_suffix)
 	if (msg->via1->branch)
 		suffix_source[ss_nr++]=msg->via1->branch->value;
 	MD5StringArray( tag_suffix, suffix_source, ss_nr );
+/* block the last 31 chars of the md5 */
+memcpy(tag_suffix + 1, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 31);
 }
 
 inline static void init_tags( char *tag, char **suffix,
```

Before your changeset:
```
INFO:presence:update_subscription: notify                                      
INFO:presence:send_notify_request: NOTIFY sip:user@host via sip:xxx on behalf of sip:user@host for event dialog, to_tag=513c-5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, cseq=1
INFO:presence:update_subscription: notify                                      
INFO:presence:send_notify_request: NOTIFY sip:user@host via sip:xxx on behalf of sip:user@host for event dialog, to_tag=513c-0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, cseq=1
CRITICAL:db_mysql:wrapper_single_mysql_stmt_execute: driver error (1062): Duplicate entry 'sip:user@host for key 'presentity_uri'
ERROR:presence:insert_subs_db: unsuccessful sql insert                         
ERROR:presence:update_subscription: failed to insert subscription in database  
ERROR:presence:handle_subscribe: in update_subscription                        
```
(without any response)

After:
```
INFO:presence:send_notify_request: NOTIFY sip:user@host via sip:xxx on behalf of sip:user@host for event dialog, to_tag=513c-fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, cseq=1
INFO:presence:send_notify_request: NOTIFY sip:user@host via sip:xxx on behalf of sip:user@host for event dialog, to_tag=513c-5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, cseq=1
INFO:presence:send_notify_request: NOTIFY sip:user@host via sip:xxx on behalf of sip:user@host for event dialog, to_tag=513c-exxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, cseq=1
ERROR:presence:update_subscription: subscription overlapping detected, rejecting
ERROR:presence:handle_subscribe: in update_subscription                        
```
(and with a nice 500 Server Internal Error)

And the records that were acknowledged were also found in the DB. Looking all good :ok_hand: 

_On a related note:_

I see you replaced an `LM_INFO("notify\n")` with an `LM_DBG` there too. As far as I'm concerned, the one in handle_expired_subs can go too, as the `handle_expired_subs` calls `send_notify_request` too, which has its own useful info.
```
# git show 4918544248c495b1099a54326f97a82df97bbe76 | grep LM_INFO -A2
-	LM_INFO("notify\n");
+
+	LM_DBG("send NOTIFY's out\n");
```
```patch
--- a/modules/presence/subscribe.c
+++ b/modules/presence/subscribe.c
@@ -1307,7 +1307,7 @@ int handle_expired_subs(subs_t* s)
                s->reason.len= 7;
                s->expires= 0;
 
-               LM_INFO("notify\n");
+               LM_DBG("send NOTIFY's out\n");
                if(send_notify_request(s, NULL, NULL, 1, NULL, 0)< 0)
                {
                        LM_ERR("send Notify not successful\n");
```

**Comment by bogdan-iancu** [comment] 2020-01-10 10:37
Thank you @wdoekes , I included your change of the log line. 
The backports to 3.0 and 2.4 were done, finally closing here :)

**Closed by bogdan-iancu** 2020-01-10 10:37 UTC
Labels: bug, fixed
