### ISSUE TITLE
[BUG] Call Pickup using events not working

### ISSUE THREAD

**Issue by flaviogoncalves** [OpenSIPS/opensips#2330] opened 2020-12-04 09:34 UTC
**OpenSIPS version you are running**

```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```

**Describe the bug**

The example of call pickup using event routing is not working. In the event routing,  we got the message

ERROR:registrar:lookup: bad DUMMY request (missing Call-ID header)

in the section:

route[handle_pickup]
{
    xlog("call picked by $avp(picker), fetching its contacts\n");
    if (lookup("location","", "$avp(picker)")) {
        # take the contacts retured by lookup() (for Charlie)
        # and inject them into the original call, but also cancel
        # any existing ongoing branch (ringing to Bob)
        t_inject_branches("msg","cancel");
    }
}

of the example:

https://opensips.org/html/docs/modules/3.1.x/event_routing.html#idp30714736

**To Reproduce**

To make it work I have commented the following section of the file /lib/reg/lookup.c line 68

        /*if (!req->callid) {
                LM_ERR("bad %.*s request (missing Call-ID header)\n",
                       req->REQ_METHOD_S.len, req->REQ_METHOD_S.s);
                return -1;
        }*/

**Comment by bogdan-iancu** [comment] 2020-12-11 07:37
@flaviogoncalves, not sure what is the  exact purpose of that check, but I just pushed a fix (on 3.2/master for the moment) that exposes a completely, well formed SIP msg to be used in script routes which are not triggered by real SIP msg. I will give it a bit of  time on master before backporting as fix to 3.1 and 3.0.

**Comment by liviuchircu** [comment] 2020-12-11 10:08
@bogdan-iancu and @flaviogoncalves:  it seems I added that Call-ID check in commit 0b7d4d1fa27, in order to provide the Call-ID of the pending INVITE during the Push Notification event route, so you can `load_dlg_ctx()` using this Call-ID and work with the INVITE data during the event route's DUMMY msg.  However, a better solution would be to just provide a `NULL` Call-ID during the event, if the SIP request does not have a Call-ID, rather than stopping `lookup()` prematurely -- I'll change it soon.

Cheers!

**Comment by bogdan-iancu** [comment] 2020-12-11 11:42
@liviuchircu , keep the check, there is no issue with it - my question was more rhetorical. With the fix on the dummy SIP message, the check will be just fine.

**Comment by liviuchircu** [comment] 2020-12-11 11:47
Unfortunately, I think backporting that check to `3.1` is actually a regression.  Any opensips scripts which were using `lookup()` from a non-SIP route and were working before, would have stopped working after I added the check.  Besides, the `NULL` value of the event parameter is completely fine (registration refresh PN events set it to `NULL` already).

**Comment by bogdan-iancu** [comment] 2020-12-11 11:54
@flaviogoncalves , I just backported to 3.1 the fix for proper dummy sip message (including for event routes), see ece775ae97001604931ed96de3873a0436a7fc94, 2a396d15427136839d4533a8c13d1f31fa56bbf, a5854b407c76b0f87d0c644ead843abfce80ddfc, 2e9e31b69bf4483f080804b85bc438d0ad592211, 9c748b16a5cbd4ad7c93807ad122ede868c1c505, 8df69e94d8f5b12f730d3f0964e613435c4fbd4d
Could you please test latest 3.1 to see if the problem is solved?

**Comment by bogdan-iancu** [comment] 2021-01-08 15:47
@flaviogoncalves , any update here ?

**Comment by bogdan-iancu** [comment] 2021-01-13 12:49
more testing done, also backported to 2.4, closing here

**Closed by bogdan-iancu** 2021-01-13 12:49 UTC
Labels: bug, fixed
