### ISSUE TITLE
CRITICAL:presence:update_presentity

### ISSUE THREAD

**Issue by michelep** [OpenSIPS/opensips#578] opened 2015-07-22 06:56 UTC
CRITICAL:db_mysql:db_mysql_submit_query: too many mysql server reconnection failures
Jul 22 05:02:07 proxy-voip01 /usr/sbin/opensips[1037]: ERROR:core:db_do_update: error while submitting query
Jul 22 05:02:07 proxy-voip01 /usr/sbin/opensips[1037]: ERROR:presence:update_presentity: updating published info in database
Jul 22 05:02:07 proxy-voip01 /usr/sbin/opensips[1037]: CRITICAL:presence:update_presentity: #012>>> pkg_free() on non-pkg ptr 0xb6afc680 - aborting!#012#012It seems you have hit a programming bug.#012Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
Jul 22 05:02:07 proxy-voip01 /usr/sbin/opensips[1048]: CRITICAL:core:receive_fd: EOF on 11
Jul 22 05:02:07 proxy-voip01 /usr/sbin/opensips[936]: INFO:core:handle_sigs: child process 1037 exited by a signal 6
Jul 22 05:02:07 proxy-voip01 /usr/sbin/opensips[936]: INFO:core:handle_sigs: core was not generated
Jul 22 05:02:07 proxy-voip01 /usr/sbin/opensips[936]: INFO:core:handle_sigs: terminating due to SIGCHLD

**Comment by michelep** [comment] 2015-07-22 07:30
This is Opensips 1.11.5 from Debian Jessie repository

**Comment by lanticezdd** [comment] 2016-01-20 02:33
I'm getting the same error in opensips-2.1.1 from CentOS 7 repository:

Jan 19 18:31:43 [20] CRITICAL:db_mysql:db_mysql_submit_query: too many mysql server reconnection failures
Jan 19 18:31:43 [20] ERROR:core:db_do_update: error while submitting query
Jan 19 18:31:43 [20] ERROR:presence:update_presentity: updating published info in database
Jan 19 18:31:43 [20] CRITICAL:presence:update_presentity:
>>> pkg_free() on non-pkg ptr 0x7f825d7734c0 - aborting!

It seems you have hit a programming bug.
Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues

Jan 19 18:31:43 [24] CRITICAL:db_mysql:db_mysql_submit_query: too many mysql server reconnection failures
Jan 19 18:31:43 [24] ERROR:core:db_do_update: error while submitting query
Jan 19 18:31:43 [24] ERROR:presence:update_presentity: update_presentity:
>>> pkg_free() on non-pkg ptr 0x7f825d7734c0 - aborting!

It seems you have hit a programming bug.
Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues

**Comment by bogdan-iancu** [comment] 2016-03-20 13:32
This is duplicate of #816

**Closed by bogdan-iancu** 2016-03-20 13:32 UTC
