### ISSUE TITLE
[BUG] OpenSIPS stops to register new users auth_db:get_ha1 is not working after some time. 

### ISSUE THREAD

**Issue by flaviogoncalves** [OpenSIPS/opensips#2752] opened 2022-02-13 14:47 UTC
Thank you for reporting a bug in OpenSIPS!

```
version: opensips 3.2.4 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 50407d340
main.c compiled on 18:06:01 Jan 18 2022 with gcc 8
```

**Describe the bug**
When the server is restarted, I'm able to register, after some random time, the registration stops working and I start to get the following error:

CRITICAL:db_mysql:wrapper_single_mysql_stmt_execute: driver error (4031): The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.
Feb 13 14:16:39 ip-172-31-92-129 /usr/sbin/opensips[12257]: ERROR:auth_db:get_ha1: failed to query database

**To Reproduce**
Just let the server inactive for some time the registration will stop. 

**Expected behavior**
The  registration should keep working 

**Relevant System Logs**
CRITICAL:db_mysql:wrapper_single_mysql_stmt_execute: driver error (4031): The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.
Feb 13 14:16:39 ip-172-31-92-129 /usr/sbin/opensips[12257]: ERROR:auth_db:get_ha1: failed to query database

**OS/environment information**
 - Operating System: Debian 10 
 - OpenSIPS installation:  Compiled
 - mysql  Ver 8.0.27 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by kworm83** [comment] 2022-02-19 19:31
Looks like this was fixed by @vladpaiu with commit cde6757 a few weeks ago and has not been back-ported.

@vladpaiu can this fix be back-ported to 3.2.x and 3.1.x LTS releases?

**Comment by liviuchircu** [comment] 2022-02-21 06:54
Hi all,

The MySQL 8.0 reconnect fix for error code 4031 has been backported down to `3.1` for quite some time now, and it will also make it into this week's round of minor releases.  So @flaviogoncalves: please try the fix, as advised by @kworm83, and if the issue is still there, just re-open this issue so we can re-evaluate.

**Closed by liviuchircu** 2022-02-21 06:54 UTC
Labels: outdated

**Comment by flaviogoncalves** [comment] 2022-02-21 11:17
Sorry, the late feedback, the patch has worked.

**Comment by bertrandNTT** [comment] 2022-04-27 12:57
Hi,

I've (almost) the same issue but on a opensips 3.1.7 (oracle 8) and with avp_db_query.

- mysql-8.0.26 (repo)
- opensips rpm repo installation

opensips -V
version: opensips 3.1.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 02:39:34 Dec 23 2021 with gcc 8

To Reproduce:
Same here, just let the server inactive for some time ...

Relevant system logs:
/usr/sbin/opensips[873953]: CRITICAL:db_mysql:wrapper_single_mysql_real_query: driver error (4031): The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.
Apr 27 10:45:32 edlosipsload /usr/sbin/opensips[873953]: ERROR:core:db_do_raw_query: error while submitting query
Apr 27 10:45:32 edlosipsload /usr/sbin/opensips[873953]: ERROR:avpops:db_query_avp: raw_query failed: db0(usr_preferences) select version()...

What the script is doing:
avp_db_query( "select version()" ); #version? to check if DB is up ... bypass userblacklist if mysql is down ...
$var(get_mysqld)=$retcode;
if ( $var(get_mysqld)== 1 )
 check_user_blacklist("$fU", "$var(star)", "$var(zero)") 

Let me know if should open a new case?
Maybe my packaged version is too old?
BR

**Comment by bogdan-iancu** [comment] 2022-05-02 13:58
Just do a `opensips -V` and see what you have there.

**Comment by bertrandNTT** [comment] 2022-05-09 14:03
I already provided the result of "`opensips -V`" in my previous comment.  => _**version: opensips 3.1.7 (x86_64/linux).**_
I've upgraded to **3.1.9** it seems fixed.
