### ISSUE TITLE
[CRASH] Segfault

### ISSUE THREAD

**Issue by palmtown** [OpenSIPS/opensips#2091] opened 2020-04-27 02:40 UTC
**OpenSIPS version you are running**

```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 7
```

**Describe the bug**

**To Reproduce**
Example:
1. Install opensips-mongodb-module via debs
2. Add loadmodule "cachedb_mongodb.so"
3. Inspect syslog
4. Notice the errors shown below.

**Expected behavior**
Opensips should have started up with MongoDB support.

**Relevant System Logs**
kernel: opensips[4287]: segfault at 10 ip 0000000000000010 sp 00007fffccaba608 error 14 in opensips[55976d848000+25f000]
kernel: opensips[4278]: segfault at 100000000 ip 00007f30f02f0c05 sp 00007fffccabad38 error 4 in libcrypto.so.1.1[7f30f0115000+29b000]
systemd[1]: opensips.service: Control process exited, code=dumped status=11
ystemd[1]: opensips.service: Failed with result 'core-dump'.

**OS/environment information**
 - Operating System: Ubuntu 18.04.4 LTS
 - OpenSIPS installation: debs
 - other relevant information:

**Additional context**

**Comment by palmtown** [comment] 2020-04-27 02:49
Hello there,

Just an update, based on further testing, I can only get the module to work if tls_mgm is not loaded.  Also, I have to disable tls, wss to avoid getting the error.

**Comment by vtzan** [comment] 2020-04-27 07:26
@palmtown Yes I had the same issue too. Its seems that whenever tls_mgm is loaded it creates more problems and instabilities. An update from the OpenSIPs Team would be useful.

I have opened https://github.com/OpenSIPS/opensips/issues/2087 regarding same issues when loading tls_mgm

Also I face some problems when loading cassandra + tls_mgm
 https://github.com/OpenSIPS/opensips/issues/2003 which seems to be fixed somehow right now but I keep investigating.

In the meantime I have disabled tls_mgm... :-(

**Comment by palmtown** [comment] 2020-04-27 11:38
Hello @vtzan 

Thanks for the additional information you provided.  I too faced both issues mentioned in #2087 and issue #2091.

**Comment by jalung** [comment] 2020-05-04 16:21
Hi, apply the patch below. I submitted a pull request for this in the past, but it was skipped. This line of code is attempting to free dynamic memory not held by old_buf. Variable old_buf declared as a simple pointer and points to a member inside a struct. pkg_free() is illegaly trying to free memory.  pkg_malloc() used to dynamically allocate memory for the same memory location but for a different object. That space cannot be freed at that point anyway because it contains the result rows of the query.  That allocated space is freed and the parent object destroyed later in the process. This bug seems to not crash and dump on some systems.
 
```
--- opensips/db/db_res.c	2017-11-22 13:30:58.000000000 +0000
+++ opensips/db/db_res.c	2018-03-17 20:50:07.000000000 +0000
@@ -200,8 +200,6 @@
 	       (char *)old_buf + old_rows * sizeof(db_row_t),
 	       old_rows * (sizeof(db_val_t) * RES_COL_N(_res)));
 
-	pkg_free(old_buf);

 	LM_DBG("allocate %d bytes for result rows and values at %p\n",
 		(int)(rows * (sizeof(db_row_t) + sizeof(db_val_t) * RES_COL_N(_res))),
 		RES_ROWS(_res));

```

**Comment by palmtown** [comment] 2020-05-04 16:29
Hello @jalung,

Thanks for your assistance.  @bogdan-iancu or anyone else would would be able to assist.  Can you please review and if validated apply the patch submitted by @jalung?  This one issue is causing several problems and blockers.

We are very appreciative of all the hard work you all have given to the project.  Thanks again @jalung

**Comment by palmtown** [comment] 2020-05-17 16:02
Hello Community,

@jalung submitted a patch, can we get this reviewed and included ASAP?

**Comment by rvlad-patrascu** [comment] 2020-05-24 22:00
Hi @palmtown,

Can you extract the backtrace from the core file for this crash?

**Comment by rvlad-patrascu** [comment] 2020-05-24 22:01
Hi @jalung,

As far as I can tell, there is no problem with the code that you pointed out. Have you experienced the same problem as described in this issue and that patch fixed it? If so, what lead you to believe that this specific piece of code is the issue?

**Comment by jalung** [comment] 2020-05-25 12:57
Hi @rvlad-patrascu , I have seen this crash in the log when using the cache_mongodb module, but in theory it, should also affect all the modules that rely on this function (db_realloc_rows). Below is a screen shot of the log when the patch is removed.

```
May  4 06:28:26 sips opensips[17398]: May  4 06:28:26 [17400] CRITICAL:core:db_realloc_rows:
May  4 06:28:26 sips opensips[17398]: >>> pkg_free() on non-pkg ptr (nil) - aborting!
May  4 06:28:26 sips opensips[17398]: It seems you have hit a programming bug.
May  4 06:28:26 sips opensips[17398]: Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues
May  4 06:28:26 mail abrt-hook-ccpp[17402]: Process 17400 (opensips) of user 0 killed by SIGABRT - dumping core
```

**Comment by rvlad-patrascu** [comment] 2020-05-26 19:17
@jalung Can you also post the backtrace from the core file? And does loading the tls_mgm module or not make any difference as others have mentioned ?

**Comment by jalung** [comment] 2020-05-26 22:21
I posted here because of the similarity of opensips crashing on startup using cachedb_mongodb. FYI: not seeing an issue loading tls_mgm and proto_tls. Using usrloc db_mode=3 to location  cachedb_mongodb.
```
version: opensips 2.3.6 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select
gcc.x86_64                                                    8.3.1
```

[core_backtrace.txt](https://github.com/OpenSIPS/opensips/files/4685135/core_backtrace.txt)

**Comment by rvlad-patrascu** [comment] 2020-05-29 14:17
@jalung This is quite strange. I guess you have some other custom patches applied (regarding the memory allocators), as the `pkg_free()` in question seems to crash on a `NULL` pointer, which should not happen. According to this log line that you've provided:
`May  4 06:28:26 sips opensips[17398]: >>> pkg_free() on non-pkg ptr (nil) - aborting!`
the crash happens [here](https://github.com/OpenSIPS/opensips/blob/2.3/mem/mem.h#L120), which is not possible as the pointer is checked to be not NULL in the [if statement](https://github.com/OpenSIPS/opensips/blob/2.3/mem/mem.h#L117) above.
As such, there is no reason to include the patch you posted in public code but nevertheless, the correct version in order not have a memory leak, should be:
```
-       pkg_free(old_buf);
+       if (old_buf)
+               pkg_free(old_buf);
```

**Comment by tyl0r** [comment] 2020-05-29 20:24
Hi @rvlad-patrascu, I'm having the same issue as @palmtown where the only way to load the cachedb_mongodb module is to first disable the tls_mgm module, otherwise opensips won't start. I'm not sure if the full backtrace I'm providing is complete or not but I hope it helps. Let me know if I can do some more debugging.

```
version: opensips 3.0.2 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8
```
```

**Comment by jalung** [comment] 2020-06-01 15:14
@rvlad-patrascu , seems strange that this has not been reported by others, but OpenSips also crashes using the vanilla 2.3.6 tarball in the identical manner. It has been such since version 2.3.0 after upgrading from 2.1.5. It has also crashed in the same way on incrementing versions of the underlying OS. Basic routing scripts have been tried, but the result has been the same. Other than that line of code, everything is pretty stable under current use. 

It also crashes the same way using the suggested code below. Obviously, old_buf is not null. I'm still inclined to believe the error message that that pointer is pointing to something not created by pkg_malloc().  
```
-       pkg_free(old_buf);
+       if (old_buf)
+               pkg_free(old_buf);
```

**Comment by rvlad-patrascu** [comment] 2020-06-02 12:14
HI @tyl0r,

Although I'm able to reproduce the crash myself when loading tls_mgm along with cachedb_mongodb, just to be sure it's the same thing, it would be best if you could produce a backtrace from an opensips binary with debugging symbols enabled (otherwise not much info can be extracted).

**Comment by rvlad-patrascu** [comment] 2020-06-02 13:08
@jalung Allow me to disagree. `old_buf` obviously **is** null the first time `db_realloc_rows` is called from [here](https://github.com/OpenSIPS/opensips/blob/2.3/modules/cachedb_mongodb/cachedb_mongodb_dbase.c#L1279). And this is undoubtedly confirmed by this part: `non-pkg ptr (nil)` of the error line that you've provided (see how that line is printed [here](https://github.com/OpenSIPS/opensips/blob/2.3/mem/mem.h#L119)). As such, unless you've changed the condition in that if statement I was referring to earlier, the crash seems impossible in this circumstances.
Maybe after applying the patch as I've suggested, that pointer gets corrupted in a different way some time later. Please provide a proper backtrace (`bt full` in `gdb`) in order to investigate further.

**Comment by rvlad-patrascu** [comment] 2020-06-12 16:45
I have just a pushed a fix for the cachedb_mongodb + tls_mgm crash. But I am waiting for a confirmation of the fix from anyone having this issue before closing this ticket though.

**Closed** 2020-07-14 15:18 UTC
Labels: bug, fixed
