### ISSUE TITLE
[BUG] TLS1.0 and 1.2 disabled when using mode SSLv23

### ISSUE THREAD

**Issue by telematico** [OpenSIPS/opensips#1986] opened 2020-02-27 21:42 UTC
**OpenSIPS version you are running**
version: opensips 2.4.7 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, F_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on  with gcc 8

```
```

**Describe the bug**

Hello:
When I configure TLS_MGM module to use the mode SSLv23, OpenSips only offers the protocols TLS1.2 and TLS1.3 (don't offer TLS1.0 or 1.1)
If I use the modes TLSv1 or TLSv1_2 It works as expected

**To Reproduce**
Only need to configure tls_mngm module on SSLv23 mode:
modparam("tls_mgm", "tls_method", "[tls]SSLv23")
and do a check with openssl:
openssl s_client -connect DOMAIN:5061 -tls1
openssl s_client -connect DOMAIN:5061 -tls1_1
openssl s_client -connect DOMAIN:5061 -tls1_2
openssl s_client -connect DOMAIN:5061 -tls1_3

**Expected behavior**
In SSLv23 OpenSips should offer all supported protocols, including TLS1.0 and 1.1 

**OS/environment information**
 - Operating System: Debian 10 
 - OpenSIPS installation:  installed from official APT repository
 - other relevant information: OpenSSL version is 1.1.1d  10 Sep 2019

**Comment by razvancrainea** [comment] 2020-02-28 10:16
I've just tested this and worked just fine.
Looking into the code I can confirm that OpenSIPS does not enforce any version when using `SSLv23`
Are you using OpenSIPS in server or client mode?

**Comment by telematico** [comment] 2020-02-28 13:06
Hi Razvan:

I´m using OpenSIPS in server mode.  I´ve tested with different versions of openssl client in Linux and mac. I can share (privately) my opensips public address just to check the TLS negotiation. If you don´t enforce any version, can be a restriction with OpenSSL 1.1.11d? Is the standard library on Debian 10

I tried with a very simple config and I still see the issue:

listen = tls:XXX.XXX.XXX.XXX:5061
loadmodule "proto_tls.so"
loadmodule "tls_mgm.so"
modparam("proto_tls", "tls_crlf_pingpong", 1)
modparam("proto_tls", "tls_max_msg_chunks", 8)
modparam("tls_mgm", "tls_handshake_timeout", 200)
modparam("tls_mgm", "tls_send_timeout", 50)
modparam("tls_mgm", "tls_method", "SSLv23")
#modparam("tls_mgm", "tls_method", "TLSv1")
modparam("tls_mgm", "certificate", "/etc/opensips/XXXXXX.crt")
modparam("tls_mgm", "private_key", "/etc/opensips/XXXX.key")
modparam("tls_mgm", "ca_list", "/etc/opensips/CAlist.crt")
modparam("tls_mgm", "require_cert", "0")
modparam("tls_mgm", "verify_cert", "1")


When I try with openssl or with a SIP phone (Cisco SPA508G)  I get in logs:

 ERROR:proto_tls:tls_accept: New TLS connection from 10.8.8.69:11905 failed to accept
 ERROR:proto_tls:tls_print_errstack: TLS errstack: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol
ERROR:proto_tls:tls_read_req: failed to do pre-tls reading

Here are my tests using openssl client:

bad handshake:

openssl s_client -connect MY_HOST:5061 -tls1
CONNECTED(00000005)
4654354028:error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/ssl/ssl_pkt.c:1200:SSL alert number 70
4654354028:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/ssl/ssl_pkt.c:585:

no peer certificate available

No client certificate CA names sent

SSL handshake has read 7 bytes and written 0 bytes

New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Start Time: 1582891711
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)


good handshake:

openssl s_client -connect MY_OPENSIPS:5061 -tls1_2
CONNECTED(00000005)
depth=3 C = XX, O = XXXXXXXX, OU = XXXXXXXXXXXXX, CN = XXXXXXXXXXXXXXXXXXXX
verify return:1
depth=2 C = XX, ST = XXXXXXXXX, L = XXXXXXX, O = XXXXXXXXXXX Network, CN = XXXXXXXXXXX
verify return:1
depth=1 C = XX, ST = XXXXXXXX, L = XXXXXXX, O = XXXXXXXXX, CN = XXXXXXXXXXXXXXXXX
verify return:1
depth=0 OU = XXXXXXXXXXXXX, OU = XXXXXXXXX, CN = XXXXXXXX
verify return:1

Certificate chain
MY_CERTIFICATE_CHAIN

Server certificate
-----BEGIN CERTIFICATE-----
MY_CERTIFICATE
-----END CERTIFICATE-----
subject=/OU=XXXXXXXXXX/OU=XXXXXXXXXXXX/CN=XXXXXXXXXXXXXXXXXX
issuer=/C=XX/ST=XXXXXXXXXXX/L=XXXXXXXXXX/O=XXXXXXXXXXX/CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits

SSL handshake has read 5262 bytes and written 289 bytes

New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: XXXXXX
    Session-ID-ctx:
    Master-Key: XXXXXXXXX
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
         XXXXXXXXXXX
         ............
        XXXXXXXXXXXX
    Start Time: 1582892476
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)

closed

**Comment by razvancrainea** [comment] 2020-02-28 16:45
could you run the `opensipsctl fifo tls_list` command and check the `METH` node in there?
If it corresponds to your config, can you share a PCAP? You can send it privately if you'd like.

**Comment by telematico** [comment] 2020-03-02 12:38
I´ll email you the PCAP and certifcates used.

the result of `tls_list` is the expected

**Comment by razvancrainea** [comment] 2020-03-05 08:24
I've tried to replicate this, but it doesn't seem to replicate.
Are you sure you're not using a custom lib of TLS? Can you run `ldd` on the `tls_mgm.so` and send us the output?

Best regards,
Răzvan

**Comment by telematico** [comment] 2020-03-05 11:16
Thank you Răzvan.

 I´m using standard debian10 libraries and OpenSips from official DEB repository

/usr/lib/x86_64-linux-gnu/opensips/modules# ldd tls_mgm.so
	linux-vdso.so.1 (0x00007ffd431d5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fadae0ea000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fadae0d0000)
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fadae03e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fadade7d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fadae11f000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fadadb94000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fadadb73000)

apt-cache policy opensips-tls-module
opensips-tls-module:
  Installed: 2.4.7-1
  Candidate: 2.4.7-1
  Version table:
 *** 2.4.7-1 500
        500 https://apt.opensips.org buster/2.4-releases amd64 Packages
        100 /var/lib/dpkg/status
     2.4.6-1 500
        500 https://apt.opensips.org buster/2.4-releases amd64 Packages

**Comment by razvancrainea** [comment] 2020-03-20 12:38
I've finally managed to figure this out - the problem is only happening on [Debian](https://metadata.ftp-master.debian.org/changelogs//main/o/openssl/openssl_1.1.1d-0+deb10u2_changelog), starting with 1.1.0f-5, that is compiling the openssl packages with tls v1.0 and v1.1 disabled by default. I will deploy a fix for this soon.

**Closed** 2020-03-20 13:45 UTC
