### ISSUE TITLE
[CRASH] SIGCHILD while raising an event

### ISSUE THREAD

**Issue by ovidiusas** [OpenSIPS/opensips#3222] opened 2023-10-07 20:10 UTC
**OpenSIPS version you are running**

```
version: opensips 3.4.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 684f6df2f
main.c compiled on 12:50:05 Oct  6 2023 with gcc 9
```

**Describe the traffic that generated the bug**
One single wss connection, right after restart.

**Relevant System Logs**
```
Oct  7 19:16:40 cx-ops01 opensips: INFO:core:daemonize: pre-daemon process exiting with 0

Oct  7 19:20:04 cx-ops01 o[607]: ERROR:tls_openssl:openssl_tls_accept: SSL_ERROR_SYSCALL err=Connection reset by peer(104)
Oct  7 19:20:04 cx-ops01 o[607]: ERROR:tls_openssl:openssl_tls_accept: New TLS connection from X.Y.Z.W:50479 failed to accept
Oct  7 19:20:04 cx-ops01 o[607]: ERROR:tls_openssl:openssl_tls_accept: TLS error: (ret=-1, err=5, errno=104/Connection reset by peer):
Oct  7 19:20:04 cx-ops01 o[607]: ERROR:proto_wss:wss_read_req: cannot fix read connection
Oct  7 19:20:04 cx-ops01 o[707]: CRITICAL:core:sig_usr: segfault in process pid: 707, id: 23
Oct  7 19:20:04 cx-ops01 o[497]: INFO:core:handle_sigs: child process 707 exited by a signal 11
Oct  7 19:20:04 cx-ops01 o[497]: INFO:core:handle_sigs: core was generated
Oct  7 19:20:04 cx-ops01 o[497]: INFO:core:handle_sigs: terminating due to SIGCHLD
Oct  7 19:20:04 cx-ops01 o[572]: INFO:core:sig_usr: signal 15 received
```
The crash is happening while raising an event to the script.

**Comment by razvancrainea** [comment] 2023-10-09 06:10
Closed as duplicate of #3212.

**Closed by razvancrainea** 2023-10-09 06:10 UTC
Labels: bug, duplicate
