### ISSUE TITLE
Unable to use "$" in a password

### ISSUE THREAD

**Issue by gremaudc** [OpenSIPS/opensips#439] opened 2015-03-23 10:35 UTC
Hello,

I never success to set a password with the dollar character ($) in the residential script for configuring the MySQL connection.

Best regards

CG

**Comment by liviuchircu** [comment] 2015-03-23 12:57
Could you please describe exactly what isn't working? Is it an opensipsctl or opensipsdbctl command? The following works properly:

    modparam("dispatcher|usrloc", "db_url", "mysql://root:$te$t$$@192.168.2.133/opensips")

**Comment by gremaudc** [comment] 2015-03-24 12:12
I edit manually the residential script and when a write sometime like that:

modparam("uri", "db_url", "mysql://opensips:$superPass2016$@localhost/opensips")

It doesn't work. In the log file, I can see an MySQL connect error.

**Comment by liviuchircu** [comment] 2015-03-24 12:24
Maybe it is a permissions issue? You can easily double-check with:

    mysql> select * from mysql.user;

**Comment by gremaudc** [comment] 2015-03-24 13:08
Yes of course the first check that I have made is to try to connect using mysql tool and it's work.

mysql -uopensips -p

**Comment by liviuchircu** [comment] 2015-03-24 13:26
Please post the ERRORs you are getting in the logs. For example, if I use the wrong pass, I get:

    ERROR:db_mysql:db_mysql_connect: driver error(1045): Access denied for user 'root'@'192.168.2.133' (using password: YES)

**Comment by gremaudc** [comment] 2015-03-25 06:24
I have exactly the same as you...

**Comment by liviuchircu** [comment] 2015-03-25 09:44
You should come on IRC (irc.freenode.net, #opensips). We should be able to solve this much faster. Meanwhile, if the following fails, then you need to give the *opensips* user access rights:

    sock=($(sudo netstat -tlnp | grep mysql | awk '{print $4}' | tr -s : ' ')); echo "MySQL is listening on: ${con[@]}"; mysql -uopensips -h${sock[0]} -P${sock[1]} -p\$superPass2016\$

**Comment by liviuchircu** [comment] 2015-04-20 10:18
Closing with "unable to reproduce". Please re-open only after helping us with a "working mysql client connect command" along with a "not working opensips db_mysql URL config file fragment + startup ERROR logs" with a password containing at least one "$" char.

**Closed by liviuchircu** 2015-04-20 10:18 UTC
