### ISSUE TITLE
SIGSEGV in pkg_malloc/fm_malloc

### ISSUE THREAD

**Issue by shimaore** [OpenSIPS/opensips#721] opened 2015-12-09 12:38 UTC
This is using opensips 2.1 at commit ee99ac71d8718c93c29e28e6a5266287491f17a5 in a production environment. OpenSIPS is configured to generate coredump, [core.txt](https://github.com/OpenSIPS/opensips/files/56763/core.txt) has `bt full` + `print` of variables in last 3 stack entries.

The issue in the code is relatively simple to understand,

    pf = n->prev;

is followed by

    *pf = n->u.nxt_free;

(lines [167](https://github.com/OpenSIPS/opensips/blob/2.1/mem/f_malloc.c#L167) and [171](https://github.com/OpenSIPS/opensips/blob/2.1/mem/f_malloc.c#L171) of [mem/f_malloc.c](https://github.com/OpenSIPS/opensips/blob/2.1/mem/f_malloc.c)) without checking whether `n->prev` actually exists. However this is fairly old code so there must be some assumptions that made the test unnecessary at the time — but maybe not anymore, or maybe there's some environment dependency I need to check.

**Comment by shimaore** [comment] 2015-12-09 12:58
FWIW there are two locations in mem/f_malloc.c that might have problems with `n->prev` being NULL before calling `fm_remove_free`:
- The first one is [line 353](https://github.com/OpenSIPS/opensips/blob/2.1/mem/f_malloc.c#L353) if `n` === `frag`.
- The other one is the one where this issue goes through, [line 385](https://github.com/OpenSIPS/opensips/blob/2.1/mem/f_malloc.c#L385). The loop at [lines 332-337](https://github.com/OpenSIPS/opensips/blob/2.1/mem/f_malloc.c#L332) never checks `frag->prev`.

Also there are only three places were `->prev` is set to NULL:
- in [`fm_remove_free`](https://github.com/OpenSIPS/opensips/blob/2.1/mem/f_malloc.c#L178)
- in [`fm_malloc_init`](https://github.com/OpenSIPS/opensips/blob/2.1/mem/f_malloc.c#L288) for `qm->last_frag` and `qm->first_frag`.

Not sure I can help much more. :]

**Comment by shimaore** [comment] 2015-12-09 13:20
PR #722 has a workaround for the condition experienced in this case. However this might lead to fragments not being re-used iff `->prev` is already NULL, which might lead to memory leak / memory exhaustion.
This would need to be reviewed by someone more conversant with memory management. :)

**Comment by razvancrainea** [comment] 2015-12-09 13:59
As detailed in #722, the ```->prev``` should never be ```NULL```, otherwise the fragment is in use by somebody else and cannot be in the ```qm->free_hash``` hash.
Here we seem to have a situation where the memory allocator sees the fragment as being free and tries to use it, but in the same time somebody else comes and takes it. Unfortunately we did not solved this concurrency issue yet, but we are tracking it.

**Comment by shimaore** [comment] 2015-12-09 15:29
Sounds like the critical sections of the memory allocator could use mutexes, then?
Is there another allocator I could select at compile time that would be thread-safe?

**Comment by razvancrainea** [comment] 2015-12-09 16:27
There's no thread-safe allocator in opensips, because there's no need for something like that, since opensips is multi-process, not multi-threaded.
The concurrency seems to be related between two processes, and the only scenario I can think about is that somebody allocates some memory in the shared memory (that is indeed thread safe, because it is shared between all processes) and the private memory (that is never thread safe, because it should only be used by a single process, that runs sequentially), or the other way around. Anyhow, I couldn't point out the exact code that's doing this, so this is just an assumption.

**Comment by razvancrainea** [comment] 2015-12-09 16:33
So, just to clarify - the issue is not in the memory allocator itself, but in the cote that uses it wrong. We could guard some critical sections with mutexes, but that will introduce a big performance penalty, and it will only prevent OpenSIPS from crashing, but the code will still use it wrong. The solution of this problem is to find the bad code.

**Comment by shimaore** [comment] 2015-12-09 17:34
OK, so OpenSIPS architecture hasn't changed from what I knew, which is good :)

Could this happen if the outcome of a shm `malloc` was given to the pkg `free` (or the other way around) for example?

**Comment by razvancrainea** [comment] 2015-12-10 10:45
Yes, that is a possible scenario. Or the other way around. Unfortunately I cannot point out where the issue is, otherwise this issue would have been solved. The only information I think we have is that this does not happen too often, because otherwise the crash would be more frequent.

**Comment by shimaore** [comment] 2015-12-10 10:55
Assuming this scenario... is it possible to tag _shm_ vs _pkg_ pointers inside the memory allocator, so that when a module tries to `free`/`realloc`/.. a pointer with the wrong type, OpenSIPS reports it (hopefully with data about where the operation was done)?

**Comment by liviuchircu** [comment] 2015-12-10 11:14
[This feature](https://gitlab.onem.com/onem/sms-routing/issues/32) has been in place in OpenSIPS 1.11+ for almost a year now, if you're using `F_MALLOC`

**Comment by shimaore** [comment] 2015-12-10 23:09
Thank you @liviuchircu -- this should be in [my build](https://github.com/shimaore/docker.opensips/blob/master/Dockerfile#L29); I'll report if I see anything.

@razvancrainea We haven't had a crash yet since I applied #722 to our production code last night — I know it's not a real fix but it's a viable alternative to OpenSIPS crashing a couple times a day. :)  I also assume it doesn't create a memory leak, since the fragments that this code is skipping are already in use.

**Comment by razvancrainea** [comment] 2015-12-11 08:25
@shimaore so the crashes you were experiencing were happening several times per day? That's something unexpected. Did you try to run opensips with the memory debugging allocator?

**Comment by shimaore** [comment] 2015-12-14 14:58
@razvancrainea  yes, we had the issue maybe every hour or so (on one server) on the day it first appeared (we also had it on other servers with a lesser rate). I hadn't done much work with the internals of OpenSIPS so didn't know about the memory debugging allocator, and since it was a SIGSEGV I first tried to figure out where the crash was happening; it's only later that I figured out that the memory allocator was involved and that the actual issue might be incorrect use of the allocator.

We had some low-rate unwanted traffic on those servers while this was happening (INVITEs, with no ACKs) and the problems kind-of disappeared after I blocked the IPs that were causing trouble; however I can't say for sure this was the source of the problem; either way this might be difficult to re-create.

Following up on @liviuchircu 's note, the only `CRIT`-level notices I see on the new versions (with #722 applied, running over the week-end) are `CRITICAL:tm:set_timer: set_timer for 1 list called on a "detached" timer -- ignoring`.
→ Do I need to set `memlog=1` for this to work?

I'll see if I can build a test image with the memory allocator and put it alongside the production images.
→ should I use the QM allocator (`DBG_QM_MALLOC`), or is it enough to use `DBG_F_MALLOC` ?

I guess I could also `abort()` at the point in the allocator where the problem is detected.

**Comment by razvancrainea** [comment] 2015-12-15 09:00
You could try to use the QM allocator to see if this also replicates. If it does, you might have extra information that can help us debug this.

Best regards,
Răzvan

**Comment by james-criscuolo** [comment] 2016-03-08 16:50
Hi @razvancrainea,
  We are seeing a similar type crash in production a few times a day. Here is [a backtrace](https://gist.github.com/james-criscuolo/9c8263920eb0ae84db03) of one, but they all run into `prev` being `null` from that same `pkg_malloc` call in `get_p_notify_body`. Given that we are running 1.10.0 with some of our own patches/modules, I'm not sure how pertinent this will be, but if there is anything I can dig up to help this go away, I'm willing to try.

My main question is, you listed one way this was possible above (mixing up a `shm_malloc` and a `pkg_free`, or vice versa), are there any other potential errors you can think of that could be leading to this?

Thanks,
James

**Comment by james-criscuolo** [comment] 2016-03-08 22:11
Just a quick update here, I've been debugging most of the day and believe I've found something. 

```
--- a/modules/presence/notify.c
+++ b/modules/presence/notify.c
@@ -1226,9 +1226,9 @@ str* get_p_notify_body(str pres_uri, pres_ev_t* event, str* etag, str* publ_body
                                if(row_vals[extra_hdrs_col].val.string_val!= NULL)
                                {
-                                       if (extra_hdrs && !extra_hdrs->s)
+                                       len = strlen(row_vals[extra_hdrs_col].val.string_val);
+                                       if (len > 0 && extra_hdrs && !extra_hdrs->s)
                                        {
-                                               len = strlen(row_vals[extra_hdrs_col].val.string_val);
```

This occurs 3 times (on release 1.10.0, as well as master) in the `get_p_notify body` function. I've been working under the assumption that mallocs of size 0 eventually lead to weirdness, and this code was another example where a `pkg_malloc` of size 0 could occur.

Should a malloc of size 0 be safe? This is not the first set of crashes I've *hopefully* fixed by preventing a malloc of size 0 (the last time around seems to have gone well, we'll see about this one), although the other fix was in a custom module.

**Comment by liviuchircu** [comment] 2016-05-26 08:58
@shimaore: there have been several memory corruption backports on both `2.1` and `2.2` versions, so we strongly recommend updating to latest git.

Should you run into another crash, please recompile with `QM_MALLOC` and `DBG_MALLOC` (you may enable these compile flags through `make menuconfig`), so that OpenSIPS will preemptively attempt to catch memory corruptions as soon as they ensue.

I will close this issue for now, please re-open if necessary.

**Closed by liviuchircu** 2016-05-26 08:58 UTC
Labels: bug
