### ISSUE TITLE
t_wait_for_new_branches, problem of waitting time(not stopped by cancel from caller)

### ISSUE THREAD

**Issue by futsystems** [OpenSIPS/opensips#1237] opened 2017-12-20 15:37 UTC
Problem2: notify_on_event fire notify_route even when the transction is canceled
notify_on_event("E_UL_CONTACT_INSERT","$avp(filter)","fork_call", "20");
UA1 make a call to UA2 at Time1, UA2 will be notified and register to REG, and the subscription will be notified.
UA1 cancel the call at Time2.
UA1 make another call to UA2 immediately again at Time3 ,UA2 will be notified and register to REG again.
if Time3-Time1<20(the timeout of subscription ) the fork_call will be notified twice.one is the Call1 and another is Call2. i think.

so why UA1 cancel the call1, but the fork_call still be notified at Call2? i think if transaction is canceled,then the subscription will not be notified.

![problem-3-1](https://user-images.githubusercontent.com/5887620/34215324-ecba50f4-e5df-11e7-9e1d-37aac3304e00.png)

**Comment by bogdan-iancu** [comment] 2017-12-22 15:09
Hi @futsystems, after some more investigations it turned out not to be a bug, but an unsuspected behavior.
Everything goes back to a change does couple of years ago in how the canceling of a transaction works - according to RFC3261, if you have a branch which provided no reply back yet, upon cancel, the proxy should not sent CANCEL to it and it should not assume it was canceled ; what it has to do is to wait to receive any reply back form that branch until timeout occurs (so incoming reply versus timeout). This "waiting" for not-replied branches translates into the delay into sending/generating the 487 reply back to caller.
Now, in our case, the event-based routing is using a phony branch (it has no SIP signaling) to force the TM internals to keep the transaction awake and alive (no final reply back to caller) until the subscription expires. This phony branch has no replies on it and it will behave as described above upon canceling - it will wait for timeout before closing the branch (as subscription expire hits).

More or less the the INVITE transaction is not yet completed (even if cancel was triggered) because OpenSIPS is waiting to properly handle the phony branch.
This behavior has no negative impact on the UAC (as said, the behavior is not necessarily related to event routing, but more to cancel handling).

Let me know if my explanations covers your case.

**Comment by futsystems** [comment] 2017-12-27 09:58
thank your for  explain of that problem.
but i am still confused about this cancel problem.
condition 1:
Callee is online, Caller make a call, Callee ring, then Caller cancel the call. the 487 is received immediately

condition 2:
Callee is offline,Caller make a call, Callee ring up on registion,then Caller cancel the call, the 487 is delayed.

so does that mean,
in condition 1,first branch got reply from callee(branch created via lookup),so when caller cancel the call.
the branch is canceled and there is no any other branch alive,so caller got 487 immediately.

in condition 2,there are 2 branches, first one have no reply from Callee,just alive and waitting for subscription expires. and second one is created when callee register to proxy. Caller cancel the call, the second branch is canceled,but the first is still alive, when first one hit timeout,then the final 487 is send to caller.

do i understand these stuff right?

**Comment by bogdan-iancu** [comment] 2018-01-03 14:48
Hi @futsystems - just to be sure, do you use t_wait_for_new_branches() in both scenarios ?

**Comment by futsystems** [comment] 2018-01-03 15:09
yes, both scenarios is in same server. just one is online, and another is notified to wakeup.

**Comment by bogdan-iancu** [comment] 2018-01-05 11:26
hi @futsystems , I was able to reproduce your report - indeed, if there is at least one online branch, there will be no waiting to for more branch insertion. 
Let me work out a fix and I will update here.

Thanks for the report!!

**Closed as completed** 2018-04-25 08:19 UTC
Labels: bug, fixed, high-priority
