### ISSUE TITLE
[BUG] ASYNC rest_client requests timeout

### ISSUE THREAD

**Issue by john08burke** [OpenSIPS/opensips#2483] opened 2021-04-23 16:57 UTC
**OpenSIPS version you are running**
```
version: opensips 3.1.1 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 16:01:37 Apr 21 2021 with gcc 8
```

**Describe the bug**
In our test environment, we simulate HTTP API integrations with a localized container serving mock data.  This results in an almost instantaneous response.  If the mock API doesn't inject some delay in the response, OpenSIPS fails to see the response and eventually the request will time out.

Noteworthy logs:
```
Apr 22 18:34:10 [111] DBG:rest_client:w_async_rest_get: async rest get http://0.0.0.0:8889/fake_endpoint 0x7fca9ff68030 (nil) 0x7fca9ff68220
Apr 22 18:34:10 [111] DBG:rest_client:start_async_http_req: perform code: 0, handles: 0
Apr 22 18:34:10 [111] DBG:rest_client:start_async_http_req: libcurl TCP connect: we should wait up to -1ms (timeout=3000ms, poll=20ms)!
Apr 22 18:34:10 [111] DBG:rest_client:start_async_http_req: curl_multi_timeout() returned -1, pausing 20ms...
Apr 22 18:34:10 [111] DBG:rest_client:start_async_http_req: busy waiting 20ms ...
...
...
Apr 22 18:34:13 [111] ERROR:rest_client:start_async_http_req: connect timeout on http://0.0.0.0:8889/fake_endpoint (3s)
```

The issue appears to be with the way OpenSIPS is using libcurl's multi interface, specifically the [curl_multi_timeout](https://curl.se/libcurl/c/curl_multi_timeout.html) function. The code currently checks `curl_multi_timeout` for a -1 return and goes to busy loop instead of checking for completed transfer or available fd.

https://github.com/OpenSIPS/opensips/blob/1178395744929491df8143a37f63d02f49999860/modules/rest_client/rest_methods.c#L739-L743

However, libcurl's docs state the following about `curl_multi_timeout`: 
> Note: if libcurl returns a -1 timeout here, it just means that libcurl currently has no stored timeout value. You must not wait too long (more than a few seconds perhaps) before you call curl_multi_perform() again.

I also noticed that the timeout from `curl_multi_timeout` is never utilized, but rather busy waiting is always done via [connect_poll_interval](https://opensips.org/html/docs/modules/3.1.x/rest_client.html#param_connect_poll_interval) param. There is a micro optimization to be done here, as in theory `curl_multi_timeout` could return value smaller than `connect_poll_interval` or even signal immediate processing should be done via 0.

**To Reproduce**
1. Start OpenSIPS with this [minimal script](https://github.com/OpenSIPS/opensips/files/6366925/minimal.txt)
2. Start up some fast responding web server.
3. Send call.
4. Notice OpenSIPS times out request.

**OS/environment information**
 - Operating System: `Debian 10`
 - OpenSIPS installation: `git 3.1 latest`

**Comment by liviuchircu** [comment] 2021-04-26 10:19
hey, @john08burke!  I tried to reproduce this locally using an Apache on `localhost`, but I can't get it to respond faster than 5 ms, so I couldn't reproduce your specific bug.  However, your suggested fix seems logical and my tests are still passing after applying it.

What's most interesting, though, is that my async GET using libcurl `7.68` actually get stuck in a _different_ sequence of events:

```
Apr 26 12:14:04 [37043] DBG:rest_client:w_async_rest_get: async rest get http://localhost 0x7fef29d16350 (nil) (nil)
Apr 26 12:14:04 [37043] DBG:rest_client:get_multi: multi pool size is now 1
Apr 26 12:14:04 [37043] DBG:rest_client:start_async_http_req: perform code: 0, handles: 1
Apr 26 12:14:04 [37043] DBG:rest_client:start_async_http_req: libcurl TCP connect: we should wait up to 1ms (timeout=20000ms, poll=20ms)!
Apr 26 12:14:04 [37043] DBG:rest_client:start_async_http_req: ongoing transfer on fd 246
Apr 26 12:14:04 [37043] DBG:rest_client:start_async_http_req: >>> add fd 246 to ongoing transfers
...
Apr 26 12:14:04 [37043] DBG:tm:t_handle_async: placing async job into reactor with timeout 0
Apr 26 12:14:04 [37043] DBG:tm:io_watch_add: [UDP_worker] io_watch_add op (246 on 177) (0x56152cc42560, 246, 16, 0x7fef26157d70,1), fd_no=4/8192
Apr 26 12:14:04 [37043] DBG:core:destroy_avp_list: destroying list (nil)
Apr 26 12:14:04 [37043] DBG:core:receive_msg: cleaning up
...
Apr 26 12:14:04 [37043] DBG:tm:t_resume_async: resuming on fd 246, transaction 0x7fef261540d8 
Apr 26 12:14:04 [37043] DBG:rest_client:_resume_async_http_req: resume async processing...
Apr 26 12:14:04 [37043] DBG:rest_client:_resume_async_http_req: perform result: 0, running: 1
Apr 26 12:14:04 [37043] DBG:rest_client:_resume_async_http_req: transfer in progress...
```

There seems to be an extraneous `|| !enable_expect_100` exit condition within the while loop, preventing `curl_multi_perform()` to be called multiple times after a `CURLM_OK` return code, which should actually be the correct usage flow.  Removing the condition unblocks my own fast async transfers, so I'll get that issue fixed in a separate commit.

Cheers!

**Closed** 2021-04-26 10:23 UTC
Labels: bug

**Comment by vbomfim** [comment] 2021-12-11 00:09
Hi guys,

  I need your help.
  As I see as fixed, I assume that I'm doing something wrong.
  The async rest_post is not triggering before receiving data.
  The log shows "connected, but transfer timed out (5s)", but only after it receives the response after the timeout.
  I'm running:
```
   async(rest_post($var(connectURL), $json_compact(req), "application/json" , $var(resp), $var(ct), $var(rcode)), resume);
```
Config:
```
OPENSIPS_VERSION = 3.2
OPENSIPS_BUILD = nightly or releases
modparam("rest_client", "curl_timeout", 5)
modparam("rest_client", "connection_timeout", 5)
modparam("rest_client", "connect_poll_interval", 20)
```
Log:
```
Dec 10 23:38:08 [17] DBG:rest_client:w_async_rest_post: async rest post 'http://192.168.2.44:9099/v1/' 0x7f4f12f996b8 0x7f4f12f99898 0x7f4f12f999e0
Dec 10 23:38:08 [17] DBG:rest_client:get_multi: multi pool size is now 1
Dec 10 23:38:08 [17] DBG:rest_client:start_async_http_req: perform code: 0, handles: 1
Dec 10 23:38:08 [17] DBG:rest_client:start_async_http_req: libcurl TCP connect: we should wait up to 199ms (**timeout=5000ms, poll=20ms**)!
Dec 10 23:38:08 [17] DBG:rest_client:start_async_http_req: busy waiting 20ms ...
Dec 10 23:38:08 [17] DBG:rest_client:start_async_http_req: perform code: 0, handles: 1
Dec 10 23:38:08 [17] DBG:rest_client:start_async_http_req: ongoing transfer on fd 4`
Dec 10 23:38:08 [17] DBG:rest_client:start_async_http_req: >>> add fd 4 to ongoing transfers
Dec 10 23:38:08 [17] DBG:tm:t_handle_async: placing async job into reactor with timeout 0
Dec 10 23:38:08 [17] DBG:tm:io_watch_add: [UDP_worker] io_watch_add op (4 on 96) (0x55c78652c120, 4, 16, 0x7f4f11375548,1), fd_no=4/41943
Dec 10 23:38:08 [17] DBG:core:destroy_avp_list: destroying list (nil)
**Dec 10 23:38:08** [17] DBG:core:receive_msg: cleaning up
    15s later, but the timeout is 5s.
**Dec 10 23:38:23** [17] DBG:tm:t_resume_async: resuming on fd 4, transaction 0x7f4f1137d298 
Dec 10 23:38:23 [17] DBG:rest_client:_resume_async_http_req: resume async processing...
Dec 10 23:38:23 [17] DBG:rest_client:_resume_async_http_req: perform result: 0, running: 0
Dec 10 23:38:23 [17] DBG:rest_client:del_transfer: del fd 4
Dec 10 23:38:23 [17] ERROR:rest_client:_resume_async_http_req: **connected, but transfer timed out (5s)**
Dec 10 23:38:23 [17] DBG:rest_client:_resume_async_http_req: HTTP response code: 0
Dec 10 23:38:23 [17] DBG:tm:io_watch_del: [UDP_worker] io_watch_del op on index -1 4 (0x55c78652c120, 4, -1, 0x10,0x1) fd_no=5 called
Dec 10 23:38:23 [17] async rest_post() with -3, user=4384981095
Dec 10 23:38:23 [17] DBG:core:comp_scriptvar: int 26: -3 / 0
Dec 10 23:38:23 [17] async rest_post() failed with -3, user=4384981095
Dec 10 23:38:23 [17] DBG:core:MD5StringArray: MD5 calculated: 3beb091d49b6a2e245ae9c8c3efb98c5
Dec 10 23:38:23 [17] DBG:core:parse_headers: flags=ffffffffffffffff
Dec 10 23:38:23 [17] DBG:tm:cleanup_uac_timers: RETR/FR timers reset
Dec 10 23:38:23 [17] DBG:tm:set_timer: relative timeout is 500000
Dec 10 23:38:23 [17] DBG:tm:insert_timer_unsafe: [4]: 0x7f4f1137d3e0 (40200000)
Dec 10 23:38:23 [17] DBG:tm:insert_timer_unsafe: [0]: 0x7f4f1137d410 (44)
Dec 10 23:38:23 [17] DBG:tm:_reply_light: reply sent out. buf=0x7f4f131e0360: SIP/2.0 5..., shmem=0x7f4f113755c0: SIP/2.0 5
Dec 10 23:38:23 [17] DBG:tm:_reply_light: finished
Dec 10 23:38:23 [17] DBG:tm:do_t_cleanup: transaction 0x7f4f1137d298 already updated! Skipping update!
Dec 10 23:38:23 [17] DBG:tm:t_unref: UNREF_UNSAFE: [0x7f4f1137d298] after is 0
```
