### ISSUE TITLE
Opensips crashes as a result of multiple failed SSL connections

### ISSUE THREAD

**Issue by StephBrown0** [OpenSIPS/opensips#2762] opened 2022-02-25 15:59 UTC
**OpenSIPS version you are running**

```
docker exec opensips-edgesbc opensips -V
version: opensips 3.2.0-dev (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: 41a3230df
main.c compiled on  with gcc 8
```

**Crash Core Dump**

Please see Segfault_Opensips_v4.0.66_Core_Dump.txt in the below google drive:
https://drive.google.com/drive/folders/1iqowEnsNBRAp7tyQzRKfrMGQlxHUvA1F?usp=sharing

**Describe the traffic that generated the bug**
```
At the time Opensips was attempting to establish TLS connections to a number of endpoints. Some were successful and some not.  Please see PCAP Segfault_Opensips_v4.0.66.pcap in the below google drive for all traffic at the time of the crash:
https://drive.google.com/drive/folders/1iqowEnsNBRAp7tyQzRKfrMGQlxHUvA1F?usp=sharing
```

**To Reproduce**
```
Steps to reproduce the behavior:
Example:
1. Start OpenSIPS
2. Ensure there are TLS endpoints in the dispatcher table (we have 8). I assume that some of these TLS endpoints will need to fail to establish in order to trigger the bug. 
3. Check OpenSIPS crashed
```

**Relevant System Logs**
Please see full System logs in Segfault_Opensips_v4.0.66_Opensips_Logs.log:
https://drive.google.com/drive/folders/1iqowEnsNBRAp7tyQzRKfrMGQlxHUvA1F
```
"log":"Feb 24 16:06:25 [54] ERROR:tm:msg_send: send() to 85.55.66.77:5061 for proto tls/3 failed\n","stream":"stderr","time":"2022-02-24T16:06:25.891369852Z"}
{"log":"Feb 24 16:06:25 [54] ERROR:tm:t_uac: attempt to send to 'sip:85.55.66.77:5061;transport=tls' failed\n","stream":"stderr","time":"2022-02-24T16:06:25.891428546Z"}
{"log":"Feb 24 16:06:25 [54] ERROR:tm:msg_send: send() to 85.55.66.78:5061 for proto tls/3 failed\n","stream":"stderr","time":"2022-02-24T16:06:25.891443143Z"}
{"log":"Feb 24 16:06:25 [54] ERROR:tm:t_uac: attempt to send to 'sip:85.55.66.78:5061;transport=tls' failed\n","stream":"stderr","time":"2022-02-24T16:06:25.891456033Z"}
{"log":"Feb 24 16:06:25 [54] ERROR:tm:msg_send: send() to 185.63.142.76:5061 for proto tls/3 failed\n","stream":"stderr","time":"2022-02-24T16:06:25.892078383Z"}
{"log":"Feb 24 16:06:25 [54] ERROR:tm:t_uac: attempt to send to 'sip:185.63.142.76:5061;transport=tls' failed\n","stream":"stderr","time":"2022-02-24T16:06:25.892103599Z"}
{"log":"Feb 24 16:06:26 [110] ERROR:tls_wolfssl:_wolfssl_tls_conn_shutdown: no ssl data\n","stream":"stderr","time":"2022-02-24T16:06:26.98755915Z"}
{"log":"Feb 24 16:06:26 [110] ERROR:tls_wolfssl:_wolfssl_tls_conn_shutdown: no ssl data\n","stream":"stderr","time":"2022-02-24T16:06:26.988031029Z"}
{"log":"Feb 24 16:06:27 [110] ERROR:tls_wolfssl:_wolfssl_tls_conn_shutdown: no ssl data\n","stream":"stderr","time":"2022-02-24T16:06:27.23918138Z"}
{"log":"Feb 24 16:06:27 [110] ERROR:tls_wolfssl:_wolfssl_tls_conn_shutdown: no ssl data\n","stream":"stderr","time":"2022-02-24T16:06:27.239614166Z"}
{"log":"Feb 24 16:06:27 [110] ERROR:tls_wolfssl:_wolfssl_tls_conn_shutdown: no ssl data\n","stream":"stderr","time":"2022-02-24T16:06:27.240167138Z"}
{"log":"Feb 24 16:06:27 [59] --[45e111f36c8daa9e3018b93e70bc1df2@85.118.157.5:5060] ## NEW REQUEST MESSAGE ## - from:[85.118.157.5]:[5060] | method:[OPTIONS]cseq:[102]\r\n","stream":"stderr","time":"2022-02-24T16:06:27.645373964Z"}
{"log":"Feb 24 16:06:27 [59] [45e111f36c8daa9e3018b93e70bc1df2@85.118.157.5:5060] - REQINIT\r\n","stream":"stderr","time":"2022-02-24T16:06:27.645421701Z"}
{"log":"Feb 24 16:06:29 [101] --[6b3ba0c7286111a4-1566@172.16.7.29] ## NEW REQUEST MESSAGE ## - from:[172.16.7.29]:[47486] | method:[OPTIONS]cseq:[10]\r\n","stream":"stderr","time":"2022-02-24T16:06:29.038319529Z"}
{"log":"Feb 24 16:06:29 [101] [6b3ba0c7286111a4-1566@172.16.7.29] - REQINIT\r\n","stream":"stderr","time":"2022-02-24T16:06:29.038402153Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_add: [TCP_main] epoll_ctl ADD failed: Bad file descriptor [9]\n","stream":"stderr","time":"2022-02-24T16:06:36.037282524Z"}
{"log":"Feb 24 16:06:36 [107] NOTICE:tls_wolfssl:verify_callback: depth = 0, verify success\n","stream":"stderr","time":"2022-02-24T16:06:36.072339065Z"}
{"log":"Feb 24 16:06:36 [107] INFO:tls_wolfssl:_wolfssl_tls_async_connect: new TLS connection to 85.118.157.5:5061 established\n","stream":"stderr","time":"2022-02-24T16:06:36.085910728Z"}
{"log":"Feb 24 16:06:36 [101] NOTICE:tls_wolfssl:verify_callback: depth = 0, verify success\n","stream":"stderr","time":"2022-02-24T16:06:36.097065395Z"}
{"log":"Feb 24 16:06:36 [101] INFO:tls_wolfssl:_wolfssl_tls_async_connect: new TLS connection to 85.118.157.152:5061 established\n","stream":"stderr","time":"2022-02-24T16:06:36.112203341Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281444078Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281486711Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281500328Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281511745Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281533022Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281544658Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281555815Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281567189Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281578009Z"}
{"log":"Feb 24 16:06:36 [110] ERROR:core:io_watch_del: BUG - [TCP_main] trying to del fd 417 with flags 1 2\n","stream":"stderr","time":"2022-02-24T16:06:36.281588615Z"}

{"log":"Feb 24 16:07:38 [110] ERROR:core:io_watch_del: [TCP_main] trying to delete already erased entry 417 in the hash(-1, 0, (nil)) )\n","stream":"stderr","time":"2022-02-24T16:07:38.141793234Z"}
{"log":"Feb 24 16:07:38 [110] ERROR:core:io_watch_del: [TCP_main] trying to delete already erased entry 417 in the hash(-1, 0, (nil)) )\n","stream":"stderr","time":"2022-02-24T16:07:38.141798294Z"}

{"log":"Feb 24 16:07:45 [110] CRITICAL:core:io_watch_del: \n","stream":"stderr","time":"2022-02-24T16:07:46.086474772Z"}
{"log":"\u003e\u003e\u003e fd_array idx 6 (fd=417) points to bogus map (fd=-1,type=0,flags=0,data=(nil))\n","stream":"stderr","time":"2022-02-24T16:07:46.086484996Z"}
{"log":"\n","stream":"stderr","time":"2022-02-24T16:07:46.086496456Z"}
{"log":"It seems you have hit a programming bug.\n","stream":"stderr","time":"2022-02-24T16:07:46.086506316Z"}
{"log":"Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues\n","stream":"stderr","time":"2022-02-24T16:07:46.086516429Z"}
{"log":"\n","stream":"stderr","time":"2022-02-24T16:07:46.086527089Z"}
{"log":"Feb 24 16:07:45 [110] CRITICAL:core:io_watch_del: \n","stream":"stderr","time":"2022-02-24T16:07:46.086536636Z"}
{"log":"\u003e\u003e\u003e unused fd_map fd=417 has bogus data (fd=-1,flags=20000000,data=(nil))\n","stream":"stderr","time":"2022-02-24T16:07:46.086546746Z"}
{"log":"\n","stream":"stderr","time":"2022-02-24T16:07:46.086557173Z"}
{"log":"It seems you have hit a programming bug.\n","stream":"stderr","time":"2022-02-24T16:07:46.086566613Z"}
{"log":"Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues\n","stream":"stderr","time":"2022-02-24T16:07:46.08657646Z"}
{"log":"\n","stream":"stderr","time":"2022-02-24T16:07:46.086586796Z"}
{"log":"Feb 24 16:07:45 [110] CRITICAL:core:io_watch_del: \n","stream":"stderr","time":"2022-02-24T16:07:46.0865962Z"}
{"log":"\u003e\u003e\u003e used fd map fd=418 is not present in fd_array (fd=418,type=19,flags=2,data=0x7f2399959198)\n","stream":"stderr","time":"2022-02-24T16:07:46.08660615Z"}
{"log":"\n","stream":"stderr","time":"2022-02-24T16:07:46.086616646Z"}
{"log":"It seems you have hit a programming bug.\n","stream":"stderr","time":"2022-02-24T16:07:46.086626046Z"}
{"log":"Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues\n","stream":"stderr","time":"2022-02-24T16:07:46.086635866Z"}
{"log":"\n","stream":"stderr","time":"2022-02-24T16:07:46.086654096Z"}
{"log":"Feb 24 16:07:45 [110] CRITICAL:core:io_watch_del: [TCP_main] check failed after successful fd del (fd=417,flags=0, sflags=2) over map (fd=-1,type=0,data=(nil),flags=536870912) erase=1\n","stream":"stderr","time":"2022-02-24T16:07:46.086665633Z"}
{"log":"Feb 24 16:07:45 [110] CRITICAL:core:io_watch_add: \n","stream":"stderr","time":"2022-02-24T16:07:46.08667768Z"}
{"log":"\u003e\u003e\u003e used fd map fd=418 is not present in fd_array (fd=418,type=19,flags=80000002,data=0x7f2399959198)\n","stream":"stderr","time":"2022-02-24T16:07:46.086687947Z"}
{"log":"\n","stream":"stderr","time":"2022-02-24T16:07:46.086698714Z"}
{"log":"It seems you have hit a programming bug.\n","stream":"stderr","time":"2022-02-24T16:07:46.086708177Z"}
{"log":"Please help us make OpenSIPS better by reporting it at https://github.com/OpenSIPS/opensips/issues\n","stream":"stderr","time":"2022-02-24T16:07:46.08671812Z"}
{"log":"\n","stream":"stderr","time":"2022-02-24T16:07:46.086728804Z"}
{"log":"Feb 24 16:07:45 [107] CRITICAL:core:sig_usr: segfault in process pid: 107, id: 59\n","stream":"stderr","time":"2022-02-24T16:07:46.086738294Z"}
{"log":"Feb 24 16:07:45 [107] qm_status (0x7f239b450010):\n","stream":"stderr","time":"2022-02-24T16:07:46.086748531Z"}
{"log":"Feb 24 16:07:45 [107]  heap size= 16777216\n","stream":"stderr","time":"2022-02-24T16:07:46.086758454Z"}
{"log":"Feb 24 16:07:45 [107]  used= 3059192, used+overhead=3826192, free=12951024\n","stream":"stderr","time":"2022-02-24T16:07:46.086768327Z"}
{"log":"Feb 24 16:07:45 [107]  max used (+overhead)= 3898632\n","stream":"stderr","time":"2022-02-24T16:07:46.086778477Z"}
{"log":"Feb 24 16:07:45 [110] CRITICAL:core:io_watch_add: [TCP_main] check failed after successful fd add (fd=417,type=19,data=0x7f2399a626e8,flags=2) already=0\n","stream":"stderr","time":"2022-02-24T16:07:46.086789187Z"}
{"log":"Feb 24 16:07:45 [107] failed to walk through all fragments (0x7f239c450010 0x7f239b485508 0x7f239c44ffe0)\n","stream":"stderr","time":"2022-02-24T16:07:46.086800381Z"}
{"log":"Feb 24 16:07:45 [107]  dumping summary of all alloc'ed. fragments:\n","stream":"stderr","time":"2022-02-24T16:07:46.086811024Z"}
```

**OS/environment information**
debian:bullseye
 deb https://apt.opensips.org bullseye 3.3-nightly
 deb https://apt.opensips.org bullseye cli-nightly
&& apt-get install sqlite3 iproute2 ruby opensips autoconf automake libtool opensips-tls-openssl-module opensips-tls-wolfssl-module opensips-cli opensips-sqlite-module opensips-http-modules opensips-dialplan-module opensips-dbg opensips-xml-module opensips-rabbitmq-modules opensips-xmlrpc-module opensips-tlsmgm-module opensips-tls-module opensips-prometheus-module opensips-json-module -y \

**Comment by razvancrainea** [comment] 2022-03-09 11:47
Looks like a duplicate of #2724, let's follow up there.

**Closed by razvancrainea** 2022-03-09 11:47 UTC
