### ISSUE TITLE
reinvite_ping_interval 

### ISSUE THREAD

**Issue by mrsanvicente** [OpenSIPS/opensips#1287] opened 2018-02-19 19:43 UTC
Hello,

I am configuring reinvite_ping_interval.  I already configured the prerequisites, but opensips is no generating reinvite.

Any advise:

#### Transaction Module
loadmodule "tm.so"
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 30)
modparam("tm", "restart_fr_on_each_reply", 0)
modparam("tm", "onreply_avp_mode", 1)

#### Record Route Module
loadmodule "rr.so"
modparam("rr", "append_fromtag", 1)

loadmodule "dialog.so"
modparam("dialog", "dlg_match_mode", 2)
modparam("dialog", "default_timeout", 21600)  # 6 hours timeout
modparam("dialog", "profiles_with_value", "concalls; gwcalls; inbound;outbound")
modparam("dialog", "profiles_no_value", "local; facility")
modparam("dialog", "rr_param", "lts")
modparam("dialog", "options_ping_interval", 60)
modparam("dialog", "reinvite_ping_interval", 900) # 15 minute timeout

       if ( is_method("INVITE")) {

                                     xlog("test  '$ru'");
                                     rewritehostport("x.x.x.x:5060");
        }

**Comment by bogdan-iancu** [comment] 2018-02-27 09:28
@mrsanvicente , how do you create your dialog in the script ?

**Comment by bogdan-iancu** [comment] 2018-02-27 10:09
closing as it is duplicate of #1274

**Closed by bogdan-iancu** 2018-02-27 10:09 UTC
